### ISSUE TITLE
**Describe the bug**

### ISSUE THREAD

**Issue by feyyyyylo** [webpack/webpack-dev-middleware#1020]
**Describe the bug**
Use the following 2 UIiewRepresentable to mapping Rendereriew in the SwiftUI environment. They both can't guarantee the videoRendererView is always rendering in the SwiftUI view. In some cases, the swiftUI view just lost the video rendererView and displaying an empty view. 

````
struct VideoRendererView: UIViewRepresentable {
    let rendererView: RendererView

    func makeUIView(context: Context) -> RendererView {
        return rendererView
    }

    func updateUIView(_ uiView: RendererView, context: Context) {
    }
}
````

````
struct RenderInboundVideoView: UIViewRepresentable {

    @Binding var view:RendererView!

    func makeUIView(context: Context) -> UIView {
        return UIView()
    }

    func updateUIView(_ uiView: UIView, context: Context) {
        for view in uiView.subviews {
            view.removeFromSuperview()
        }
        if (view != nil) {
            uiView.addSubview(view)
        }
    }
}
````

Need a suggestion in how to use RendererView in swiftUI view. 

__Originally posted by @AmyL219 in https://github.com/Azure/Communication/issues/369__

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by SarawutSr** [comment]
I face this issue for 2 weeks now. My application is using the the [Azure Communication Calling iOS SDK version 2.11.0](https://github.com/Azure/Communication/releases/tag/v2.11.0) for joining the ACS group call

When I run the application with iOS 17.4+. in simulator, it always crashed all the time at function on above.

By the way, it working fine with iOS < 17.2.

Can you help to share how to solve/tackle this issue?
