### ISSUE TITLE
Use file system instead of memory so rebuild isn't necessary after server restart

### ISSUE THREAD

**Issue by tuckerconnelly** [webpack/webpack-dev-middleware#104]
I'm using nodemon to restart my server when there's a file change. Problem is webpack-dev-middleware rebuilds webpack on every restart, and webpack build is slow af. I think ya'll should use the file system to cache the webpack build so a rebuild isn't necessary when the server restarts.

**Comment by SpaceK33z** [comment]
This is done on purpose, see #53.

**Comment by xjamundx** [comment]
Our webpack build takes 30s at PayPal and we restart our app all the time, so this would be worth forking for. Any interest in making this an option?

**Comment by rtsao** [comment]
I've had success with https://github.com/mzgoddard/hard-source-webpack-plugin
