### ISSUE TITLE
Compatibility with DllPlugin?

### ISSUE THREAD

**Issue by DelvarWorld** [webpack/webpack-dev-middleware#106]
I'm building a dll bundle using the dll plugin. My Dll step builds a file `static/dist/hash.json`.

My public path is http://localhost:3001/dist/

However http://localhost:3001/dist/hash.json doesn't load.

My webpack config has

    new webpack.DllReferencePlugin({ 
      context: path.join( __dirname, '../' ),
      manifest: require( path.join( assetsPath, 'manifests/assets-manifest.json' ) ),
    }),

which is the correct path to the manifest created by the DllPlugin.

**Comment by SpaceK33z** [comment]
Why do you want to load the json file with webpack-dev-middleware? This json file should only be used by the compiler. Also see [this article](http://engineering.invisionapp.com/post/optimizing-webpack/) for a very nice explanation about how it works.

**Comment by SpaceK33z** [comment]
Closing for now, but let me know if you still have a problem.
