### ISSUE TITLE
waitUntilValid callback always called immediately when using MultiCompiler.

### ISSUE THREAD

**Issue by gdborton** [webpack/webpack-dev-middleware#107]
It seems that this snippet always hits the first code path when using a compiler built with an array of configurations, because watching is an instance of [MultiCompiler](https://github.com/webpack/webpack/blob/master/lib/MultiCompiler.js#L9) which doesn't have a running property.

```javascript
webpackDevMiddleware.waitUntilValid = function(callback) {
  callback = callback || function(){};
  if (!watching || !watching.running) callback();
  else ready(callback, {});
};
```

**Comment by SpaceK33z** [comment]
PR #100 would fix this problem. Not sure if we're going to merge that PR though.

**Comment by gdborton** [comment]
Is there a reason that it wouldn't get merged, or another route that would get this working?

**Comment by SpaceK33z** [comment]
I still need to check that PR out, and ensure that nothing breaks of it.
