### ISSUE TITLE
Multiple entry points are not processed

### ISSUE THREAD

**Issue by gvidon** [webpack/webpack-dev-middleware#109]
I can't make this config work, when run it with `webpack-dev-middleware`. It builds with no issues with webpack, but when I apply it to webpack-dev-middleware it fails.

Software versions:
* webpack-dev-middleware 1.6.1
* webpack 2.1.0-beta.17

How I run it with webpack-dev-middleware
![2016-07-22 23 35 50](https://cloud.githubusercontent.com/assets/58164/17070518/0b40a242-5065-11e6-967d-85aebe2093c5.png)

Errors during compilation
![2016-07-22 23 36 44](https://cloud.githubusercontent.com/assets/58164/17070540/29e95ee6-5065-11e6-9770-73341263a8e3.png)

Config itself
```javascript
var
	CopyWebpackPlugin = require('copy-webpack-plugin'),
	path = require('path'),
	webpack = require('webpack');

module.exports = {
	context: path.resolve(__dirname, '..'),
	devtool: 'cheap-module-eval-source-map',

	entry: {
		app: './app/index',

		vendor: [
			'./node_modules/isomorphic-fetch',
			'./node_modules/jquery',
			'./node_modules/keymirror',
			'./node_modules/lodash',
			'./node_modules/moment',
			'./node_modules/react',
			'./node_modules/react-addons-css-transition-group',
			'./node_modules/react-addons-shallow-compare',
			'./node_modules/react-dom',
			'./node_modules/react-redux',
			'./node_modules/react-redux-form',
			'./node_modules/react-router',
			'./node_modules/react-router-redux',
			'./node_modules/redux',
			'./node_modules/redux-api',
			'./node_modules/redux-thunk'
		]
  },

	output: {
		path: path.join(__dirname, '..', 'build'),
		filename: 'bundle.js',
		pathinfo: true,
		publicPath: '/'
	},

	plugins: [
		new CopyWebpackPlugin([{from: path.join(__dirname, '..', 'index.html'), to: ''}]),
		new webpack.optimize.CommonsChunkPlugin({name: 'vendor', filename: 'vendor.bundle.js'}),
		new webpack.DefinePlugin({__DEV__: false})
	],

	module: {
		noParse: /\.min\.js/,

		loaders: [
			{
				test: /\.js$/,
				loaders: ['babel'],

				query: {
					cacheDirectory: true,
					presets: ['es2015-webpack', 'stage-0', 'react']
				},

				exclude: /node_modules/
			},

			{
				test: /\.css$/,

				loaders: [
					'style?sourceMap',
					'css?modules&camelCase=dashes&importLoaders=1&localIdentName=[local]__[hash:base64:5]'
				]
			},

			{test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'},
			{test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/, loader : 'file-loader'}
		]
	},

	resolve: {
		extensions: ['', '.js'],

		modules: [
			path.resolve(__dirname, '..', 'app'),
			'node_modules',
			path.resolve(__dirname, '..', 'app', 'Forbidden')
		]
	}
};
```

While debugging failing code I found it always consider `.entry` of config to be a string. Is it a webpack-dev-middleware issue or I really missed something?

**Comment by SpaceK33z** [comment]
Do you still have this issue with the most recent webpack version? Just checking before I'm going to debug this.

**Comment by SpaceK33z** [comment]
ping @gvidon

**Comment by gvidon** [comment]
@SpaceK33z sorry, missed your first message. Will try later today and let you know.

**Comment by gvidon** [comment]
@SpaceK33z it now through another error but at the same place. Webpack version is **2.1.0-beta.22**.

![2016-09-19 23 02 06](https://cloud.githubusercontent.com/assets/58164/18647231/bea33134-7ebd-11e6-8b28-9b15ecbaeb7e.png)

**Comment by SpaceK33z** [comment]
Unfortunately I can't reproduce your issue. Could you make a test repo where this happens, with as little of code as possible? This helps pinpointing the problem.

**Comment by gvidon** [comment]
Ok, will do in a couple of days.

**Comment by gvidon** [comment]
@SpaceK33z after reviewing the code, I have done some refactoring and don't have this error any longer. Thank you.
