### ISSUE TITLE
Options of outputfilesystem is confusing

### ISSUE THREAD

**Issue by 29984608** [webpack/webpack-dev-middleware#1112]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In the example docs, we can use `devMiddleware.outputFileSystem`. In fact, if I use this example docs, the code will prompt undefined error of `outputFileSystem`. I must use `devMiddleware.context.outputFileSystem` 

### Your Proposal for Changes

Change examle docs for outputFileSystem options

**Comment by alexander-akait** [comment]
Yes, valid usage, using `devMiddleware.context.outputFileSystem`, feel free to send a fix in docs

**Comment by snitin315** [comment]
I will fix it.
