### ISSUE TITLE
Support for https server config option?

### ISSUE THREAD

**Issue by gsccheng** [webpack/webpack-dev-middleware#112]
Hi, it doesn't look like we can configure the server for HTTPS like in webpack-dev-server?

[http://webpack.github.io/docs/webpack-dev-server.html#cli](http://webpack.github.io/docs/webpack-dev-server.html#cli)

Thanks.

**Comment by SpaceK33z** [comment]
This package is only for the middleware, so why would you need HTTPS here?

**Comment by gsccheng** [comment]
Yeah, nevermind, thanks.

I was asking because in my project I'm getting: 
```
Mixed Content: The page at 'https://myproj.com' was loaded over HTTPS, but requested an insecure script 'http://localhost:3001/dist/main-478a3819d101e4167c3c.js'. This request has been blocked; the content must be served over HTTPS.
```

But, as you mention this isn't the responsibility of this module. I just need to manually configure the server to HTTPS.
