### ISSUE TITLE
Range support looks like it has issues

### ISSUE THREAD

**Issue by hnry** [webpack/webpack-dev-middleware#113]
The range support doesn't look right:

https://github.com/webpack/webpack-dev-middleware/blob/264dd2bc1810b4ce8a5647c90076433e0da7e8bc/middleware.js#L169
- don't think there is such a **request** header "Accept-Ranges"
- either way, it won't ever match, node.js req headers are always lower cased

[update] updated link to point to correct line to latest commit instead of master

**Comment by SpaceK33z** [comment]
Are you interested in making a PR to fix this?

**Comment by hnry** [comment]
Thanks for asking @SpaceK33z
