### ISSUE TITLE
[Question] Write specific files to disk?

### ISSUE THREAD

**Issue by emjaksa** [webpack/webpack-dev-middleware#115]
I use the file loader to transform .jsp files which need to be written to disk. Is there an option to exclude these files from been handled in memory and written to disk?

**Comment by SpaceK33z** [comment]
The dev-server cannot write files to disk, and will not get this functionality. Perhaps [write-file-webpack-plugin](https://github.com/gajus/write-file-webpack-plugin) can help you out?

**Comment by SpaceK33z** [comment]
Closing because question was answered.

**Comment by dutchenkoOleg** [comment]
Thank you! It helped me
