### ISSUE TITLE
A wild test appeared

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack-dev-middleware#121]
So I started with writing the first test for this repo... Finally!

Here's a roadmap of things to test:

- [x] `GetFilenameFromUrl`
- [x] full test with express
- [x] `webpackDevMiddleware.waitUntilValid`
- [x] `webpackDevMiddleware.invalidate`
- [x] `webpackDevMiddleware.close`
- [x] `handleRangeHeaders`
- [x] compiler `done` event
- [ ] compiler `invalid` event
- [ ] compiler `watch-run` event
- [ ] compiler `run` event
- [x] lazy mode
- [x] `reporter` option
- [x] `serverSideRender` option
- [x] `/index.html` should work
- [x] given `headers` should be set on response

**Comment by SpaceK33z** [comment]
@wuct, I started writing some tests. I'm having some trouble with testing your `serverSideRender` option. See [`Server.test.js`](https://github.com/webpack/webpack-dev-middleware/blob/master/test/Server.test.js#L90). Would you be able to help me by either fixing it with a PR, or giving some clues?

**Comment by wuct** [comment]
@SpaceK33z I fix the test by #122.

**Comment by wuct** [comment]
In short, requests for bundle files would still be responded by __webpack-dev-middleware__, so the next middleware would never be invoked.
