### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by vjpr** [webpack/webpack-dev-middleware#1257]
### Modification Proposal

Currently, `stats.toString()` is printed on the `compiler.hooks.afterDone` hook, inside a `process.nextTick()` call.

I want to print something after that stats have all printed.

The `nextTick` means that even if I override the hook, I still can't print after it.

I want to be able to disable this hook from being set.

**Comment by alexander-akait** [comment]
You can create own plugin and use nextTick too
