### ISSUE TITLE
[5.3.2] .d.ts references dom Request/Response

### ISSUE THREAD

**Issue by AviVahl** [webpack/webpack-dev-middleware#1270]
### Bug report

new release changed the typings, and where it says `Request/Response`, it references global ones defined by `dom.d.ts`.

### Actual Behavior

```
node_modules/webpack-dev-middleware/types/index.d.ts:168:21 - error TS2344: Type 'Request' does not satisfy the constraint 'IncomingMessage'.
  Type 'Request' is missing the following properties from type 'IncomingMessage': aborted, httpVersion, httpVersionMajor, httpVersionMinor, and 46 more.

168   headers?: Headers<Request, Response>;
```

### Expected Behavior

It should pass type checking in strict typescript projects that don't specify `skipLibCheck`.

### How Do We Reproduce?

```
mkdir dev-middleware-bug
cd dev-middleware-bug
npm init -y
npm i webpack webpack-dev-middleware typescript
npx tsc --init --skipLibCheck false
echo "import 'webpack-dev-middleware';" > a.ts
npx tsc --noEmit
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux 5.17 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 56.48 GB / 62.43 GB
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
  Packages:
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    webpack: ^5.72.1 => 5.72.1 
    webpack-dev-middleware: ^5.3.2 => 5.3.2 
```

**Comment by AviVahl** [comment]
@alexander-akait I believe this is a regression from these changes: https://github.com/webpack/webpack-dev-middleware/pull/1260/files#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccce

**Comment by luoguoxiong** [comment]
I have the same problem~

**Comment by nuintun** [comment]
+1

https://github.com/webpack/webpack-dev-middleware/blob/f88067d31f7f639381cd3fcf6d7c2fd2f23d92f9/types/index.d.ts#L175-L178

`Request_1` and `Response_1` generic definition is unused.

**Comment by alexander-akait** [comment]
@AviVahl Weird, we don't touch ts files, just update deps, maybe regression in ts?

**Comment by alexander-akait** [comment]
Found ts regression, when you have:
```
/**
 * @template {IncomingMessage} Request
 * @template {ServerResponse} Response
 * @typedef {Object} Options
 * @property {{[key: string]: string}} [mimeTypes]
 * @property {boolean | ((targetPath: string) => boolean)} [writeToDisk]
 * @property {string} [methods]
 * @property {Headers<Request, Response>} [headers]
 * @property {NonNullable<Configuration["output"]>["publicPath"]} [publicPath]
 * @property {Configuration["stats"]} [stats]
 * @property {boolean} [serverSideRender]
 * @property {OutputFileSystem} [outputFileSystem]
 * @property {boolean | string} [index]
 */
 ```
 
ts 4.6 consider `Request` and `Response` as global DOM classes (as @AviVahl mention), not as local generics, very weird, let's downdgrade and fix types and report
