### ISSUE TITLE
TypeError: Object [object Object] has no method 'isAbsolute'

### ISSUE THREAD

**Issue by bioball** [webpack/webpack-dev-middleware#132]
Version 1.8.x is breaking on node v0.10, due to using `path.isAbsolute`. Here's the error message I'm getting:

```
TypeError: Object [object Object] has no method 'isAbsolute'
  at new module.exports (/mnt/jenkins/jobs/makewonder.com/jobs/master/workspace/node_modules/webpack-dev-middleware/middleware.js:59:54)
```

Suggest using some polyfill or something for this.

**Comment by SpaceK33z** [comment]
Hmm, apparently we still allow v0.10...

**Comment by bioball** [comment]
Thx!

**Comment by broveloper** [comment]
Can we push this fix to a new tag?

webpack-dev-server's package.json has webpack-dev-middleware@^1.4.0 which will install 1.8.2 (version still has this error in it)

**Comment by SpaceK33z** [comment]
@broveloper, done; `1.8.3`.
