### ISSUE TITLE
Adding Hapi To The Other Servers Section Of README

### ISSUE THREAD

**Issue by antonio-malcolm** [webpack/webpack-dev-middleware#1374]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

Hi all, it's good to meet everyone.

I noticed, on the webpack-dev-middleware README, a section for combining it with other servers. Currently, I have both the dev middleware and hot reloading middleware working with Hapi, in what I think is an interesting use case. It may be a bit complex, as-is, as an example, however, if there's interest, and no one's gotten to it yet, I think it could be simplified / adapted for the README

### Your Proposal for Changes
Adding a Hapi server configuration to the README.

The relevant configuration, for both middleware and server, can be viewed, via the Github link below. There are two files - one which digests a Webpack configuration module, modifies that module's object, to manage and track whatever is available in the dev middleware's in-memory file system, and provide useful information describing such to the client.

I imagine it's not exactly obvious why one would do this, but the project itself is it, and the project is a monorepo, and this approach, while a bit more laborious up-front, pays off in the long term.

If you think the configuration linked below is useful, I'd be happy to assist in reducing it into something more readily digestible. The core, essentials of the configuration would be much the same, methinks.

https://github.com/antonio-malcolm/interreaction/tree/master/server

Cheers,
~Antonio

**Comment by alexander-akait** [comment]
Hello, PR welcome

**Comment by antonio-malcolm** [comment]
Great, thanks!

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack-dev-middleware/issues/945, when we will ready to support it we will add docs, anyway if you want to help us - PR welcome
