### ISSUE TITLE
Incorrect stats position field in res object 

### ISSUE THREAD

**Issue by MDAkramSiddiqui** [webpack/webpack-dev-middleware#1383]
Documentation Is: ReadMe file 

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
this paragraph is mentioned in the ReadMe file to access stats but checked in code the stats field is not present inside `devMiddleware.context.stats` but in `devMiddleware.stats`
  ```
  const { devMiddleware } = res.locals.webpack;
  const outputFileSystem = devMiddleware.context.outputFileSystem;
  const jsonWebpackStats = devMiddleware.context.stats.toJson();
  const { assetsByChunkName, outputPath } = jsonWebpackStats;
 ```

### Your Proposal for Changes

Either update the code or ReadMe.
  ```
  const { devMiddleware } = res.locals.webpack;
  const outputFileSystem = devMiddleware.outputFileSystem;
  const jsonWebpackStats = devMiddleware.stats.toJson();
  const { assetsByChunkName, outputPath } = jsonWebpackStats;
 ```

**Comment by alexander-akait** [comment]
Feel free to send a fix to docs, just use `devMiddleware.context.stats`

**Comment by MDAkramSiddiqui** [comment]
This is what I am saying cannot use stats via this `devMiddleware.context.stats` as context is undefined.

**Comment by alexander-akait** [comment]
@MDAkramSiddiqui When you try to get this? Becaue it can be undefined if no builds happend

**Comment by mdakram-swiggy** [comment]
https://github.com/webpack/webpack-dev-middleware/blob/9d1edd472a20cc6fcbe76ffe634401da6238c8f7/src/middleware.js#L88
Talking about this line, `devMiddleware` is `context` itself

**Comment by MDAkramSiddiqui** [comment]
Talking about this line, `devMiddleware` is `context` itself, @alexander-akait 
https://github.com/webpack/webpack-dev-middleware/blob/9d1edd472a20cc6fcbe76ffe634401da6238c8f7/src/middleware.js#L88

**Comment by alexander-akait** [comment]
Do you have middleware after webpack-dev-middleware? Anyway can you create minimum reproducible test repo, because I can't undestand there is place where you try to get it, thank you

**Comment by alexander-akait** [comment]
Oh, I see, do you want to send a PR with fix?

**Comment by MDAkramSiddiqui** [comment]
cannot raise a PR, getting error that I don't have permission.

**Comment by alexander-akait** [comment]
You need fork firstly, then send a PR to your fork and then go to PR requests and send it

**Comment by MDAkramSiddiqui** [comment]
thanks, have raised the PR https://github.com/webpack/webpack-dev-middleware/pull/1485
