### ISSUE TITLE
webpack-dev-middleware with Node 6

### ISSUE THREAD

**Issue by kol9n93** [webpack/webpack-dev-middleware#139]
Hi. Is there some issues with Node 6?
I'm trying to use the following code, but browser tries to get bundle.js from root context.
```
let compiler = webpack(require('./../../webpack.development.config.js'));
app.use(webpackMiddleware(compiler, {
  publicPath: '/static',
  noInfo: true
}));
```
Should GET from 'http://localhost:3000/static/bundle.js', but trying to get from 'http://localhost:3000/bundle.js'.
If I change `publicPath` to `publicPath: '/'`, then It's trying to get bundle from 'http://localhost:3000/static/bundle.js', but bundle locates in 'http://localhost:3000/bundle.js'.

**Comment by SpaceK33z** [comment]
There aren't any issues with Node v6, I use it all the time.

Could you try adding a trailing slash to the `publicPath`?

**Comment by kol9n93** [comment]
`publicPath: '/static/'` Doesn't help.

**Comment by SpaceK33z** [comment]
Just tested this myself on a very simple app, but it still works (there are also tests for this). Could you show me what you `output` object looks like in your webpack config?

**Comment by kol9n93** [comment]
Yes, sure.
```
 output: {
    path: path.resolve(__dirname, 'build/client'),
    filename: 'bundle.js',
    libraryTarget: 'umd',
    hot: true
  }
```
I've changed node version from 4.3.1 to 6.7.0. And also webpack started to build two bundles (bundle.js and 1.bundle.js) with node v6.7.0. But with node v4.3.1 webpack builds only one bundle (bundle.js)

**Comment by SpaceK33z** [comment]
Do you need `libraryTarget: 'umd'`? If you remove this property, it will work (at least in my tests). Not sure yet why.

Side-note: `hot: true` has no effect so you can remove that.

**Comment by kol9n93** [comment]
Thank you. But it doesn't solve the problem. Webpack started to split my bundle on two chunks (bundle.js and 1.bundle.js) and system tries to get 1.bundle.js from http://localhost:3000/1.bundle.js, but should get from http://localhost:3000/static/1.bundle.js

**Comment by SpaceK33z** [comment]
Okay, so if I understand it correctly you're one step further now (since `/bundle.js` loads at the least)?

I think it tries to get the chunk from `static/1.bundle.js` because the `output.publicPath` is still on `/static/`. In one of my projects I had an issue like this and I set `output.publicPath` to `/` and made sure that webpack-dev-middleware is initialised with `{ publicPath: '/' }`.

**Comment by kol9n93** [comment]
Thank you for your help. I've solved that problem by setting puplicPath: '/static' to ouput property in webpack config.
