### ISSUE TITLE
Webpack compiles with "null" keys of chunks

### ISSUE THREAD

**Issue by nikitabulatov** [webpack/webpack-dev-middleware#146]
Result example:
```js
  webpackJsonp([0],{

  /***/ null:
  /***/ function(module, exports) {

  	eval("...");

  /***/ },

  /***/ 0:
  /***/ function(module, exports, __webpack_require__) {

  	__webpack_require__(null);
  	module.exports = __webpack_require__(null);


  /***/ },

  /***/ null:
  /***/ function(module, exports) {

  	eval("...");

  /***/ },
```

webpack-dev-server config:
```js
webpack = require('webpack')
WebpackDevServer = require('webpack-dev-server')
config = require('./webpack.config.coffee')
path = require('path')

server = new WebpackDevServer(webpack(config, (err) -> console.log err if err?),
  contentBase: path.resolve(__dirname, '../tmp/build')
  quiet: true
  inline: true
  stats: colors: true
  proxy: ...
```

**Comment by SpaceK33z** [comment]
webpack-dev-middleware can't change the output of the bundle, so this would belong in the webpack repo. Have you also tried if this happens when compiling with webpack?

**Comment by nikitabulatov** [comment]
@SpaceK33z If I try to compile with same config and without webpack-dev-middleware then I get valid result

**Comment by SpaceK33z** [comment]
First try this:

- Try setting `outputPath: "/"` in the options for DevServer
- Try setting `publicPath: "/"` in the options for DevServer

If nothing of that works, please show the options you have in your webpack config under `output`.

**Comment by SpaceK33z** [comment]
And another thing: does it work when using the webpack-dev-server CLI?

**Comment by nikitabulatov** [comment]
webpack-dev-server CLI works. Thank you!

**Comment by SpaceK33z** [comment]
Interesting. It was some kind of configuration issue in that case, because the CLI just uses the Node.js API with some other settings.

Closing this for now. If anyone sees this and it is happening again on **webpack v2**, please comment here.

**Comment by ganapativs** [comment]
Compilation filled with null. What to do?
<img width="234" alt="screen shot 2017-05-15 at 6 55 30 pm" src="https://cloud.githubusercontent.com/assets/4010960/26059643/201cf2d6-39a0-11e7-8cbb-7d6bce4744cd.png">
