### ISSUE TITLE
Default configuration sometimes set to lazy instead of watch

### ISSUE THREAD

**Issue by chrishtanaka** [webpack/webpack-dev-middleware#147]
Downloading the [Webpack Typescript Recipe](https://github.com/BrowserSync/recipes/tree/master/recipes/webpack.typescript) from the repo has watch mode enabled by default.

When I create a new project I must explicitly enable watch mode:
```js
webpackDevMiddleware(bundler, {
  publicPath: webpackConfig.output.publicPath,
  stats: { colors: true },
  lazy: false,
  watchOptions: {
    aggregateTimeout: 300,
    poll: true
  }
})
```

What is the default configuration supposed to be, and why are they different?

**Comment by SpaceK33z** [comment]
I don't understand your question exactly. You don't have to explicitly set `lazy: false`, if you mean that. `watchOptions.poll` is only necessary when your OS or filesystem doesn't properly support filesystem events. This can happen when you're using it in a virtual machine or if the code is mounted on a NFS volume.

**Comment by chrishtanaka** [comment]
Sorry, this is what I meant:
The Webpack Typescript Recipe uses the following configuration and rebuilds on change:
```js
middleware: [
    webpackDevMiddleware(bundler, {
        publicPath: webpackConfig.output.publicPath,
        stats: {colors: true}
    })
],
```
If I use the same configuration on a new project webpack does not rebuild on change. The only difference here is that I downloaded the webpack recipe example vs starting from scratch.

If I want to rebuild on change on a new project I have to explicitly add the watch option to my configuration:
```js
webpackDevMiddleware(bundler, {
  publicPath: webpackConfig.output.publicPath,
  stats: { colors: true },
  lazy: false,
  watchOptions: {
    aggregateTimeout: 300,
    poll: true
  }
})
```

I am not using a virtual machine, I am running the latest macOS Sierra.

**Comment by SpaceK33z** [comment]
I tested this to be sure, but you really don't have to explicitly set the `watchOptions`.
