### ISSUE TITLE
Add Koa 2 support

### ISSUE THREAD

**Issue by kellytk** [webpack/webpack-dev-middleware#148]

**Comment by axe312ger** [comment]
Nice! You should have a look o these two repos, they already try to achieve it :)
https://github.com/leecade/koa-webpack-middleware
https://github.com/shellscape/koa-webpack

**Comment by shellscape** [comment]
koa-webpack has the added bonus of shipping with webpack-hot-middleware bundled.

**Comment by pastelsky** [comment]
For anyone having trouble having using async middlewares along with other webpack dev servers, I recommended checking out [webpack-koa2-middleware](https://github.com/iyuq/webpack-koa2-middleware). Worked beautifully for us.

**Comment by shellscape** [comment]
#177 is pending and will add support for koa2 when merged

**Comment by kaelzhang** [comment]
`webpack-dev-middleware` is built to support those situations that not working with express, see [here](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L72)

So, we could simply use [`express-to-koa`](https://www.npmjs.com/package/express-to-koa)

```js
const e2k = require('express-to-koa')
app.use(e2k(devMiddleware))
```

**Comment by shellscape** [comment]
Fixed by #177

**Comment by megakoresh** [comment]
I am not sure how to use it with koa. Just plugging it in like I do native middleware gives me this every 1-2 seconds:
![Error](http://images.devs-on.net/Image/Zl9EfeAAWlkUxUpj-Region.png)

**Comment by noinkling** [comment]
@megakoresh "Support" in the title is a bit misleading, you will probably still want to use something like [koa-webpack](https://github.com/shellscape/koa-webpack).
