### ISSUE TITLE
Hot reload fails to download patch when public path is specified

### ISSUE THREAD

**Issue by kurtharriger** [webpack/webpack-dev-middleware#15]
Trying to proxy server and mount js file in expected dev build location in webpack-dev-server grunt config to intercept requests for  http://localhost:6001/slm/js/alm/builds/components/alm-components.js
...
publicPath: '/slm/js/alm/builds/components'

This works now but hot reloading is no longer able to find the update chunks at /af64be6a5c4098fd56ce.hot-update.json

but works if public path is specified: 
curl http://localhost:6001/slm/js/alm/builds/components/af64be6a5c4098fd56ce.hot-update.json
{"h":"1da04cff58307a4c0143","c":[0]}

It seems that it still needs to expect update chunks to be at root or hot reload module needs to know the public path.

**Comment by vohof** [comment]
How do you hot reload with just using this middleware?
