### ISSUE TITLE
middleware blocks on requests to non-webpack assets

### ISSUE THREAD

**Issue by bruce-c-liu** [webpack/webpack-dev-middleware#1523]
### Actual Behavior
I am currently trying to upgrade `webpack-dev-middleware` from `3.7.2` to `5.3.3`. In `3.7.2`, the middleware properly ignores requests to non-webpack assets. However, in `5.3.3`, the middleware will block until the bundle is built even when the request is for a non-webpack asset. 

### Expected Behavior
- I expect the behavior to be the same as `3.7.2` as I did not see any mention of this behavior change in the `CHANGE_LOG`. 

### How Do We Reproduce?
See discussion.

### Other notes
- This is kind of annoying as I am running tests with this middleware and I can't hit my other endpoints until the bundle finishes building (which takes 40+ seconds). Of course, the easy fix is to move this middleware to behind all those other endpoints.
- P.S I don't consider this a bug, but it is an undocumented change. Could you please let me know when this change was introduced?

**Comment by alexander-akait** [comment]
Strange, we have https://github.com/webpack/webpack-dev-middleware/blob/master/src/middleware.js#L98, maybe you have something unusual with your public path?

**Comment by bruce-c-liu** [comment]
Hmm, I tried to create a minimum repro, but I wasn't able to get the same behavior. Might be some weird combo of plugins in our project. It's not really a big deal, so I'll just close this. Thanks!

**Comment by bruce-c-liu** [comment]
Minutes after I wrote that comment, I was able to repro, haha... See the comment in `app.js` for context.

Repro steps:
- yarn
- Run `node pingServer.js` with `webpack-dev-middleware` 3.7.2 vs 5.3.3 to see the difference in how it handles a request to a non-webpack asset.


File structure:
- index.js
- pingServer.js
- package.json
- app.js

```js
// index.js

// importing mui because it takes a little while to build. That time it takes better represents a real app's webpack build.
import * as mui from 'material-ui';

console.log(mui);
```

```js
// pingServer.js

const child_process = require('child_process');
const fetch = require('node-fetch');

const child = child_process.fork('./app.js');

// keeps pinging server until it returns a response
async function pingServer() {
  while (true) {
    try {
      // GET non-webpack resource
      const res = await fetch('http://localhost:3000');
      console.log('Server started!');

      const data = await res.text();
      console.log(data.slice(0, 50));
      return;
    } catch (e) {
      console.log('Server not ready yet');

      // sleep for 100ms and ping again
      await new Promise((resolve) => {
        setTimeout(resolve, 100);
      });
    }
  }
}

process.on('SIGINT', function () {
  console.log('killed!');
  child.kill();
});

pingServer();
```

```js
// app.js

const webpack = require('webpack');
const webpackDevMiddleware = require('webpack-dev-middleware');
const express = require('express');

const app = express();

const compiler = webpack({
  mode: 'development',
  entry: './index.js',
});
app.use(
  webpackDevMiddleware(compiler, {
    publicPath: '/dist/', // <---- Notice publicPath vs the endpoint we're actually hitting!
  })
);

// On fetch('http://localhost:3000'):
// - in 3.7.2, this gets hit immediately even if bundle hasn't finished building
// - in 5.3.3, this gets hit after bundle finishes building
// Notice that we are fetching a non-webpack asset endpoint. I think
// in 3.7.2, webpack-dev-middleware may have recognized that and optimized it by
// going next() immediately? On the other hand, 5.3.3 doesn't seem to make that optimization?
app.get('/', (req, res) => {
  res.send('NON-WEBPACK ASSET ENDPOINT');
});

app.listen(3000);

```

```json
{
  "name": "repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "express": "4.17.1",
    "material-ui": "^0.20.2",
    "node-fetch": "2.6.7",
    "webpack": "4.46.0",
    "webpack-dev-middleware": "3.7.2"
  }
}

```

**Comment by alexander-akait** [comment]
I think it is due `'/dist/'` and `/` webpack is thinking it is a part of request to bundle code, maybe we should improve this, do you want to send a PR?

**Comment by bruce-c-liu** [comment]
> I think it is due `'/dist/'` and `/` webpack is thinking it is a part of request to bundle code.

Yes, I believe that is the reason as well. Seems like the behavior was optimized in `3.7.2`, but is no longer the case. 

> do you want to send a PR?
Unfortunately, I do not have the bandwidth to take that on at the moment. This is not a blocking issue for me, so feel free to prioritize whenever.

Thank you for the fast responses!

**Comment by alexander-akait** [comment]
@bruce-c-liu I checked code and I understand why it was changed, our `publucPath` can be 'auto' (i.e. based on output path and yes you can emit assets above output path using `../../[name][ext]`) and also we support dynamic function, so we can't know your assets URLs until we build a project, what is why we block requests, but it doesn't mean you can't solve it, just change:
```js
app.use( "/dist/",
  webpackDevMiddleware(compiler, {
    publicPath: '/', // <---- Notice publicPath vs the endpoint we're actually hitting!
  })
);
```

and all works correctly, I want to say it is a limitation

**Comment by alexander-akait** [comment]
Even more you can change output path and public path inside plugins, that is why we get it from stats https://github.com/webpack/webpack-dev-middleware/blob/master/src/utils/getPaths.js#L15

**Comment by alexander-akait** [comment]
And yes you can have `publicPath: "/[hash]/public/"`, and we can't calculate hash without bundling, so I think we need improve our docs and provide an example:
```js
app.use( "/dist/",
  webpackDevMiddleware(compiler, {
    publicPath: '/', // <---- Notice publicPath vs the endpoint we're actually hitting!
  })
);
```

when you want to avoid such behaviour

**Comment by alexander-akait** [comment]
Are you fine with it?

**Comment by bruce-c-liu** [comment]
Ah, that makes sense! Thank you for the explanation.

**Comment by alexander-akait** [comment]
Let's keep open I want to improve our documentation :smile: If you want you can send a PR

**Comment by alexander-akait** [comment]
Oh, looks like we have this one https://github.com/webpack/webpack-dev-middleware/issues/966, so let's close
