### ISSUE TITLE
Remove default for "index" option

### ISSUE THREAD

**Issue by cecchi** [webpack/webpack-dev-middleware#153]
Currently I have an `index.html` in my output directory, and requests to the root URL will be handled by webpack-dev-middleware as requests to `/index.html` due to this line: https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L50

I would prefer to have webpack-dev-middleware ignore the request, as I have a catch all handler to serve the index.html for all routes not exactly matching a webpack asset. Something like:

```js
app.all('*', (req, res) => {
  res.sendFile('/path/to/index.html');
  // Do some other stuff
})
```

That extra logic is lost if the `/` request is served by webpack-dev-middleware. I can get around it by renaming `index.html`, or by setting `options.index` to some nonsense or `true` but thats hacky and brittle. 

I'd prefer either removing the default `options.index` value, or adding another option to change the behavior.

**Comment by SpaceK33z** [comment]
We're not going to remove the index option, but there seems to be a small bug with it. Currently if it set to a falsy value, it will always default to `index.html`. It should only do this when it is set to `true` or is `undefined` ([see line](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L50)).

You can make a PR to fix that.

**Comment by em0ney** [comment]
As a workaround, I am making sure that my webpack compiler doesn't name it index.html when doing copy to the output path.  Then I reference this different name in my handler for '*'
