### ISSUE TITLE
Errors in async tasks cause webpack to hang

### ISSUE THREAD

**Issue by hansl** [webpack/webpack-dev-middleware#156]
I want to report a **bug**.

## What is the current behavior?
Webpack hangs indefinitely when using `webpack-dev-middleware` (directly or indirectly through `webpack-dev-server`) and there's an error in an async step.

## Steps to reproduce.
Make a plugin like this:

```typescript
class MyErrorPlugin {
  apply(compiler) {
    compiler.plugin('make', (compilation, cb) => {
      setTimeout(() => cb(new Error('Heho!')), 1);
    });
  }
}
```

Run a webpack configuration with `webpack-dev-middleware` and this plugin, and the generation will hang forever.

Note that this occurs in the Webpack plugin for Angular 2, when an application cannot be statically analyzable, since we perform that analysis . Also, if this error is not reported in the async task everything works as the expected behaviour.

The reason is the callback used when running webpack (see [here](https://github.com/webpack/webpack-dev-middleware/blob/6b49341db9c1323a1304ff99092036a72d2449a8/lib/Shared.js#L164) and [here (watch)](https://github.com/webpack/webpack-dev-middleware/blob/6b49341db9c1323a1304ff99092036a72d2449a8/lib/Shared.js#L153)) which simply `throw` instead of reporting the error and stopping the build. Because the build is not stopped by Webpack itself, webpack is waiting for the `make` step of the compiler to finish, which won't happen because the `throw` killed the task.

Not sure what the proper solution is.

# What is the expected behavior?
Show error on console, say the bundle is INVALID or something, watch for file changes, rebuild when file changes.

**Comment by SpaceK33z** [comment]
Thanks for your clear bug report. I *think* the best solution would be to simply log the error, using `options.warn` instead of `throw`.

Would you be interested in making a PR for this? I could also fix it, but it will take a bit longer before I have time.

**Comment by SpaceK33z** [comment]
Could you check if #157 fixes it for you?

**Comment by hansl** [comment]
Seems like #157 fixes the middleware part, but webpack itself is hanging. 

Running this config:

```es6
class CustomErrorPlugin {
  apply(compiler) {
    compiler.plugin('make', function(compilation, callback) {
      Promise.resolve()
        .then(() => console.log('0'))
        .then(() => callback(new Error('hello')));
    });
  }
}


module.exports = {
  resolve: {
    extensions: ['.ts', '.js']
  },
  entry: './app/main.ts',
  output: {
    path: './dist',
    filename: 'app.main.js'
  },
  plugins: [
    new CustomErrorPlugin()
  ],
  module: {
    loaders: [
      { test: /\.css$/, loader: 'raw-loader' },
      { test: /\.html$/, loader: 'raw-loader' },
      { test: /\.ts$/, loader: 'awesome-typescript-loader' }
    ]
  },
  devServer: {
    historyApiFallback: true
  }
};
```

`webpack --watch` blocks at 50% on my custom project. Still investigating, but it seems like the PR would help.

**Comment by hansl** [comment]
(not there is no middleware).

**Comment by hansl** [comment]
I'll file a bug with Webpack itself.
