### ISSUE TITLE
Bump peerDependency for latest webpack@2

### ISSUE THREAD

**Issue by glenjamin** [webpack/webpack-dev-middleware#159]
**Do you want to request a *feature* or report a *bug*?**
Bug, ish

**What is the current behavior?**
Peer Dependency warning when used with latest webpack beta version

**If the current behavior is a bug, please provide the steps to reproduce.**
```
npm install webpack@beta webpack-dev-middleware
```

**What is the expected behavior?**
No warnings

------

I would have sent a PR, but wasn't sure what version range to go for, what with the final version due soon.

**Comment by SpaceK33z** [comment]
This was fixed in `1.9.0`.
