### ISSUE TITLE
BUG: 1.9.0 npm linked modules and watch

### ISSUE THREAD

**Issue by jonashartwig** [webpack/webpack-dev-middleware#165]
Hej,

I found a rather bad issue. If I use npm link to develope a npm module using webpack and I use the dev middleware in watch mode the process dies with too many file handles.
I could isolate the issue: It seems to recursively watch the node_modules folder. (removing node_modules folder does not bring the issue) If I change lazy: true it works, but unfortunately it has lots of requests for images for example and every request rebuild the bundle.

webpack: 1.13.1
Any advice?

Regards

**Comment by SpaceK33z** [comment]
See https://webpack.js.org/configuration/watch/#watchoptions-ignored

**Comment by jonashartwig** [comment]
this is not included in webpack documentation less than 2. is that still available?

**Comment by SpaceK33z** [comment]
yes

**Comment by jonashartwig** [comment]
Ok, that works fine. Maybe this should be added to webpack 1.x docs :)

**Comment by jonashartwig** [comment]
Hi, i am facing issues again and tried to understand how this works. I dont see any reference to ignored or watch, watchOptions etc in the source code.
