### ISSUE TITLE
Bump json-joy dependency to new version due to bug fix with reserved windows file names

### ISSUE THREAD

**Issue by Gytiss** [webpack/webpack-dev-middleware#1735]
Hello,

I see that you have dependency to `https://github.com/streamich/json-joy`

The problem is that `json-joy` had a bug with creating reserved filenames on Windows and they fixed it here: https://github.com/streamich/json-joy/issues/482  

They included the fix in version `11.19.0` https://github.com/streamich/json-joy/pull/489 

But I see your latest version of `json-joy` is still `9.9.1` 

Is there a planned release with an update of bumping `json-joy` version and thus eliminating the issue of node modules not deleting on windows due to reserved file names created by `json-joy` ? (see above the issue that is fixed in their repo and the same happens with installing `webpack-dev-middleware`)

**Comment by alexander-akait** [comment]
We don't use `json-joy` directly, please ask this in `memfs`, thank you, if they fixed it - just update your deps

**Comment by qntm** [comment]
This appears to have been resolved upstream under https://github.com/streamich/memfs/issues/979 and https://github.com/streamich/memfs/issues/980. `memfs@4.7.7` no longer uses `json-joy` at all.
