### ISSUE TITLE
package.json: with webpack 2.3.3, yarn warns unmet peer

### ISSUE THREAD

**Issue by estaub** [webpack/webpack-dev-middleware#178]
`warning "webpack-dev-middleware@1.10.1" has unmet peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".`

**Comment by shellscape** [comment]
@estaub do you have webpack installed?

**Comment by estaub** [comment]
@shellscape Yes, 
```
  "name": "webpack",
  "version": "2.5.1",
```
