### ISSUE TITLE
BUG: babel-plugin-resolver breaks down webpack-dev-middleware on Mac

### ISSUE THREAD

**Issue by olegkalyta** [webpack/webpack-dev-middleware#179]
I have React app with enabled server rendering.
It uses babel to compile client code on server side for it.
Now I decided to use `resolve` to avoid `../../../../../`

So I updated **webpack.config.js** (version 2.3.3)  with 

    resolve { root: ['./src']

Also i updated **.babelrc**:

    [
      "resolver",
      {
        "resolveDirs": ["src"]
      }
    ]

And it works fine on Windows machines (tested a lot). But one of our front-end developers uses Mac. And on it Webpack HMR is not working.

For HMR we use:
`webpack-dev-middleware` (1.10.1) and `webpack-hot-middleware` (2.18.0).

On his Mac I see, that there is connection between client and server HMR.
 
But `webpack-dev-middleware`  does not discovers any changes.

**Comment by shellscape** [comment]
@olegkalyta if you can provide a repo with a sample project that illustrates this problem, with instructions on how to reproduce the problem, we can take a look at a possible solution. (Please include clear directions on how to reproduce)

**Comment by olegkalyta** [comment]
I was wrong here. There was another reason for this bug.
