### ISSUE TITLE
Address the vulnerability

### ISSUE THREAD

**Issue by sebastian-kopiczko** [webpack/webpack-dev-middleware#1793]
Hi folks! Do you plan to address or have an ETA for fixing the vulnerability reported here: [Path traversal in webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/security/advisories/GHSA-wr3j-pwj9-hqq6)

**Comment by DanielRuf** [comment]
Should be already patched:

![grafik](https://github.com/webpack/webpack-dev-middleware/assets/827205/a4a40be5-4111-4ee2-9b6e-8657fb382da3)

**Comment by alexander-akait** [comment]
Already fixed, the answer above, thank you

**Comment by rumpnizz** [comment]
I'm not sure this is properly fixed for **6.1.2**.
Looking at the [version6-middleware.js#L103](https://github.com/webpack/webpack-dev-middleware/blob/version-6/src/middleware.js#L103), `extra` isn't passed to `getFilenameFromUrl`

This compared to the other versions [version5-middleware.js#L104](https://github.com/webpack/webpack-dev-middleware/blob/version-5/src/middleware.js#L104) and [latest-middleware.js#L184](https://github.com/webpack/webpack-dev-middleware/blob/master/src/middleware.js#L184). 
Or is it handled differently in 6.1.2?

**Comment by DanielRuf** [comment]
The line that you see was added at https://github.com/webpack/webpack-dev-middleware/commit/ab533de933c6684218172b86992f35c3ca6c58a4, which is not directly related to the fix.

See https://github.com/webpack/webpack-dev-middleware/commit/9670b3495da518fe667ff3428c5e4cb9f2f3d353 for all the changes in v6 related to the fix.

**Comment by alexander-akait** [comment]
@rumpnizz yeah, good catch :+1:

**Comment by navalamol** [comment]
Hi Team, Can we get this patched in version 3 & 4 as well ? 
3.7.3 & 4.3.0 are also widely used libraries. As they are transitive dependencies which further rely on previous node versions. So possibly these are also in use.

It would be great if we can patch fix in above versions

**Comment by alexander-akait** [comment]
We use `~` eveywhere, so you can update deps locally

**Comment by navalamol** [comment]
I understand that but we are enforced to use 3.x.x & 4.x.x versions of webpack-dev-middleware due to certain limitations. 

You have provided a patch for 5.x.x, 6.x.x & 7.x.x versions.  So my request was to provide patch for 3.x.x & 4.x.x versions. Thanks

**Comment by alexander-akait** [comment]
They are outdated, anyway I can accept your PR to patch them

**Comment by DanielRuf** [comment]
I wonder if people use dev tools in production, or what justifies to patch even more versions?
Just curious because you can never have 0 vulnerabilities in your dev tools: https://overreacted.io/npm-audit-broken-by-design/

I have to deal with CVEs on a daily basis at work, and there we can and will not patch every problem, especially in dev tools. When we use CVSS v4 and EPSS as part of correct risk management, most findings often pose no real risk - unless you use dev tools on a production server.

**Comment by DanielRuf** [comment]
To quote from the linked GHSA entry:

> If the development server is listening on a public IP address (or 0.0.0.0), an attacker on the local network can access the local files without any interaction from the victim (direct connection to the port).

If
* your OS exposes all ports to the outside
* AND your router allows accessing devices from the outside via any port (port forwarding)

then you have basically two dangerous and not recommended misconfigurations, which pose even higher risks.
