### ISSUE TITLE
Feature: Fallback for unreachable file

### ISSUE THREAD

**Issue by lo-tp** [webpack/webpack-dev-middleware#180]
Imagine, we are debugging a react app with react-router. We click
a link sending us to another url. That's ok since all the routing
stuff are handled in the front end. Then we make some modification
to the html and want to refresh the whole page. Now problem arises,
the url is now unreachable in the back end because we have changed
it so that the server has no idea what file to serve.

In this case, we would like the dev server to serve one similiar
html no matter what the url is( the root html).

**Comment by shellscape** [comment]
Closed considering resolution of #181
