### ISSUE TITLE
memorize util printed out CACHE key

### ISSUE THREAD

**Issue by zenxds** [webpack/webpack-dev-middleware#1804]
### Bug report

https://github.com/webpack/webpack-dev-middleware/blob/17ed7eb03ebf7fa47e763d0f51f2b4eaa3f0f3ee/src/utils/memorize.js#L17C18-L17C23

`console.log("CACHE", key)`

Is this expected behavior, I think not

### Actual Behavior

```
CACHE /
CACHE /src_containers_home_components_Table_index_tsx.45be7021e6b9a384681a.js
CACHE /
CACHE /src_containers_home_components_Toolbar_index_tsx.24b17739d81d0c4506e0.js
CACHE /
CACHE /src_containers_home_index_tsx.b26b2f3571b079553f1f.js
CACHE /
```

### Expected Behavior

Don't log cache key

### How Do We Reproduce?

esay reproduce

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

 System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 97.06 MB / 16.00 GB
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 17.0

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-middleware/pull/1805, release will be soon
