### ISSUE TITLE
Incorrect compile failure message given failOnWarning and failOnError of eslint-loader

### ISSUE THREAD

**Issue by jcrben** [webpack/webpack-dev-middleware#182]
**UPDATE**: I think I got confused. The bug is in the message "Failed to compile". It seems to actually compile properly. 

Let me know if I'm missing some configuration detail... I might have time to try and fix this if it's actually a bug.

**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`webpack-dev-middleware` fails to compile due to eslint rules despite `eslint-loader` `failOnError` rules. I set `failOnError` to false explicitly even tho it defaults to false: https://gitlab.com/jcrben/react_redux_demo/blob/master/webpack.config.js#L34

See https://gitlab.com/jcrben/react_redux_demo for a demonstration repo. `node_modules/.bin/webpack` runs the compilation while `npm run webpack:dev` emits the message `webpack: Failed to compile.` from https://github.com/webpack/webpack-dev-middleware/blob/master/lib/Shared.js#L49.

![image](https://cloud.githubusercontent.com/assets/5614134/24987710/4b844e46-1fb6-11e7-9456-6b00d2a93b24.png)

If build it using just webpack it will compile. If I remove `eslint-loader` and compile again it works fine.

**What is the expected behavior?**

~Emit proper build despite errors~. properly notify of build success or failure

**Please mention your webpack and Operating System version.**
Running `10.11.5`. Excerpt from package.json of example demo:

    "webpack": "^2.3.3",
    "webpack-dev-server": "^2.4.2",
    "webpack-hot-middleware": "^2.18.0"

**Comment by shellscape** [comment]
@jcrben I might be missing something here (it's been a day) but I don't see webpack-dev-middleware anywhere in your demo repo (https://gitlab.com/jcrben/react_redux_demo) I see webpack-dev-**server** and webpack-**hot**-middleware, but not this module. Did you post this in the wrong repo by chance?

**Comment by jcrben** [comment]
`webpack-dev-server` uses `webpack-dev-middleware` (see https://github.com/webpack/webpack-dev-server/blob/v2.4.5/package.json#L25) - pretty sure the issue is with the middleware...

**Comment by shellscape** [comment]
I've traced this to

```js
> context.compiler.plugin("done", share.compilerDone);

> compilerDone: function(stats) {
...
context.options.reporter({
	state: true,
	stats: stats,
	options: context.options
});

> defaultReporter: function(reporterOptions) {
	var state = reporterOptions.state;
	var stats = reporterOptions.stats;
	var options = reporterOptions.options;

> var msg = "Compiled successfully.";
if(stats.hasErrors()) {
	msg = "Failed to compile.";
...
options.log("webpack: " + msg);
```

According to https://webpack.js.org/api/node/#stats-haserrors-, this is behaving correctly. The issue may lie with webpack, or the eslint loader, but I believe that webpack-dev-middleware is correct here.

**Comment by jcrben** [comment]
Yeah, I suspect it is eslint loader in that case... I'll close this and maybe poke around at eslint-loader sometime.
