### ISSUE TITLE
stats.toJson().modules[id].chunks has empty arrays when it shouldn't

### ISSUE THREAD

**Issue by faceyspacey** [webpack/webpack-dev-middleware#184]
**What is the current behavior?**
Modules in the stats always have an empty array for `chunks`:

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const compiler = webpack(clientConfig, (error, stats) => {
    // stats.toJson().modules[someId].chunks === [] 
    app.use(serverRender(stats.toJson()))
});

app.use(webpackDevMiddleware(compiler, { publicPath }))
```
 
I've tried passing every single option as true such as `chunkModules: true` to `stats.toJson(options)` and to the options passed to the middleware. The IDs of chunks the modules correspond to never show.

**What is the expected behavior?**
The expected behavior is if you're using dynamic split chunks, to see their IDs in the `chunks` array. Instead it's always empty. The stats written to disk, if you use `write-file-webpack-plugin` is correct, but in memory is not correct. I looked through the `webpack-dev-middleware` code and I couldn't find anywhere that explicitly adjusts the stats passed to the callback of `webpack` that creates the compiler above.

ALSO NOTE: If the middleware is not used, the chunks are correctly there. That's the weirdest part. There must be some hidden switch that the middleware is triggering within the compiler by the presence of some key.

**Please mention your webpack and Operating System version.**
"webpack": "^2.2.1",
OSX

**Comment by shellscape** [comment]
@faceyspacey if you can put together a demo repo which outlines the issue, and provide some clear instructions for reproducing it, we can take a look at what the cause might be. I suspect this may be specific to your particular setup.

**Comment by shellscape** [comment]
@faceyspacey this ticket is stale at 60 days and will be closed if there's no response from the community. last chance to weigh in 😅
