### ISSUE TITLE
Error `Uncaught SyntaxError: Invalid or unexpected token` since v7.1.0

### ISSUE THREAD

**Issue by wattanx** [webpack/webpack-dev-middleware#1846]
### Bug report
Error `Uncaught SyntaxError: Invalid or unexpected token` since v7.1.0.
ref: https://github.com/nuxt/nuxt/issues/26951

### Actual Behavior
`Uncaught SyntaxError: Invalid or unexpected token` is raised.

### Expected Behavior
No errors should occur.

### How Do We Reproduce?
If you check the console, you will see an error `Uncaught SyntaxError: Invalid or unexpected token`.
https://stackblitz.com/edit/github-x4yvog

Downgrading to v7.0.0 will no longer cause the error.
https://stackblitz.com/edit/github-x4yvog-bvn5jq

For reference, nuxt's webpack configuration is described in the following source code.
https://github.com/nuxt/nuxt/blob/main/packages/webpack/src/webpack.ts

Sorry for the repuroduction using the framework.
I will create a minimal reproduction with no framework.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```log
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
```

**Comment by wattanx** [comment]
Sorry, we haven't been able to reproduce it without the framework yet.
However, there was a strange phenomenon that I would like to share.

I found out when I set sourcemap to false, but I think the bundle is broken.
In the following environment, an error is output to the console.
https://stackblitz.com/edit/github-x4yvog-sfctk4

But, The following file is the actual bundle, but the error does not exist.
`.nuxt/dist/client/_nuxt/vendors-node_modules_webpack-hot-middleware_client_js_reload_true_timeout_30000_path_2F__webp-b4bdca.js`

**Comment by alexander-akait** [comment]
@wattanx I have seen this too, I think bug somewhere in nuxt (maybe custom source map plugin or something else), I can't reproduce it in pure setup, I don't know nuxt structure, so I will take a lot of time for me to undestand where is the bug

Because we don't do a lot of critical changes in 7.1.0, only perf improvements...

**Comment by wattanx** [comment]
Thank you for your comment!
I have prepared a reproduction environment without framework and I believe the problem is most likely on the nuxt (nitro) side.
https://github.com/nuxt/nuxt/issues/26951#issuecomment-2143791640
I will investigate more.

**Comment by alexander-akait** [comment]
@wattanx Feel free to ping me

**Comment by wattanx** [comment]
It turns out that the problem is caused by another library that nuxt depends on.
Thanks for your help!
