### ISSUE TITLE
Express static content and webpack-dev-middleware

### ISSUE THREAD

**Issue by davidvorona** [webpack/webpack-dev-middleware#189]
I'm not entirely sure if this is a bug or expected behavior, but I'm having issues serving static content with my Express/Webpack/React app, using the latest versions of everything.

Below is the simple configuration of my Webpack middleware in my Express devserver.

```
const compiler = webpack(webpackConfig);   // config is required above

const webpackDevMid = require("webpack-dev-middleware");
const webpackHotMid = require("webpack-hot-middleware");

app.use(webpackDevMid(compiler, {
    noInfo: true,
    publicPath: webpackConfig.output.publicPath    // "/static/"
}));

app.use(webpackHotMid(compiler));
```

I serve my root 'index.html' file like so:

```
app.get("/", (req, res) => {
    if (!req.cookies.access_token) return res.redirect("/login");
    return res.sendFile(path.join(__dirname, "index.html"));
});
```

That root index.html file then has a div with the 'root' tag which points to my 'index.js' file in the Webpack-generated bundle, which is included in the index.html in script tag as '/static/bundle.js'. This all works fine, and renders correctly.

The issue I'm having is that I need to serve up my 'favicon.ico' to my root index.html file outside of Webpack, which is usually do with:

`app.use(express.static(path.join(__dirname, "/public")));`

However, nothing I serve in this way is working. It does not show up in the Chrome dev console sources tab where it usually does. This middleware seems to be the variable that is responsible, as it's a module I haven't worked with before and this is the first time I've encountered this problem. Is webpack-dev-middleware messing with my 'express.static()' or am I missing something else entirely?

Thanks in advance.

**Comment by taicho** [comment]
I'm having the same issue... Any resolution you were able to find? Any response from the dev team?

**Comment by davidvorona** [comment]
@taicho unfortunately no, and probably because this is the type of question they expect you to ask on StackOverflow (received no responses [there](http://stackoverflow.com/questions/43667102/webpack-dev-middleware-and-static-files) either).

**Comment by shellscape** [comment]
I use this module with koa, koa-webpack, and vue.js and don't have any issues with static assets. I'm not familiar with the nuances of React (crazy, I know) so I can't speak to that directly. There's been a few commits that haven't been published yet, so it might be worth using a repo reference in package.json for this module and giving that a shot.

**Comment by Izhaki** [comment]
In your webpack file make sure you have:

```
    target: 'node',
    node: {
        __dirname: true,
    },
```
See:

- https://github.com/webpack/webpack/issues/1599
- https://github.com/webpack/docs/wiki/configuration#node

**Comment by shellscape** [comment]
@davidvorona this ticket is stale at 60 days and will be closed if there's no response from the community. last chance to weigh in 😅

**Comment by TFKED** [comment]
+1 I was also having this issue and simply had to stop using webpack-dev-middleware because it wouldn't at all work for me.

**Comment by shellscape** [comment]
@TFKED please use the reaction buttons on a post rather than replying with a +1.

closing as abandoned by the author, and citing the work-around by @Izhaki

**Comment by digiperfect-janak** [comment]
@Izhaki You are a lifesaver. For the life of me - why does webpack change the default!
