### ISSUE TITLE
[question] accessing the filesystem via dev middleware

### ISSUE THREAD

**Issue by tconroy** [webpack/webpack-dev-middleware#190]
Hey there,

I have a react + express + webpack app. The React app is rendered server-side. 

In production, I generate two stylesheets -- an AboveTheFold.css and an EverythingElse.css. The express server needs to load the AboveTheFold.css, so it can inline its contents in my page template.. something like:

```js
const aboveFoldCSS = fs.readFileSync('/static/assets/AboveFold.css', 'utf8')
// ..
function pageTemplate(css) {
  return `
    <html>
      <head>
        <style>${css}</style>
      </head>
     ....
    </html>
`
}
res.send(pageTemplate(aboveFoldCSS));
```

... however, since I'm using react/webpack/etc, I use `webpack-dev-middleware` during development.

How would I accomplish the above, when my CSS file is being stored in the memory filesystem? I can't seem  to find any way to read from it. I'm using the webpack [CSSEntryPlugin](https://www.npmjs.com/package/css-entry-webpack-plugin) to generate the stylesheets:

```js
plugins: [
    new CssEntryPlugin({
      output: { filename: '[name].css' },
    }),
]
```

is there any way to read a file from the memory history for usage like above?

**Comment by SimeonC** [comment]
I'll answer here to avoid polluting the other thread. (Caveat; I don't have access to that code I was talking about as it's at my last company so this is from memory and some quick lookups at the plugin again).
If you currently have something like: `app.use(webpackMiddleware(compiler))`.
Change this to:
```
const middleware = webpackMiddleware(compiler);
app.use(middleware)
```
Then change your example to something like:
```
const aboveFoldCSS = middleware.fs.readFileSync('/static/assets/AboveFold.css', 'utf8')
```
Reference: https://github.com/webpack/webpack-dev-middleware/blob/6b49341db9c1323a1304ff99092036a72d2449a8/middleware.js#L83

**Comment by tconroy** [comment]
hey @SimeonC -- thanks for the reply, I appreciate it!

I did try something along those lines, unfortunately it doesn't seem to work :( 

```
/<project path>/node_modules/memory-fs/lib/MemoryFileSystem.js:107
			throw new MemoryFileSystemError(errors.code.ENOENT, _path);
			^
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/<project path>/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
```

Not really sure where in the memory-fs the file should be located.. presumably what was defined in `publicPath: ''` in the devMiddleware instantiation, but doesn't seem to work here :( I'm open to other ideas of course!

**Comment by diestrin** [comment]
@tconroy not really sure about your specific case, but I think that the route you're looking for, isn't right. The devMiddleware.fileSystem is a mirror of your local fileSystem plus generated virtual files. So try looking with a value like `path.join(__dirname, './${your webpack dist value}/static/assets/AboveFold.css')` The `publicPath` value doesn't matter here.

**Comment by shellscape** [comment]
hey folks, the issues are reserved for bugs and features. citing the Issue Template;

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

Please do hit up either of those two sites. You're welcome to continue discussing here, but we're gonna close this one.

**Comment by thomashibbard** [comment]
@tconroy Did you end up solving this?
