### ISSUE TITLE
Add webpack 3 to peerDependencies

### ISSUE THREAD

**Issue by chearon** [webpack/webpack-dev-middleware#199]
Hello,

Webpack 3 was just released and I noticed this (as a dependency of `karma-webpack`) doesn't have version 3 of webpack in peerDependencies. I haven't looked at the source here, but I am at least one data point that can say it is working fine in webpack 3. The list of breaking changes was small.

If you could consider adding `|| ^3`, it'd reduce warnings for those of us who've upgraded. Thanks!
<hr>

* Operating System: macOS Sierra
* Node Version: 6
* NPM Version: 3.10.10
* webpack version: 3.0.0
* webpack-dev-middleware Version: 1.10.2

- [x] This is a **feature** request
- [ ] This is a **bug**

### Expected Behavior
Silent install

### Actual Behavior
> "webpack-dev-middleware@1.10.2" has incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".

**Comment by shellscape** [comment]
Fixed by #200
