### ISSUE TITLE
Emitting event to window

### ISSUE THREAD

**Issue by jeffling** [webpack/webpack-dev-middleware#20]
Hey, I'm wondering if we can see when there is a module update from within the app. This would allow us to 'refresh' the page within a SPA to get the latest changes. I'm imagining some event that we can watch from the `window` object.

**Comment by SpaceK33z** [comment]
Very late answer:

webpack-dev-middleware stands "above" this, in the sense that it does not even communicate with the page, it only serves page from memory.

Do you use webpack-dev-server? If so, see https://github.com/webpack/webpack-dev-server/issues/542 for more info.

**Comment by jeffling** [comment]
I think I was trying to write a hot reload angular middleware :)
