### ISSUE TITLE
webpack-dev-middleware + express.static

### ISSUE THREAD

**Issue by PavelPolyakov** [webpack/webpack-dev-middleware#203]
* Operating System:
macOS
* Node Version:
v6
* NPM Version:
v5
* webpack version:
v2
* webpack-dev-middleware Version:
latest

- [x] This is a **feature** request
- [ ] This is a **bug**

### Issue
Hi @SpaceK33z, 
I know this is not a bug, but more likely a common use case, answer for which would be helpful for the community.

This is a copy of the original [stackoverflow question](https://stackoverflow.com/questions/44736354/webpack-dev-middleware-serve-fallback-to-the-public-directory).

Project structure:

1. Webpack is building the app into the `public` folder
2. At the same time I have some static assets located there, like:
`public/assets/font-awesome-4.7.0/css/font-awesome.css`

What I want:

1. I want to run my `express` app with the `webpack-dev-middleware` for the dev purposes
2. I want that all the requests for the static assets (which are not processed by `webpack`) were served from the `public` folder

How I tried to do that:

**first attempt**

    app.use(require('webpack-dev-middleware')(compiler, {
        stats: { colors: true }
    }));

    app.use(require('webpack-hot-middleware')(compiler));
    app.use('/', feathers.static(app.get('public'))); // express.static

This works good, until you have `index.html` in the `public` folder. If you have it there - the static one would be served, **NOT** the one which is the actual version according to the `webpack-dev-middleware`.

**second attempt**

Then I thought - probably I must use `express.static` only for the production case, I removed it. Now I was not able to open `/assets/font-awesome-4.7.0/css/font-awesome.css`

**third attempt (hack which works right now)**

Finally I made it work, but I'm not satisfied with the current solution. I manually put all the `assets` directory into the `webpack` realm by extending the webpack config with this:

    new CopyWebpackPlugin([
                { from: 'public/assets/', to: 'assets' },
                { from: 'node_modules/bootstrap/dist/', to: 'vendor/bootstrap/dist' }
            ]),

however this method assumes that one need to point every static file which he wants to be served by `webpack-dev-middleware`

Any thoughts are appreciated. 

Regards,

### For Features; What is the motivation and/or use-case for the feature?

I believe this is quite common use case, as `express` + `webpack-dev-middleware` are commonly used together.

**Comment by shellscape** [comment]
Hey @PavelPolyakov, please see the header of the isssue template.

> The Issues page for this repository is not a support forum. **Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid."

I'm sorry, but we have to close this one citing that message, and that you've already opened a SO for this question verbatim. Please pursue your answer on StackOverflow. You can always join the webpack gitter as well at https://gitter.im/webpack/webpack.

**Comment by PavelPolyakov** [comment]
Hi @shellscape,

I did tried two sources you mention, with the respect to the issue template header. Unfortunately my experience shows, that asking on github is times more effective.

Thank you for your time.
