### ISSUE TITLE
Separated project output files

### ISSUE THREAD

**Issue by impulsgraw** [webpack/webpack-dev-middleware#204]
In my new project I am using a WebPack2 engine, so, to deploy it, I need to compile all the project modules to 4 output files:

 - project.effects.css //can be included onto a page by user manually
 - project.effects.js //can be included onto a page by user manually
 - project.css //primary project output
 - project.js //primary project output

The latest one (`project.js`) is actually an entry point; does contain main project files, and it is compiled by WebPack as a default output. Three other files are the vendor `js+css` or some project css.

The latter (`project.effects.css`, `project.effects.js`, `project.css`) files should be packed during WebPack parses `require()` calls, so, for example, something like

```js
require('prj-fx-loader!sass-loader!./some-vendor-style.scss');
require('prj-fx-loader!sass-loader!./some-other-vendor-style.scss');
```

(`prj-fx-loader` doesn't exist, it is actually some pseudo example) should be interpreted by WebPack as follows:

 1. Both of `.scss` files are precompiled by `sass-loader`
 2. Both of the css-compiled results should be concatenated and emitted to single output file `project.effects.css`, as far as both of the `require()` calls contain the same `prj-fx-loader` which is (in my idea) responsible for outputting to `project.effects.[ext]` file (`js` or `css` - depending on extension of requiring file)

Or, for example:

```js
require('prj-fx-loader!script-loader!./some-vendor-script.js');
require('prj-fx-loader!./some-vendor-style.css');
require('prj-loader!./project-module-style.css');
require('./project-module.js');
```

should be interpreted by WebPack as follows:

 1. `some-vendor-script.js` should be emitted to `project.effects.js` output file
 2. `some-vendor-style.css` should be emitted to `project.effects.css` output file
 3. `project-module-style.css` should be emitted to `project.css` output file
 4. `project-module.js` should be defaultly emitted to `project.js` output file

I was trying to play with `extract-text-webpack-plugin`, but all that worked was only to apply that plugin inside of `webpack.config.js` `module: {rules: [/*{}*/]}` or `module: {loader: [/*{}*/]}`. That solution *is not what I need* because the loader-rule is applied globally on some file extensions, whereas there can be two files with the same `.css` extension, and both of them should be emitted to different output files (see an example above). 

But I can't implement the `ExtractTextPlugin` inside of a custom `loader(s)` (like `prj-fx-loader` and `prj-loader` in examples above) I have tried to create for solving my problem.

**Comment by impulsgraw** [comment]
Could you, please, advice me, what is the best direction for me to think about to finally solve my problem?

**Comment by shellscape** [comment]
> The Issues page for this repository is not a support forum. **Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid." Please do not delete this template from a new issue. Please remove this header to acknowledge this message.

I'm really sorry, but please note the header above from the issue template for this project. Please use one of the other outlets for general questions.
