### ISSUE TITLE
Filesystem memory leak?

### ISSUE THREAD

**Issue by krevativ** [webpack/webpack-dev-middleware#215]
* Operating System: OSX El Capitan 10.11.6
* Node Version: 8.4.0 (Tested with >= 7.10)
* NPM Version: 5.3.0 (Cleared the npm cache and reinstalled all packages)
* webpack version: 3.5.5 (Tested with >= 3.1.0)
* webpack-dev-middleware Version: 1.12.0 (tested with >= 1.6.0)
* webpack-hot-middleware Version: 2.18.2 (tested with >= 2.10)

- [ ] This is a **bug**

Hi, I had some problems with hot reloading and was looking into the dev-middleware fileSystem to find out if *.hot-update.json was in my static folder. My webpack config has nothing special. It just serving a simple react app with dev- and hot-middlewares. I removed everything unrelated. The main part is the following:

### Code

```js
  const mfs = devMiddleWare.fileSystem;
  const file = path.join(webpackConfig.output.path, '../index.html');
  let fileContent = null;
  
  router.get('*', (req, res) => {
    devMiddleWare.waitUntilValid(() => {
      
      const files = mfs.readdirSync(path.resolve(webpackConfig.output.path));
      console.log(files); // <--- my static files

      if (!fileContent) {
        fileContent = mfs.readFileSync(file);
      }
      res.writeHeader(200, { 'Content-Type': 'text/html' });
      res.end(fileContent);
    });
  });
```

### Expected Behavior

 I was expecting to find only one file or none. 

### Actual Behavior

After the first start the output looks normal:

  [ 
    'favicons',
    '0.js',
    '1.js',
    'polyfills.js',
    'client.js',
    'dev.js',
    'manifest.json' 
  ]

Then I have changed something and refreshed the browser. The output looks like so:

  [
    'favicons',
    '0.js',
    '1.js',
    'polyfills.js',
    'client.js',
    'dev.js',
    'manifest.json',
    '6a1cf9260ed70662a712.hot-update.json',
    'd3dcf2c0cc60ed930ae8.hot-update.json',
    '3c6f042c4d257e547598.hot-update.json'
  ]

And after the second time:

  [ 
    ...
    '6a1cf9260ed70662a712.hot-update.json',
    'd3dcf2c0cc60ed930ae8.hot-update.json',
    '3c6f042c4d257e547598.hot-update.json',
    '8a51990d58d965214710.hot-update.json',
    '427167602edfc6a035e2.hot-update.json',
    '671f04e7aaeed03ac0dc.hot-update.json'
  ]

And so on. This seems to me like a memory leak. If I should provide more information, just tell me what.

**Comment by shellscape** [comment]
Thanks for taking a moment to report an issue. 

It's not an in-memory so it wouldn't be a _memory_ leak, but it's possible that webpack isn't cleaning up after itself. Did you examine the output directory and find the same files when the server was stopped? If so, that's a garbage problem.

Either way, it's behaving as it should with regard to creating files. See [this test](https://github.com/webpack/webpack-dev-middleware/blob/712040d3bb9f5e42091e497b51f716902964183a/test/Server.test.js#L70). So with that, if you'd like to report this as a bug with the webpack project (and not webpack-dev-middleware), head over to [webpack](https://github.com/webpack/webpack). You can reference [this line](https://github.com/webpack/webpack/blob/aaa6eea68f42517ac8af0f4aa454951cddfcef62/lib/WebpackOptionsDefaulter.js#L61) and [this file](https://github.com/webpack/webpack/blob/2eccb19010506b886e9057cf77f9f2817ef83fd2/lib/HotModuleReplacementPlugin.js) for possible solutions or to identify the problem.

The good news/bad news is that the issue doesn't lie with webpack-dev-middleware.

**Comment by krevativ** [comment]
Thanks for the quick reply.

I can't find this files on disk nevertheless if the server is running and after the stop. So they must be in memory? And I can't tell when this stops to grow, so it may pollute the memory. First I thought this has something to do with the hot-middleware because of *hot-update.json*, but this was not the case. And next on the list was this module.

Thanks for the hint, I will look in to the code tomorrow and than decide if I should report it as bug. Maybe it's expected behavior.
