### ISSUE TITLE
Fails to load files with slow internet connection

### ISSUE THREAD

**Issue by nschurmann** [webpack/webpack-dev-middleware#217]
* Operating System: amazon linux
* Node Version: 8.1.3
* NPM Version: 5.0.3
* webpack version: 3.5.5
* webpack-dev-middleware Version: 1.12.0

- [ ] This is a **feature** request
- [ ] This is a **bug**

```js
    browserSync.init({
      open: false,
      logFileChanges: false,
      proxy: `localhost:${config.port}`,
      ws: true,
      middleware: [
        webpackDevMiddleware(compiler, {
          noInfo: false,
          stats: {
            colors: true,
            timings: true,
            chunks: false,
          },
        }),
      ],
      port: config.browserSyncPort,
      plugins: ['bs-fullscreen-message'],
    })
```

config file
https://gist.github.com/nschurmann/8684ec7ee3f889bec3b0e38ba8f1980f

### Expected Behavior
Loads different files of the bundle
### Actual Behavior
Fails with net::ERR_CONTENT_LENGTH_MISMATCH

### For Bugs; How can we reproduce the behavior?
have a big bundle (2MB), host it on any server, have slow internet connection (something that takes more than 5 seconds to download 500kb), then will throw the error, in chrome you can check it opening the console -> network

With fast internet connection it loads correctly
<img width="906" alt="screen shot 2017-09-21 at 12 10 47 pm" src="https://user-images.githubusercontent.com/5099344/30704076-ee0a2006-9ec7-11e7-90ac-4890d0ae1c92.png">

**Comment by shellscape** [comment]
This is pretty edge-case-y, especially given that this is for use in a development environment and not production. We'd be happy to review a PR that would resolve this, however.

**Comment by shellscape** [comment]
This issue is more than 90 days without activity. Closing as stale.

**Comment by GeorgeTaveras1231** [comment]
I actually believe this is an issue that affects the development environment as it is pretty common to simulate poor connections during development to test how your app handles slow connections.

I'm currently running into this same error while trying to test the use of responsive image loading, loading larger images when the device's pixel density and bandwidth is high. This is blocking me from testing the bandwidth part 😞

**Comment by anasanzari** [comment]
@shellscape would you consider reopening this issue?

**Comment by shellscape** [comment]
@anasanzari I no longer maintain this project
