### ISSUE TITLE
Inconsistent url parsing 

### ISSUE THREAD

**Issue by eladchen** [webpack/webpack-dev-middleware#218]
* Operating System: OSX Sierra
* Node Version: 8.2.1
* NPM Version: 5.4.2
* webpack version: 3.4.1
* webpack-dev-middleware Version: 1.12.0

- [ ] This is a **feature** request
- [x] This is a **bug**

https://github.com/webpack/webpack-dev-middleware/blob/441335c8d09d78675317d986b789bb7e73311a88/lib/GetFilenameFromUrl.js#L9-L10

The above urlParse calls are inconsistent ( two more arguments ) and produce different results
for at least one case I stumbled upon.

The use case I'm talking about is when both 'publicPath' and 'url' are a string with a value of '//localhost:9090/static/client/'

With the argument above the resulting value for 'localPrefix' is

```json
{
  "protocol": null,
  "slashes": true,
  "auth": null,
  "host": "localhost:9090",
  "port": "9090",
  "hostname": "localhost",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/static/client/",
  "path": "/static/client/",
  "href": "//localhost:9090/static/client/"
}
```
And for 'urlObject'

```json
{
  "protocol": null,
  "slashes": null,
  "auth": null,
  "host": null,
  "port": null,
  "hostname": null,
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "//localhost:9090/static/client/",
  "path": "//localhost:9090/static/client/",
  "href": "//localhost:9090/static/client/"
}
```
A quick look at the two results shows that parsing isn't consistent.
This makes a false positive in the condition below

https://github.com/webpack/webpack-dev-middleware/blob/441335c8d09d78675317d986b789bb7e73311a88/lib/GetFilenameFromUrl.js#L13-L16

### Expected Behavior
urlParse invoking should be consistent ( I think )

### For Bugs; How can we reproduce the behavior?
Just set a breakpoint in the mentioned lines and call both of them with '//localhost:9090/static/client/'

**Comment by shellscape** [comment]
I took a look at this during the 2.0.0 refactor (just neglected to follow up). The behavior as-is is correct. `publicPath` isn't supposed to be a full URL, it's supposed to be a _path_ fragment :smile:. You should omit the `'//localhost:9090` bit and only pass `/static/client/`. That's the intended use. I don't think this one is a bug. If you disagree, we're going to need a repo that has a simple (emphasis on simple) example of a failing case.
