### ISSUE TITLE
historyApiFallback is not supported

### ISSUE THREAD

**Issue by adipascu** [webpack/webpack-dev-middleware#221]
* Operating System: macOS Sierra
* Node Version: 8.5.0
* NPM Version: 5.5.1
* webpack version: 3.6.0
* webpack-dev-middleware Version: 1.12.0

This is a request for a documentation change.
I have noticed that `devServer.historyApiFallback` is not being processed by `webpack-dev-middleware`, it is processed by `webpack-dev-server`.
If a user wants to use `devServer.historyApiFallback` without `webpack-dev-server` they need to add the `connect-history-api-fallback` middleware to their web server. 
This means that not all properties that reside inside `devServer` prop in the webpack config file coincide with the options passed into this middleware programmatically and might not get processed.
This should be a warning in the documentation since it's not expected.

**Comment by shellscape** [comment]
@adipascu thanks for checking in. unfortunately there's a few things awry with the issue you've created. citing the issue template:

> The Issues page for this repository is not a support forum. **Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid."

The issue template here isn't optional, and removing all or portions of it is generally frowned upon on Github. There's also no implied, direct support for historyApiFallback baked into webpack-dev-middleware. For that reason I disagree with your assessment that the documentation is lacking. Any middleware you want to use along side webpack-dev-middleware must be handled and setup manually - that's a common pattern among the many popular server modules available including express and koa.

**Comment by adipascu** [comment]
@shellscape Sorry that was a draft that was accidentally sent.
