### ISSUE TITLE
configurable final handler

### ISSUE THREAD

**Issue by smoebody** [webpack/webpack-dev-middleware#226]
Im working on an angular app which uses the so called *html5* mode which means that the requested path is not returned to the server rather than handled client-side in angular. 
however there are moments when an url is opened in a new window and the browser sends a request to the server. In this case the middleware responses 404 because the path is not found (obviously).

In expressjs this can be handled by serving e.g. `/index.html` to all requests:
```js
app.use('*', (req, res, next) => {
  res.sendFile(path.join(basePath, 'index.html'));
});
```
Unfortunately this is not working out of the box in *webpack-dev-middleware*, but imho should be easy to be integrated. 
I haven't had looked into the code right now. If you would like to support that and want me to provide a PR, just say so. If you know exactly, how to do it and its one line of code you can easily hack on your phone, i would rather let you do the trick :)
 
- [x] This is a **feature** request
- [ ] This is a **bug**

**Comment by shellscape** [comment]
>  If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid."

**Comment by smoebody** [comment]
so rude. i implemented it myself. feel free to merge  https://github.com/smoebody/webpack-dev-middleware/tree/catch-all-handler

**Comment by shellscape** [comment]
@smoebody I'm sorry you felt that was rude. however, you willfully ignored some pretty clear instructions. you'll have far more success with open source in the future reading through information provided for you, for your benefit and the benefit of the folks maintaining the projects we all enjoy for free.
