### ISSUE TITLE
Using compiled bundle with serverSideRender option

### ISSUE THREAD

**Issue by herrstucki** [webpack/webpack-dev-middleware#228]
* webpack version: 3.8.1
* webpack-dev-middleware Version: 1.12.0

- [x] This is a **feature** request

### For Features; What is the motivation and/or use-case for the feature?

Instead of just having access to `webpackStats`, I'd also like to _use_ the compiled bundle to server-render a page (e.g. for a universal React app).

I don't think that's possible right now, since the compiled modules are in memory only, thus cannot be `require`d in the subsequent middlewares.

**Comment by shellscape** [comment]
This issue is more than 90 days without activity. Closing as stale. Please reference https://github.com/webpack/webpack-dev-middleware/issues/239 for a similar discussion.
