### ISSUE TITLE
Not recompiling after file changes

### ISSUE THREAD

**Issue by mtzeka** [webpack/webpack-dev-middleware#23]
I'm using webpack-dev-middleware on my express app. Everything looks as expected when I start my app. When I'm making changes as its running, I'm not seeing assets recompile. The documentation gives the impression that it's in watch mode by default and "the compiler recompiles on file changes". Is there something obvious I'm missing? Are there other examples that use webpack-dev-middleware? (other than webpack-dev-server).

Any help is appreciated.

Setup

````
var webpack = require("webpack");
var webpackDevMiddleware = require("webpack-dev-middleware");
var webpackConfig = require('../webpack.config');
var compiler = webpack(webpackConfig);

app.use(webpackDevMiddleware(compiler));
````

Config (Note: publicPath is temporarily set to the dev publicPath).

````
var webpack = require('webpack');
var path = require('path');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {

    entry: {
        lib: ['react', 'react-router'],
        main: './app/client.js'
    },

    output: {
        path: __dirname + '/public',
        filename: '/bundle.js',
        publicPath: 'http://localhost:3000'
    },

    resolve: {
        extensions: ['', '.js', '.jsx', '.scss'],
        moduleDirectories: ['node_modules', 'bower_components']
    },

    module: {
        loaders: [
            { test: /\.(js|jsx)$/, loader: 'jsx-loader' },
            { test: /\.scss$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader!sass-loader') },
            { test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') },
            { test: /\.(png|jpg)$/, loader: 'file-loader' }
        ]
    },

    plugins: [
        new ExtractTextPlugin('global.css')
    ]
};
````

**Comment by sokra** [comment]
Not sure...

There are some small mistakes in your config, maybe fixing them fixes it...

``` js
        filename: 'bundle.js',
        publicPath: 'http://localhost:3000/'
```

**Comment by mtzeka** [comment]
Made no difference unfortunately. Confused on why I have to restart the app to see my changes...

**Comment by mtzeka** [comment]
It turns out this issue has nothing to do with webpack-dev-middleware - the VM I have to run this app in doesn't seem to work well with the compiler. If I run the app outside of the VM environment all assets compile upon changes as expected. Closing this issue.
