### ISSUE TITLE
why not support multi static pages route in devMiddleware 

### ISSUE THREAD

**Issue by wansheg** [webpack/webpack-dev-middleware#232]
I doesn't find any options to config devMiddleware to support multi page .  currently, to support mutli pages,  I have to   write code jumping new url with  "location.href = "/page2.html" ,  it is ugly in production environment, so I need change these  urls  manually  to " location.href= "/page2" 

 is there any option to support route multi  static  pages ? 

I don't expect devMiddleware have strong capability to do route for any http request . 
because I  know "dev-server" is only for  development . in addition , for other url which is not for "static" resource ,  I can use "proxyMiddleWare" 

but , for "static" url , I strongly recommend to add some config option to reduce ".html" suffix in url

**Comment by shellscape** [comment]
Closing as invalid. Please see the issue template. This is not a support forum, please use one of the options provided for you in the issue template instead.
