### ISSUE TITLE
v2 changelog

### ISSUE THREAD

**Issue by hsz** [webpack/webpack-dev-middleware#234]
`webpack-dev-middleware` in `v2` has been released but I cannot find the changelog in _Releases_.
Can anyone summarize the changes?

**Comment by shellscape** [comment]
Closing as invalid. The issue template is not optional.

**Comment by hsz** [comment]
In opposition to the change log as I see. ;)

**Comment by shellscape** [comment]
There's literally no excuse for ignoring the issue template other than laziness or plain old contempt. We put enough time into creating it to assist users and maintainers alike that we can't abide ignoring it. If a formal release hasn't been posted yet, be patient and read the commit log - thats the informal summary for every release on every github repo.
