### ISSUE TITLE
Webpack v4 alpha breaks support for multiple compilers.

### ISSUE THREAD

**Issue by phyllisstein** [webpack/webpack-dev-middleware#236]
* Operating System: macOS 10.13
* Node Version: 9.3.0
* NPM Version: 5.6.0
* webpack version: 4.0.0-alpha.1
* webpack-dev-middleware Version: 2.0.1

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code
Webpack config is a little tough to read since it's exported from `webpack-chain`, but you can see the output from `inspect` in this gist: <https://gist.github.com/phyllisstein/d58d9516ef3b360156969ddac441eb90>.

```js
// app.js

#!/usr/bin/env node

const config = require('./config/webpack/middleware')
const devMiddleware = require('webpack-dev-middleware')
const express = require('express')
const hotMiddleware = require('webpack-hot-middleware')
const hotServerMiddleware = require('webpack-hot-server-middleware')
const webpack = require('webpack')

const compiler = webpack(config)
const app = express()

app.use(
  devMiddleware(compiler, {
    hot: true,
    publicPath: '/',
    quiet: false,
    serverSideRender: true,
  }),
)

app.use(
  hotMiddleware(compiler.compilers.find(c => c.name === 'client')),
)

app.use(
  hotServerMiddleware(compiler),
)

app.listen(4444)
```

### Expected Behavior
The server in `app.js` should start and run with an array of multiple compilers exported from the Webpack configuration.

### Actual Behavior
`app.js` throws an error:

```
/Users/daniel/Repos/Ignota/ordo/packages/client/node_modules/tapable/lib/Tapable.js:63
		throw new Error(`Plugin could not be registered at '${name}'. Hook was not found.\n` +
		^

Error: Plugin could not be registered at 'watch-run'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
    at MultiCompiler.plugin (/Users/daniel/Repos/Ignota/ordo/packages/client/node_modules/tapable/lib/Tapable.js:63:9)
    at MultiCompiler.deprecated [as plugin] (internal/util.js:52:15)
    at ctx (/Users/daniel/Repos/Ignota/ordo/packages/client/node_modules/webpack-dev-middleware/lib/context.js:95:20)
    at wdm (/Users/daniel/Repos/Ignota/ordo/packages/client/node_modules/webpack-dev-middleware/index.js:43:19)
    at Object.<anonymous> (/Users/daniel/Repos/Ignota/ordo/packages/client/app.js:14:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

### For Bugs; How can we reproduce the behavior?
It seems to be reproducible with any set of multiple compilers.

---

Thanks for taking a look! I've flagged this in the Webpack repo as well, since the `plugin` invocation is supposed to be backwards-compatible: <https://github.com/webpack/webpack/issues/6064#issuecomment-350434888>.

**Comment by shellscape** [comment]
@phyllisstein thanks for checking in. I don't think this is an issue with `webpack-dev-server`, and I'm 99% sure this would happen on an older version of the module with `webpack@4` from the looks of it. This is the line that suggests it's not WDM's fault:

```
 at **MultiCompiler.deprecated** [as plugin] (internal/util.js:52:15)
```


`webpack@4` is alpha at the moment, so I think you made the right call opening an issue on the main project repo.

**Comment by phyllisstein** [comment]
Thanks! That sounds like a valid assessment to me. I'll drop another note about it in the Webpack repo and keep you posted.

**Comment by shellscape** [comment]
@phyllisstein the alpha is up to the 4th release now. has this been resolved for you?

**Comment by phyllisstein** [comment]
Yes! Sorry for not updating you, but they fixed the compatibility issues with `MultiCompiler` in alpha 3 the other day. All appears to be well now.

**Comment by shellscape** [comment]
Great to hear, thanks for checking back in.
