### ISSUE TITLE
Hot module replacement support?

### ISSUE THREAD

**Issue by grrowl** [webpack/webpack-dev-middleware#24]
I'm trying to enable hot module replacement support, but webpack-dev-middleware doen't seem to be capturing requests for `/socket.io/1/?t=1423...`, which end up falling through to regular page routing.

In my `Gruntfile.js` (it's the very first middleware):
```js
middlewares.unshift(webpackMiddleware(
  webpack(webpackConfig(['client', 'dev'])), {
    hot: true,
    noInfo: true,
    stats: { color: true }
  }));
```

Relevant parts of webpack.config.js:
```js
    entry: {
      client: [
        'webpack-dev-server/client?http://localhost:9001',
        'webpack/hot/only-dev-server',
        'client.jsx'
      ]
    },
    plugins: [
      new webpack.DefinePlugin({
        'process.env': {
          'NODE_ENV': JSON.stringify('development')
        }
      }),
      new webpack.HotModuleReplacementPlugin()
    ]
```

Is this possible to do within the middleware only?

**Comment by sokra** [comment]
The middleware only serves the app. It doesn't include hot notification stuff. So you can't use `webpack-dev-server/client` or `webpack/hot/only-dev-server` with the middleware (hence the `dev-server` in the module).

You can implement hot notification + HMR management code for your own server. (or just use the webpack-dev-server)

**Comment by grrowl** [comment]
Ah, I was under the impression this wrapped `webpack-dev-server` in some way. I decided to run a webpackDevServer alongside the middleware, seems to work well:

```js
  grunt.registerTask('hotserver:dev', function () {
    var WebpackDevServer = require('webpack-dev-server'),
        config = webpackConfig(['client', 'dev']),
        host = '0.0.0.0',
        port = 8001; // must match port in webpack config for client/dev

    new WebpackDevServer(webpack(config), {
      publicPath: config.output.publicPath,
      hot: true
    }).listen(port, host, function (err, result) {
      if (err)
        console.log(err);

      console.log('Hot server listening at '+ host +':'+ port);
    });
  });
```

Although since this appears to wrap expressjs, so I may just add my server middleware into that if possible, instead to avoid running two servers while on dev. Thanks for your help!

**Comment by pixeldrew** [comment]
I use this module https://www.npmjs.com/package/webpack-hot-middleware
