### ISSUE TITLE
Recompiling after a static file is changed

### ISSUE THREAD

**Issue by klis87** [webpack/webpack-dev-middleware#244]
Is it possible to force this middleware to recompile after a static file not imported by javascript is changed, like an image for instance? I need this for `i18n-next` locale files which are loaded by `i18next-node-fs-backend` - by node fs, not webpack import statement, and I would like my app to be automatically reloaded whenever I change my locale files.

**Comment by shellscape** [comment]
Closing as invalid. Please see the issue template.
