### ISSUE TITLE
Recompilation after a static file is changed

### ISSUE THREAD

**Issue by klis87** [webpack/webpack-dev-middleware#245]
* Operating System: Linux Manjaro
* Node Version: 9.3.0
* NPM Version: 5.6.0
* webpack version: 3.10.0
* webpack-dev-middleware Version: 2.0.1

- [x] This is a **feature** request
- [ ] This is a **bug**

### Expected Behavior
It could be great to be able to define paths for static files not included in a bundle, which changes could force bundle recompilations, like:
```js
app.use(webpackDevMiddleware(webpackCompiler, {
  publicPath: '/static/',
  staticPaths: ['locales/**/*.json']
}));
```

### Actual Behavior
I believe currently there is no way to achieve that, with `staticPaths` config or so we could define a list of additional paths, which are not imported by webpack, but we would still like to recompile the bundle. 

### For Features; What is the motivation and/or use-case for the feature?
I need this for `i18n-next` locale files which are loaded by `i18next-node-fs-backend` - by node fs, not webpack import statement, and I would like my app to be automatically reloaded whenever I change my locale files.

**Comment by shellscape** [comment]
(Please don't recreate issues that were previously closed. That's called a duplicate and generally frowned upon. Instead, edit your original invalid issue moving forward)

You can achieve this yourself by leveraging [`chokidar`](https://github.com/paulmillr/chokidar) in your bootstrap code, or by using the [`watchContentBase`](https://webpack.js.org/configuration/dev-server/#devserver-watchcontentbase) option. That option is not recursive into child directories, however.
