### ISSUE TITLE
can't resolve webpack aliases

### ISSUE THREAD

**Issue by Djelnar** [webpack/webpack-dev-middleware#246]
actual problem

* Operating System: windows 10 fall cu
* Node Version: 9.2.0
* NPM Version: 5.5.1
* webpack version: 3.10.0
* webpack-dev-middleware Version: 0.1.1

- [*] This is a **bug**

### Code
```js
resolve: {
  alias: {
    components: path.resolve(__dirname, 'src', 'components'),
    pages: path.resolve(__dirname, 'src', 'pages'),
  },
},
```

### Expected Behavior
it should work and works in regular mode and webpac-dev-server
### Actual Behavior
with webpack-dev-middleware it can't resolve aliases

**Comment by shellscape** [comment]
@Djelnar webpack-dev-middleware doesn't modify the config or the compiler (webpack). This is more likely due to a config issue (bad paths) or the environment you're running. Please report this to the main webpack project if you feel it's still an error with the module.

**Comment by ruoziyou** [comment]
I have the same problem. Have you solved it now? thank you！
