### ISSUE TITLE
`lazy: true` won't ever trigger rebuild without undocumented option "filename" set.

### ISSUE THREAD

**Issue by grrowl** [webpack/webpack-dev-middleware#25]
I have it narrowed down to [line 135 of middleware.js](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L130): 
```js
if(options.lazy && filename === pathJoin(compiler.outputPath, options.filename))
```

When the undocumented option `filename` isn't set, it will attempt to match `/Users/tom/Documents/somewebsite/dist/undefined`, fail, and the request will fall through to the next handler, regardless of the file. 

Setting `{ lazy: true, filename: "client.js" }` in the dev-middleware config allows it to handle the request, but this won't work for webpack configurations with multiple entry points.

**Comment by grrowl** [comment]
It's also worth mentioning in the readme that lazy compilation is incompatible with Hot Module Replacement (although in hindsight, it should have been moderately obvious)

**Comment by hswolff** [comment]
Ran into same issue from the dev server: https://github.com/webpack/webpack-dev-server/pull/103

**Comment by SpaceK33z** [comment]
Closing this very old issue, since it appears to have been fixed a while ago. `filename` is now a documented option, and this middleware also works if you don't define it.
