### ISSUE TITLE
CONTRIBUTING.md not found

### ISSUE THREAD

**Issue by deepakjois** [webpack/webpack-dev-middleware#252]
I was hoping to contribute a small feature, so I looked through the README. It has a link to a CONTRIBUTING.md file which no longer seems to be present. Maybe add a file, or remove the reference to it?

**Comment by ev1stensberg** [comment]
As you mentioned, it has been removed. This would be a nice first contribution. If it has been in the project earlier then it's no sweat finding the commit and adjust the docs accordingly

**Comment by deepakjois** [comment]
I don’t believe it has ever been in the project.

**Comment by ev1stensberg** [comment]
Hmm, maybe it would be good to have one. Again, a good first contribution 👌
