### ISSUE TITLE
getPaths does not work with MultiCompilers that have URLs for publicPath

### ISSUE THREAD

**Issue by mwhansen** [webpack/webpack-dev-middleware#255]
* Operating System: MacOS 10.12.6
* Node Version: 7.1.0
* NPM Version: 5.6.0
* webpack version: 3.10.0
* webpack-dev-middleware Version: 2.0.4

- [X] This is a **bug**

### Code

```js
const webpack = require('webpack');
const middleware = require('webpack-dev-middleware');
const express = require('express');

const app = express();
const compiler = webpack([{
    ...options for first compiler,
    output: {
        filename: "bundle.js",
        publicPath: "http://some.host:3000/dist/"
    },
}, {
    ...options for second compiler,
    output: {
        filename: "bundle.js",
        publicPath: "http://some.host:3000/dist2/"
    },
}]);

app.use(
  middleware(compiler, {
      publicPath: "http://some.host:3000/",
  })
);

app.listen(3000, () => console.log('Example app listening on port 3000!'));
```

### Expected Behavior

We should be able to fetch `http://some.host:3000/dist/bundle.js` and `http://some.host:3000/dist2/bundle.js`.

### Actual Behavior

In `getPaths` in `utils.js`, it checks for `url.indexOf(compilerPublicPath) === 0` which won't be true if `compilerPublicPath` has a schema/host since `url` will always start with `/`.

### For Bugs; How can we reproduce the behavior?

Try to use a `MultiCompiler` where each of the compilers has a `output.publicPath` that contains a schema/host.  A proposed solution would be to parse `compilerPublicPath` in these cases and just use the `pathname` along the lines of https://github.com/mwhansen/webpack-dev-middleware/commit/01b5eb94e5d8103c77403cd36c4e737184b12b35

**Comment by shellscape** [comment]
Thanks for reporting the issue. We'd be happy to review a PR that attempts a fix.

**Comment by mwhansen** [comment]
@shellscape I added a pull request for this issue.

**Comment by ev1stensberg** [comment]
@mwhansen Could you sign the CLA?
