### ISSUE TITLE
Crash when server config (server/client multi config) does not contain config.output.publicPath.

### ISSUE THREAD

**Issue by threehams** [webpack/webpack-dev-middleware#258]
* Operating System: Windows 10
* Node Version: 9.2.0
* NPM Version: 5.5.1
* webpack version: 3.10.0
* webpack-dev-middleware Version: 2.0.5

- [ ] This is a **feature** request
- [X] This is a **bug**

### Code

A boilerplate project which reproduces this bug is at: https://github.com/faceyspacey/universal-demo
(after upgrading webpack + webpack-dev-middleware to latest)

```js
// client config
  output: {
    filename: "[name].js",
    chunkFilename: "[name].js",
    path: path.resolve(__dirname, "../buildClient"),
    publicPath: "/static/",
  },

// server config
  output: {
    path: output,
    filename: "[name].js",
    libraryTarget: "commonjs2",
  },
```

### Expected Behavior
Previously, the client config has been the first ([client, server]) so the client config publicPath was chosen. I'm not familiar with multi-compiler configurations beyond the use of webpack-hot-server-middleware, so I'm not sure what would be expected beyond this case.

### Actual Behavior
Server crashes:
```js
TypeError: Cannot read property 'indexOf' of undefined
    at getPaths (/mnt/c/Users/threehams/workspace/univ-demo/node_modules/webpack-dev-middleware/lib/util.js:27:30)
    at getFilenameFromUrl (/mnt/c/Users/threehams/workspace/univ-demo/node_modules/webpack-dev-middleware/lib/util.js:60:40)
    at middleware (/mnt/c/Users/threehams/workspace/univ-demo/node_modules/webpack-dev-middleware/lib/middleware.js:26:20)
...
```

### For Bugs; How can we reproduce the behavior?
* Clone https://github.com/faceyspacey/universal-demo
* Update webpack to 3.10.0, webpack-dev-middleware to 2.0.5
* `npm start`
* Visit localhost:3000 (crash occurs at runtime)

**Comment by shellscape** [comment]
@threehams I added a new test locally for the following config:

```js
module.exports = [{
  context: __dirname,
  entry: './foo.js',
  output: {
    filename: '[name].js',
    chunkFilename: '[name].js',
    path: '/client',
    publicPath: '/client/'
  }
}, {
  context: __dirname,
  entry: './bar.js',
  output: {
    filename: 'bar.js',
    path: '/server'
  }
}];
```

And the test passed. So I'm not sure what that repo is doing, but we're going to need a much smaller and far less complicated repo (least amount of code possible to reproduce) to work from to resolve this on our end.

**Comment by threehams** [comment]
It happens either when publicPath does not match output path, or when accessing a URL outside of publicPath. PR: #259
