### ISSUE TITLE
Requests with only query are not forwarded to proxy

### ISSUE THREAD

**Issue by CircleCode** [webpack/webpack-dev-middleware#260]
* Operating System: linux (arch)
* Node Version: v9.5.0
* NPM Version: yarn v1.3.2
* webpack version: 3.10.0
* webpack-dev-middleware Version: 1.12.2

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```js
//…
devServer: {
                    clientLogLevel: 'warning',
                    historyApiFallback: false,
                    //historyApiFallback: {
                    //    rewrites: [
                    //        {from: /.*/, to: path.posix.join(config.dev.assetsPublicPath, 'index.html')},
                    //    ],
                    //},
                    hot: true,
                    contentBase: false, // since we use CopyWebpackPlugin.
                    //compress: true,
                    compress: false,
                    host: HOST || config.dev.host,
                    port: PORT || config.dev.port,
                    open: config.dev.autoOpenBrowser,
                    overlay: config.dev.errorOverlay
                        ? {warnings: false, errors: true}
                        : false,
                    publicPath: /,
                    proxy: config.dev.proxyTable,
                    quiet: false, // necessary for FriendlyErrorsPlugin
                    watchOptions: {
                        poll: config.dev.poll,
                    }
                }
//…
```
my proxy use the following context:
```js
            context: function (pathname, req) {
                console.log(req.url, req.query);
                return pathname.match('^/(api|css|lib|images|[A-Z][A-Z_]+)')
                    || pathname.match('^/.+\\.php$')
                    || req.query.app;
            },
```

### Expected Behavior

When the browser requests `?app=my_app`, the request is forwarded to proxyfied server

### Actual Behavior

the proxy answers with index.html page

This seems to be related to `getFilenameFromUrl` finding a match to publicpath directory.

**Comment by shellscape** [comment]
Thanks for checking in. If you can create a failing test case which _does not_ rely on webpack-dev-server, then we can take a look what could be causing this. But this looks like a conflict between webpack-dev-server, http-proxy-middleware, and this module.

**Comment by CircleCode** [comment]
Here is a minimal reproduction case:

package.json:
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "express": "^4.16.2",
    "html-webpack-plugin": "^2.30.1",
    "webpack": "^3.11.0",
    "webpack-dev-middleware": "^2.0.5"
  }
}
```
test.js
```js
const webpack = require('webpack');
const middleware = require('webpack-dev-middleware');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const compiler = webpack({
    entry: './app.js',
    output: {
        filename: 'bundle.js'
    },
    plugins: [new HtmlWebpackPlugin()]
});
const express = require('express');
const app = express();

app.use(middleware(compiler, {
    publicPath: '/'
}));

app.get('*', (req, res, next) => {
    console.log(req.url, req.query);
});

app.listen(3000, () => console.log('Example app listening on port 3000!'))
```

running `curl 'localhost:3000/foo?foo=bar'` logs `/foo?foo=bar { foo: 'bar' }`
running `curl 'localhost:3000/?foo=bar' does not logs anything, and the html page is served

In the case where I want to then proxify this last request, I have no chance to do it because webpack-dev-middleware never pass the query to next handlers.

**Comment by shellscape** [comment]
That behavior is actually by design. If the path matches a webpack asset, dev-middleware handles the request and that's that. You'd have to place your proxy middleware before dev-middleware to make the right intercepts.

**Comment by CircleCode** [comment]
okay, so for my usage, I would have to implement manually the proxy in the `before` option of _webpack-dev-server_

**Comment by shellscape** [comment]
Or use the `features` option (which I'm not sure if it's documented) to rearrange the ordering of middleware in webpack-dev-server. Though if you don't need legacy browser support [webpack-serve is much easier to work with](https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/proxy.config.js) when customizing this kind of thing.

**Comment by CircleCode** [comment]
thanks for the tips, and sorry for the false bug report then

**Comment by shellscape** [comment]
No worries. We can keep this open until you can confirm a working solution if you like. If you'd like you can also close the issue.

**Comment by CircleCode** [comment]
for now, I have a workaround by using `index.php?foo=bar` instead of only `.foo=bar` which is enough.
I will probably later migrate to webpack-serve (if I understand correctly, since webpack-dev-server is in maintenance only, it will be replaced by webpack-serve?)

**Comment by shellscape** [comment]
More of a forward motion alternative rather than a replacement.

**Comment by CircleCode** [comment]
okay, thanks a lot for the explanations 👍
