### ISSUE TITLE
Add option for case insensitive requests

### ISSUE THREAD

**Issue by wbern** [webpack/webpack-dev-middleware#262]
After checking stackoverflow (including posting my own question here: https://stackoverflow.com/questions/48516063/how-do-i-make-webpack-dev-middleware-case-insensitive-for-my-assets), I was led to believe that this package does not support case insensitive asset paths, likely due to the inherent nature of nodejs projects being case-sensitive.

We have a aspnet core-powered back-end in a larger project that takes asset paths and treats them without case sensitivity. For us to speed up the workflow, we'd like to introduce webpack-dev-middleware, but since this middleware is case-sensitive, we are unable to utilize it.

I would like to make a feature request for an option to have case insensitive path matching to the assets that webpack builds. I know this is not really a common case in the nodejs world, but for our dotnet back-end it would be immensely useful to have this, as we have a lot of places that would require refactorings if we had to start caring about case sensitivity.

Thanks for any tips, work-arounds or feedback on the feature request in advance.

**Comment by shellscape** [comment]
From the issue template that was deleted:

> ...Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid." **Please do not delete this template from a new issue.** Please remove this header to acknowledge this message.

You have made the 🐼 sad
