### ISSUE TITLE
Release v1.13 with webpack v4 listed as peedDependency

### ISSUE THREAD

**Issue by mikegreiling** [webpack/webpack-dev-middleware#263]
* Operating System: macOS 10.13.3
* Node Version: v9.5.0
* NPM Version: v5.6.0
* webpack version: 4.0.0
* webpack-dev-middleware Version: 1.12.1

- [x] This is a **feature** request
- [ ] This is a **bug**

### Code

The latest 1.x release (v1.12.2) will raise warnings when installed alongside webpack v4

https://github.com/webpack/webpack-dev-middleware/blob/v1.12.2/package.json#L7

```
  "peerDependencies": {
    "webpack": "^1.0.0 || ^2.0.0 || ^3.0.0"
  },
```

### Expected Behavior

Since webpack-dev-middleware v1.12.2 appears to be compatible with webpack v4.0.0, and since several webpack plugins still have not been updated to use webpack-dev-middleware v2.x, I think it would be beneficial to release **v1.13.0** which adds `^4.0.0` to the `peerDependencies`.

### Actual Behavior

When a project updates to webpack v4 and another dependency relies on webpack-dev-middleware ^1.12.0 as a sub-dependency, warnings will be thrown by most package managers and `yarn check` will fail with an error like so:

```
error "karma-webpack#webpack-dev-middleware#webpack@^1.0.0 || ^2.0.0 || ^3.0.0" doesn't satisfy found match of "webpack@4.0.0"
```

### For Bugs; How can we reproduce the behavior?

N/A

### For Features; What is the motivation and/or use-case for the feature?

I realize the best long-term goal is to nudge webpack libraries to update their webpack-dev-middleware dependencies, but for now, releasing a minor version bump for those stuck with v1.x would be a big benefit.

In my company's workflow CI will not pass if `yarn check` throws errors, so our peerDependencies have to match.  Since `karma-webpack` is still using v1.12.x, it is holding us back from upgrading to webpack v4 🙁

**Comment by mikegreiling** [comment]
Related discussion in the karma-webpack library:
https://github.com/webpack-contrib/karma-webpack/pull/301#issuecomment-368336255

**Comment by mikegreiling** [comment]
I'd open a PR for this, but it doesn't look like there is a v1.x branch I can target.

The process would be simple though:

1. create a branch off of tag `v1.12.2` called something like `v1-stable`
2. bump the version to `v1.13.0`
3. add `|| ^4.0.0` to the webpack `peerDependency`
4. tag and publish the new version 😄

**Comment by shellscape** [comment]
This sounds entirely reasonable to me. It may take me more than today to get to, but I'll get a branch up for 1.x maintenance as soon as I'm able to.

**Comment by shellscape** [comment]
found a spare moment and created the `v1-stable` branch. please do submit a PR against that branch. the old v1 tests will have to pass against webpack v4 so please be sure to run those tests with that installed.

**Comment by mikegreiling** [comment]
I've created #265 to address this.  Thanks @shellscape!
