### ISSUE TITLE
can't find webpack-dev-middleware v3.1.0 in npm

### ISSUE THREAD

**Issue by zwlzwt** [webpack/webpack-dev-middleware#277]
npm ERR! notarget No matching version found for webpack-dev-middleware@3.1.0

* Operating System: MacOs
* Node Version:v9.6.1
* NPM Version:  5.6.0
* webpack Version: 4.1.0
* webpack-dev-middleware Version: 3.0.0

I couldn't find v3.1.0 in match info

only this vesions: 
     '2.0.1': '2017-12-14T04:00:45.323Z',
     '2.0.2': '2017-12-18T17:31:26.678Z',
     '2.0.3': '2017-12-22T21:37:39.355Z',
     '2.0.4': '2018-01-07T06:09:20.901Z',
     '2.0.5': '2018-02-09T13:43:43.695Z',
     '2.0.6': '2018-02-22T19:35:23.842Z',
     '3.0.0': '2018-02-28T22:31:03.972Z' }

**Comment by shellscape** [comment]
Closing as invalid since the issue template was removed
