### ISSUE TITLE
Should support HEAD request as well

### ISSUE THREAD

**Issue by javenwang** [webpack/webpack-dev-middleware#279]
https://github.com/webpack/webpack-dev-middleware/blob/843686b8940612f055632f785cfd8f15e51918db/lib/middleware.js#L23-L25

**Comment by ev1stensberg** [comment]
Could you elaborate a bit more in depth about this, maybe the problem you are trying to solve as well as how you'd think it should look like?

**Comment by shellscape** [comment]
Closing as invalid, since the issue template was removed.

**Comment by michaek** [comment]
It seems to me the original reporter is saying that HEAD requests should be handled as GET requests, just adding a `req.method !== 'HEAD'` to the conditional. It seems to me this wouldn't be harmful, but it may be nice to respond with empty content for a HEAD request. Currently I'm putting a another middleware in front of this to handle HEAD requests.
