### ISSUE TITLE
Giving access to files outside of contentBase:...

### ISSUE THREAD

**Issue by dannymk** [webpack/webpack-dev-middleware#28]
after a great start:
yo react-webpack
yo react-webpack:component foo
grunt serve...

How do I allow access to the node_modules or bower_components directory in the index.html file?

My current solution was to use a grunt task to copy the files from the ./node_modules/... directory to the src/styles/vendor/... directory.
...
copy: {
dev: {
files: [
{
src: [__dirname + '/node_modules/bootstrap/dist/css/bootstrap.min.css' ],
dest: '<%= pkg.src %>/styles/vendor/bootstrap.min.css'
}
]
},
...

For development purposes I would rather have something like:

...index.html
&lt;link href="/node_modules/bootstrap/dist/css/bootstrap.min.css" media="all" rel="stylesheet" /&gt;

**Comment by grrowl** [comment]
You should be using `require()` or `@import "";` to fetch module styles from your modules directories. At its simplest, you add `{ test: /\.css$/, loaders: ['css'] }` to your webpack config, then any `@import` statements are rewritten as `require()`

e.g. `@import "bootstrap/dist/css/bootstrap.min.css"` imports that css file inline into your css file. If you add `style-loader` to the leftmost of `loaders:` it'll embed it in the page too, when you `require('mystyles.css')` in your regular JS code.

It's a little crazy, but once it works you'll see the light.

**Comment by dannymk** [comment]
I actually used it this way.  I was just wondering if including other main styles and libraries would always have to be included this way or if I could simply place them all on the main page.  The file size of the final "production" ready script will obviously grow with each included style/script/lib instead of using the cdn one.  I think I have my answer, thank you for your help.

**Comment by ctindel** [comment]
@grrowl How would you do this if you're trying to use typescript where the require() functions aren't working?

**Comment by grrowl** [comment]
@ctindel I haven't used Typescript and I can only assume you use ES6 modules' `import` everywhere? Anyway, use `css-loader`, it won't use Typescript and Webpack will look for the `require(...)` string in the CSS anyway;

These days I use `sass`, which uses Webpack's module resolution rules (so you use `@import "~somelib/file"` instead)
