### ISSUE TITLE
context.compiler.hooks.invalid.tap('WebpackDevMiddleware', invalid);

### ISSUE THREAD

**Issue by yezidd** [webpack/webpack-dev-middleware#283]
TypeError: Cannot read property 'invalid' of undefined
new problem in 3.x,previous in 2.x no problem

**Comment by PandaCodes** [comment]
Same thing. My stack trace:
`TypeError: Cannot read property 'invalid' of undefined
     at ctx (/app/node_modules/webpack-dev-middleware/lib/context.js:95:26)
     at wdm (/app/node_modules/webpack-dev-middleware/index.js:44:19)
     at Object.<anonymous> (/app/server/index.js:30:44)
     at Module._compile (module.js:635:30)
     at Object.Module._extensions..js (module.js:646:10)
     at Module.load (module.js:554:32)
     at tryModuleLoad (module.js:497:12)
     at Function.Module._load (module.js:489:3)
     at Function.Module.runMain (module.js:676:10)
     at startup (bootstrap_node.js:187:16)
     at bootstrap_node.js:608:3
`

**Comment by ooflorent** [comment]
`webpack-dev-middleware@3` requires `webpack@4`.

If the problem persists, please open a new issue.

**Comment by ooflorent** [comment]
@younth no. The newest version requires webpack 4

**Comment by shellscape** [comment]
Release notes and `peerDependencies` outline clearly that webpack@4.x.x is required.

**Comment by TuKun33** [comment]
i am use 'koa-webpack-middleware' to replace , then is working

**Comment by ajaymathur** [comment]
Hi, I am using `"webpack-dev-server": "^2.11.1"` and `"webpack": "^3.10.0",` but still get this issue. 🤔

**Comment by shellscape** [comment]
@ajaymathur just glossed right over the comment on March 30th there didn't ya 🤔

**Comment by ajaymathur** [comment]
I am using v2.11.1 for webpack-dev-server therefore, webpack v4 is not required. In my node_modules I see `"webpack": "^2.2.0 || ^3.0.0"` as peerDependency for webpack-dev-server. 

If there is no instant fix lets ignore this, as I am using old version and I should rather concentrate on upgrading to latest versions. 🙂

**Comment by ajaymathur** [comment]
@shellscape Sorry, I take back what I said. I looked at depndency of webpack-dev-server instead of middleware.
