### ISSUE TITLE
%20 in directory name breaks path validation in middleware.js

### ISSUE THREAD

**Issue by wbern** [webpack/webpack-dev-middleware#284]
* Operating System: Windows 10 x64
* Node Version: 8.1.2
* NPM Version: 5.0.3
* webpack version: 3.11.x
* webpack-dev-middleware Version: 2.0.2

- [ ] This is a **feature** request
- [X] This is a **bug**

### Code

Directly related to PR #201
If you have %20 in any directory name leading up to your webpack build, it will be interpreted as " ", which is incorrect.

actual path: `C:\My%20Path\wwwroot\...`
middleware.js
```
let filename = getFilenameFromUrl(context.options.publicPath, context.compiler, req.url);
```
returns: `C:\My Path\wwwroot\...`

### Expected Behavior
should return `C:\My%20Path\wwwroot`

### Actual Behavior
returns: `C:\My Path\wwwroot\...`

### For Bugs; How can we reproduce the behavior?
Just make an output path with %20 in any directory name.

### For Features; What is the motivation and/or use-case for the feature?
Our repo has %20 in it, it is hard to change it...

**Comment by wbern** [comment]
Here is a work-around that may work for most people stumbling into this issue. I'm basically creating a mutable reference (alias if you will) in the memoryfilesystem object.

```
const middlewareInstance = webpackDevMiddleware(webpackCompiler, {
    publicPath: config.output.publicPath
});

middlewareInstance.waitUntilValid((/* stats*/) => {
    const recurse = (pathObj) => {
        Object.keys(pathObj).forEach(key => {
            if (typeof pathObj[key] === "object") {
                // it's a path object
                if (key.indexOf("%20") !== -1) {
                    // there are %20 signs. make aliases to support real spaces too
                    // optionally, we could keep recursing down if we know there are more dirs
                    pathObj[key.replace(/%20/g, " ")] = pathObj[key];
                } else {
                    // no %20 signs, keep recursing until we find it
                    recurse(pathObj[key]);
                }
            }
        })
    }
    recurse(middlewareInstance.context.fs.data);
});

app.use(config.output.publicPath, middlewareInstance);
```

**Comment by shellscape** [comment]
Thanks for the issue 🍺 

This is kinda edge-casey, but I can see how it'd be pretty inconvenient. We'd welcome a fix PR, or we can leave it as-is with the workaround you've posted for folks.

**Comment by shellscape** [comment]
@wbern I have a fix in progress, but I need to see what your webpack config looks like.
