### ISSUE TITLE
Optionally Write Files to Disk

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack-dev-middleware#286]
> The Issues page for this repository is not a support forum. **Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid." Please do not delete this template from a new issue. Please remove this header to acknowledge this message.

* Operating System: Mac High Sierra
* Node Version: 9.6
* NPM Version: 5.4
* webpack version: 4.1.0
* webpack-dev-middleware Version: latest

- [x] This is a **feature** request
- [ ] This is a **bug**

### Code

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### For Bugs; How can we reproduce the behavior?

N/A

### For Features; What is the motivation and/or use-case for the feature?

https://github.com/webpack-contrib/webpack-serve/issues/71 requests the ability for the module to support the [`WriteFilePlugin`](https://github.com/gajus/write-file-webpack-plugin) - which writes the bundle/built files to disk (as WDM only writes them to a MemoryFileSystem). There's little reason that `webpack-dev-middleware` shouldn't have an option to do this for the user as an option.

**Comment by evilebottnawi** [comment]
:+1: Will be great! In some projects we need write `assets-manifest.json` to disk, because we use backend for importing scripts/styles/images/etc

**Comment by shellscape** [comment]
@evilebottnawi I'm not planning on making any special considerations for the output, it'll just basically act as dual-output. if the config specifies it, it'll end up on disk. So that may be something you'll have to specify in the config.

**Comment by evilebottnawi** [comment]
@shellscape I can do PR, where to start looking better (options name, maybe notes about implementation and etc)?

**Comment by shellscape** [comment]
Already working on it in the `dual-output` branch :)
