### ISSUE TITLE
parent directories with spaces don't seem to be supported

### ISSUE THREAD

**Issue by Gander7** [webpack/webpack-dev-middleware#297]
* Operating System: Windows 10 Home v1709 Build 16299.371
* Node Version: 9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.4.0
* webpack-dev-middleware Version: 3.1.2

- [ ] This is a **feature** request
- [x] This is a **bug**

Duplicate issue from webpack-dev-server and webpack-server, difference is that having a space in the directory path with webpack-serve gives a `Not Found`  instead of a directory listing.

Information and problem details found (specific to webpack-dev-server, but same issue) [here](https://stackoverflow.com/questions/49763540/webpack-webpack-dev-server-react-shows-directory-listing-when-it-should-show-app)

Found this from tracking down this [Webpack-dev-server issue](https://github.com/webpack/webpack-dev-server/issues/1375) and then this [webpack-serve issue](https://github.com/webpack-contrib/webpack-serve/issues/100)

Was redirected to `webpack-dev-middleware` from `webpack-serve` issue

### Code

Not my code, but a simple starter repo I've used for testing:
https://github.com/bradtraversy/react_webpack_starter

### Expected Behavior
Bundled app runs, works on project when there are no spaces in absolute directory path.

### Actual Behavior
When there are spaces in the absolute directory path: 

- Shows `Not Found` on projects using webpack-serve
- Shows directory listing on projects using webpack-dev-server 

See github issue for more information, that issue is specific to webpack-dev-server.

### For Bugs; How can we reproduce the behavior?
For webpack-serve, see [here](https://github.com/webpack-contrib/webpack-serve/issues/100)
For webpack-dev-server, see [here](https://github.com/webpack/webpack-dev-server/issues/1375)

**Comment by stephenmartindale** [comment]
I can confirm this behaviour, although I am not using `webpack-serve` or `webpack-dev-server` but using `webpack-dev-middleware` directly, with `express`.

It also appears to be a regression. My script that runs `express` works out of a path that would have included spaces when using `webpack-dev-middleware` v.3.0.1 but serves 404's in place of the webpack output when using v.3.1.2. However, if I move my working copy to a path that does not contain spaces, both version of `webpack-dev-middleware` serve webpack's output.

**Comment by shellscape** [comment]
We'd happily review a PR to resolve this.

**Comment by shellscape** [comment]
> We'd happily review a PR to resolve this.
