### ISSUE TITLE
Rebuilding every page load with lazy: true

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [webpack/webpack-dev-middleware#298]
> The Issues page for this repository is not a support forum. **Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid." Please do not delete this template from a new issue. Please remove this header to acknowledge this message.

* Operating System: macOS latest
* Node Version: 8.10.x
* NPM Version: 5.7.x
* webpack version: 4.5.0
* webpack-dev-middleware Version: 3.1.2

- [ ] This is a **feature** request
- [x] This is a **bug**

### Expected Behavior

If no files have changed since the last page load, I do not expect the bundle to be rebuilt. It should just serve the current built JS from memory.

### Actual Behavior

The bundle is rebuilt every page load.

### For Bugs; How can we reproduce the behavior?

Make a project using webpack-dev-middleware, using the "lazy" feature.

**Comment by shellscape** [comment]
Bummer. But since you haven't provided any code, gists, or simple repos that we can use to triage, there's not much we can do to help you. As always, we'll happily review a PR.

**Comment by evan-scott-zocdoc** [comment]
I think it’s the way the feature is designed? Not quite a bug, not quite a feature request. More like a behavior change request :-)

But yeah happy to roll up a PR!

**Comment by michael-ciniawsky** [comment]
This is the intended behavior, `lazy` triggers a rebuild on each *request* despite the fact if files changed or not as it ignores watching them
