### ISSUE TITLE
Options to exclude files

### ISSUE THREAD

**Issue by meaku** [webpack/webpack-dev-middleware#3]
Hey @sokra! 

I just had some troubles on osx and the max. file watcher limit. 
Is it possible to exclude certain folders via options? 

Excluding node_modules would probably solve my problems.

**Comment by christophercliff** [comment]
I moved this plugin to npm: https://www.npmjs.com/package/watch-ignore-webpack-plugin

**Comment by sokra** [comment]
@christophercliff cool... Could you add it to this list? http://webpack.github.io/docs/list-of-plugins.html
