### ISSUE TITLE
dev logLevel showing warnings when 'error' is used

### ISSUE THREAD

**Issue by SeanHub** [webpack/webpack-dev-middleware#300]
* Operating System: Windows 10
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack version: 4.6.0
* webpack-dev-middleware Version: 3.1.2

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

serve: {
        dev: {
            logLevel: 'error'
        },
        hot: false,
        open: true,
        port: 8080
    },

### Expected Behavior
I would expect only errors to appear in the console.

### Actual Behavior
Warnings and build output is also appearing along with the errors.

### For Bugs; How can we reproduce the behavior?
Force an error in TypeScript.

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if more infomation is provided :)
