### ISSUE TITLE
Logging Messages

### ISSUE THREAD

**Issue by nikwen** [webpack/webpack-dev-middleware#302]
* Operating System: Fedora 27
* Node Version: v8.11.1
* NPM Version: 5.8.0
* webpack version: 4.5.0
* webpack-dev-middleware Version: 3.1.2

- [ ] This is a **feature** request
- [ ] This is a **bug**
- [x] This is **neither**

### Code

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```
const serveStatic = require('serve-static')
const webpack = require('webpack')
const webpackDevMiddleware = require('webpack-dev-middleware')

const config = {
    output: {
        publicPath: '/js/',
        // ...
    },
    // ...
}

app.use(webpackDevMiddleware(webpack(config), {
    publicPath: config.output.publicPath
}))

app.use('/js/', serveStatic(path.join(__dirname, 'js')))
// This contains some JavaScript files that should be (and are) served as is,
// without being touched by webpack at all, i.e. no entry point includes
// them in any way, not even via an import/require call
```

### Actual Behavior

**NOTE: I swapped the Actual and Expected Behaviour sections for easier understanding.**

When requesting the statically served files directly after launching the app while our bundle is still being built, wdm prints something like this to the logs:

```
ℹ ｢wdm｣: wait until bundle finished: /js/jquery.3.2.1.min.js
ℹ ｢wdm｣: wait until bundle finished: /js/jquery-ui.min.js
```

I believe that these messages are confusing, as I understood them as: "wdm is waiting until it has finished building the bundles /js/jquery.3.2.1.min.js and /js/jquery-ui.min.js, respectively."

However, what really happens is: wdm holds back these requests until it has finished building the actual bundles at /js/.

I spent a lot of time today trying to debug why wdm was building a bundle at /js/jquery.3.2.1.min.js when in fact it wasn't.

### Expected Behavior

The log message should make it clear that /js/jquery.3.2.1.min.js and /js/jquery-ui.min.js are *not necessarily* bundles being built by wdm.

It could print something along the lines of: "Holding back request to /js/jquery.3.2.1.min.js until bundle xyz.js has been built." or "… until all bundles have been built."

### For Features; What is the motivation and/or use-case for the feature?

See above.

**Comment by shellscape** [comment]
Thanks for the issue :beer:

I agree. We have some legacy messages that weren't exactly verbose to the point of being helpful. Some of them are hanging around and could be cleaned up. I'd be happy to review a PR for some different verbiage here. Perhaps something along the lines of "Build in progress. Please wait to request  <file> until build is complete."

_(If no PR for this has been opened later this week, I'll get the change in.)_

**Comment by nikwen** [comment]
Thank you for your quick reply! I'll be glad if this issue helps even a single other person. :)

**Comment by evilebottnawi** [comment]
@nikwen friendly ping, want to send a PR?

**Comment by nikwen** [comment]
I don't have time for fixing this myself, sorry. ;)

**Comment by evilebottnawi** [comment]
Information: also need account `wds` name or allow developers redefine

**Comment by sudipt1999** [comment]
@nikwen  I am new to webpack and want to contribute to it . Can I work on it.

**Comment by nikwen** [comment]
I am just the creator of this issue. I'm not involved in the project 
otherwise.

That said, I don't see why the webpack folks wouldn't want you to 
contribute. ;)

**Comment by eragon512** [comment]
hey, I'm a new contributor and I'd like to take up this issue, if its available/active

**Comment by evilebottnawi** [comment]
Yes, PR welcome

**Comment by evilebottnawi** [comment]
Apparently this change does not interest anyone, so I close the problem, but if you want to improve the message feel free to send a PR!
