### ISSUE TITLE
A refresh bug about nuxt and iframe - I am very much looking forward to webpack_hmr is based on WebSocket, not server-sent event

### ISSUE THREAD

**Issue by yuchonghua** [webpack/webpack-dev-middleware#304]
# [A refresh bug about nuxt and iframe](https://github.com/nuxt/nuxt.js/issues/3258#issuecomment-386949276)

## I am very much looking forward to webpack_hmr is based on WebSocket, not server-sent event

> The Issues page for this repository is not a support forum. **Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid." Please do not delete this template from a new issue. Please remove this header to acknowledge this message.

* Operating System:
* Node Version:
* NPM Version:
* webpack version:
* webpack-dev-middleware Version:

- [ ] This is a **feature** request
- [x] This is a [**bug**](https://github.com/nuxt/nuxt.js/issues/3258#issuecomment-386949276)

### Code

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```js
// please provide your webpack.config.js for bug reports
```

```js
// additional code
```

**Comment by shellscape** [comment]
I'm sorry, but this is not a valid issue.
