### ISSUE TITLE
Hello, I have a suggestion.

### ISSUE THREAD

**Issue by shenguotao2015** [webpack/webpack-dev-middleware#305]
I used it for the first time, and a lot of it was not very clear, but it was very good, thank you for providing this middleware.

My suggestion is can you add the support of template engine analysis in the middleware, or provide a callback function for us to use? For example, ejs, jade:

```js
    var ejs = require('ejs');
    
    if (/\.html$/.test(filename)) {
        res.send(ejs.render(content.toString(), { 'title': 'xxxxx' }))
    } else {
        if (res.send) res.send(content);
        else res.end(content);
    }
```

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
