### ISSUE TITLE
Webpack middleware not working after update from ASP.NET 2.1 to ASP.NET core 2.1-RC

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [webpack/webpack-dev-middleware#308]
* Operating System: windows 10
* Node Version: v8.11.1
* NPM Version: 6.0.1
* webpack version: 4.8.3
* webpack-dev-middleware Version: 
* webpack-dev-server : "3.1.4"
* webpack-hot-middleware : "2.22.2"

- [ ] This is a **bug**
ASP.NET core 2 aurelia project update from core 2.0 to core 2.1-rc then webpack middleware  throw below error 

  | Name | Value | Type
-- | -- | -- | --
◢ | InnerException | {Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Cannot destructure property `analyze` of 'undefined' or 'null'. TypeError: Cannot destructure property `analyze` of 'undefined' or 'null'.     at module.exports (E:\WorkDIR\VSTS\Adra.Matcher\Source\Adra.Matcher.Web\webpack.config.js:14:18)     at createWebpackDevServer (E:\WorkDIR\VSTS\Adra.Matcher\Source\Adra.Matcher.Web\node_modules\aspnet-webpack\WebpackDevMiddleware.js:209:31)     at createWebpackDevServer (C:\Users\lilans\AppData\Local\Temp\32thujbp.0et:74:50)     at C:\Users\lilans\AppData\Local\Temp\vaustf4p.hem:114:19     at IncomingMessage.<anonymous> (C:\Users\lilans\AppData\Local\Temp\vaustf4p.hem:133:38)     at emitNone (events.js:106:13)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickCallback (internal/process/next_tick.js:180:9)    at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)    at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)    at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)    at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)} | System.Exception {Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException}

**Comment by shellscape** [comment]
Thanks for the issue :beer:

There's a few things awry with this issue, however:

- you're reporting an issue for an unstable environment version 
- you're reporting an issue for a dependency of the package you're using in your environment. 
- nothing has changed while your environment version has

Please debug this issue in your environment with that package instead. If you find an exact cause that is the fault of this module, we'll be happy to examine the cause.

**Comment by LilanMadusankaSilva** [comment]
I will try and update you guys
