### ISSUE TITLE
Version number of webpack-log dependency is incorrect

### ISSUE THREAD

**Issue by svicalifornia** [webpack/webpack-dev-middleware#317]
Issue #310 rightly pointed out that the version 1.0.1 of webpack-log does not work with webpack-dev-middleware, so "^1.0.1" is an invalid semvar dependency specification for this package. "^1.0.1" indicates that version 1.0.1 should work, which is false. The resolution of "^1.0.1" to a later version of webpack-log on a fresh install is not a valid argument, for multiple reasons:

1. It disregards the semvar specification defining the meaning of the ^ syntax.
2. A fresh install of node_modules should not be required to use webpack-dev-middleware.
3. A project may have already installed version 1.0.1 (or some other version that matches "^1.0.1" yet is incompatible with webpack-dev-middleware), and therefore the correct later version (1.2.0) will not be installed.

As the reporter of #310 (somewhat snarkily) pointed out, this trouble could be avoided by you folks being good stewards of your package.json and updating the version number of webpack-log to match only the versions that are compatible with webpack-dev-middleware.

I will make it easy for you by contributing the PR momentarily.

**Comment by evilebottnawi** [comment]
@svicalifornia why just doesn't update own packages?

**Comment by svicalifornia** [comment]
What part of this do you guys not understand? Your package.json needs to specify the correct version number ranges of the dependencies that you require. `"webpack-log": "^1.0.1"` is not correct, because webpack-dev-middleware doesn't work with version webpack-log 1.0.1.

The whole point of listing the dependencies in package.json is so that the package manager can decide what needs to be installed or upgraded. There are lots of reasons why a project might need to stay on an older version of a dependency, and your "^1.0.1" is telling us (incorrectly!) that version 1.0.1 is OK. What do you not understand about that?

**Comment by svicalifornia** [comment]
My exasperation above resulted from reading through the first attempt to get this fixed in #310, seeing it dismissed for no good reason, and then seeing the same thing happen again when I re-raised the issue herein. I'm not understanding why there have been so many defenses or shrugs from the maintainers regarding a bad dependency spec, especially after it is reported by multiple users of this library.

**Comment by michael-ciniawsky** [comment]
There is no harm in bumping the dependency to start from `^1.2.0` (more the opposite) instead of `^1.0.1`, especially when mutliple user report problems in this area. I don't really understand the fuss here :). Normally folks need to update there lockfiles if stuck on an outdated version correct, but the issue here is that 'outdated' means **broken**, so better bump to the minimum to the last working version like in #318 which should get in asap 😛

**Comment by svicalifornia** [comment]
Thank you.
