### ISSUE TITLE
Quiet and noInfo options not suppressing logs in browser

### ISSUE THREAD

**Issue by bradbarrow** [webpack/webpack-dev-middleware#33]
Hi, 

I'm using the API and setting `quiet` and `noInfo` to true as follows: 

```
  new WebpackDevServer(webpack(webpackConfig.client), {
    publicPath: webpackConfig.client.output.publicPath,
    hot: true,
    quiet: true,
    noInfo: true
  }).listen(4000, 'localhost', function (err, result) {
    if(err) {
      console.log('error', err);
    }
    else {
      console.log('info', "dev server listening on 4000");
    }
  });
```

When I run the server `node devServer.js` I simply get the `dev server listening on 4000` message and no other output which is what I want. 

When I visit my app in the browser though, which includes the following:

`<script src="http://localhost:4000/bundle/client.js"></script>`

My browser's console is spammed with socket logs. Is this expected? Shouldn't the quiet option prevent this?

**Comment by SpaceK33z** [comment]
This is related to webpack-dev-server. There are more people over there who want this: webpack/webpack-dev-server#109
