### ISSUE TITLE
Got error file path in 3.4.0 with path.posix.join

### ISSUE THREAD

**Issue by wellingfine** [webpack/webpack-dev-middleware#343]
Please see the runtime result below , I turn on debugger in vscode ,and add 4 variables
![image](https://user-images.githubusercontent.com/1908803/47264843-dc9a4d80-d550-11e8-9c02-ab6170a51a16.png)

* Operating System: win10
* Node Version: 8.11.4
* NPM Version:5.6.0
* webpack version:4.21.0
* webpack-dev-middleware Version:3.4.0

- [ ] This is a **feature** request
- [x] This is a **bug**

### Expected Behavior
Get an absolute path
### Actual Behavior
Get a relative path ,so `context.fs.statSync(filename)` will throws `no such file or directory` error and then middleware exit

### For Bugs; How can we reproduce the behavior?
I try it in windows10 , once the path contains `..` will not get  the expected result <br>
![image](https://user-images.githubusercontent.com/1908803/47265161-1faaef80-d556-11e8-88b0-ae01670b21c9.png)

But `path.posix.join` is ok with CentOS .

**Comment by apexearth** [comment]
I'm not sure if we were having the same problem, but...

I had my webpack output path set to `__dirname + '/../build'` and I was unable to get results.
I stepped through the webpack-dev-middleware to see that path.posix.join was giving that a `build/` prefix when getting the filename [here](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/util.js#L94). This meant that requesting a file in root would come out as a request for the file in `build/` which wasn't right.

Through some testing I saw that poxis join doesn't like the mixing of path separator types. (`/` vs `\`) 

To ensure I had consistent path separators I changed my webpack output path to: 
`path: path.join(__dirname, '..', 'build')`

😅 oops

**Comment by evilebottnawi** [comment]
@alanpearce expected, don't use mix `/` and `\`
@wellingfine can you create minimum reproducible test repo? Looks like regression.

**Comment by wellingfine** [comment]
@apexearth Agree !Need to preprocess the output path.
@evilebottnawi I make a repo at local .Find out that's not only the mix `/` and `\`, 
```javascript
//test cases about posix.join
path.posix.join('D:\\a\\b/../c','x/y.png')  //get c/x/y.png
path.posix.join('D:\\a\\b/c','x/y.png')  //get D:\a\b/c/x/y.png
path.posix.join('D:\\a\\b\\..\\c','x/y.png')  //get D:\a\b\..\c/x/y.png

```
So it is the three symbol `..` `/` `/` together cause my problem... Preprocessing output path is one of the solutions . If someone forget about it , may get the same problem :-( 

Finally I advice using `path.join` at [here](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/util.js#L94) ,good for windows .And it will never cause any problem in Linux or MacUnix ,because they will not use `\` at any condition.

Or before joining the paths ,preprocess outputpath `path.resolve(outputPath)`
