### ISSUE TITLE
Option to customize log name

### ISSUE THREAD

**Issue by stevenvachon** [webpack/webpack-dev-middleware#344]
* Operating System: macOS 10.14
* Node Version: 10.11.0
* NPM Version: 6.4.1
* webpack version: 4.20.2
* webpack-dev-middleware Version: 2.0.6

- [x] This is a **feature** request
- [ ] This is a **bug**

### Code

```js
options = {
    logName: 'webpack'
};
```

### For Features; What is the motivation and/or use-case for the feature?
"wdm" is not clear what it is and looks a bit confusing.

**Comment by evilebottnawi** [comment]
@stevenvachon Why? What is use case? It is bad practice add new option just "if you change name because you want"

**Comment by evilebottnawi** [comment]
@stevenvachon not sure we really need this, adding new options increase complex of program/library and implement it only because "i (my team) want something" is not enough for this, please describe **real** use case why it is `confusing` and where is `confusing`.

**Comment by stevenvachon** [comment]
Because just do it.
