### ISSUE TITLE
Change logging output name from 'wdm'

### ISSUE THREAD

**Issue by ovikholt** [webpack/webpack-dev-middleware#345]
Running
$ npm test

we get

### Actual Behavior

ERROR in ./tests/routes/Progress/components/Carousel.spec.coffee
Module not found: Error: Can't resolve 'enzyme' in '.../tests/routes/Progress/components'
 @ ./tests/routes/Progress/components/Carousel.spec.coffee 7:0-32 13:24-30
 @ ./tests sync \.(spec|test)\.(js|ts|tsx|coffee|litcoffee|coffee\.md)$
 @ ./tests/test-bundler.js
ℹ ｢**wdm**｣: Failed to compile.

### Expected Behavior

but should  get

ERROR in ./tests/routes/Progress/components/Carousel.spec.coffee
Module not found: Error: Can't resolve 'enzyme' in '.../tests/routes/Progress/components'
 @ ./tests/routes/Progress/components/Carousel.spec.coffee 7:0-32 13:24-30
 @ ./tests sync \.(spec|test)\.(js|ts|tsx|coffee|litcoffee|coffee\.md)$
 @ ./tests/test-bundler.js
ℹ ｢**webpack-dev-middleware**｣: Failed to compile.

### For Bugs; How can we reproduce the behavior?

Here, 
https://github.com/webpack/webpack-dev-middleware/blob/master/lib/context.js#L21
Please change  that string from wdm to webpack-dev-middleware, so  that also people not too deep in this package can understand their console output. :'(

**Comment by evilebottnawi** [comment]
No need

**Comment by evenstensberg** [comment]
What we could do is to change the [ on each side of the name to support windows. On widows it results in a question mark

**Comment by evilebottnawi** [comment]
@evenstensberg hm, what is problem with name?

**Comment by evenstensberg** [comment]
Nothing, but the brackets around it is not supported on windows

**Comment by evilebottnawi** [comment]
@evenstensberg Looks this issue is not about `[` abd `]`

**Comment by evenstensberg** [comment]
Indeed, just giving some feedback while at it

**Comment by gpoitch** [comment]
I agree "wdm" is odd to a user who didn't integrate the middleware.  It would be nice to suppress these logs completely but lowering the `logLevel` hides all build output.

**Comment by aikar** [comment]
i would prefer 'webpack'. dev middleware is a useless detail to the user viewing the logs.

pre the v4 update i manually added a webpack prefix to my logs. but would be nice if the prefix was more intuitive, or least configurable.

**Comment by evilebottnawi** [comment]
@gpoitch 

> change the default prefix to 'webpack' for clarity

Can you clarify?

> logLevel: 'silent' should only supress logs from webpack-dev-middleware. It currently supresses webpack stats too. That is a separate thing that is configurable by { stats: 'none' } if you don't want them.

Sounds resonable

**Comment by gpoitch** [comment]
> Can you clarify?

Simply suggesting changing the default log prefix from 'wdm' to 'webpack' (@aikar suggested this too) as a first step because no one knows what 'wdm' means as a user/on a team unless you personally integrated this middleware.

**Comment by evilebottnawi** [comment]
@gpoitch in other side `webpack` is misleading, because this output generated not `webpack`, it is generated `webpack-dev-middleware`, other plugins/middlewares/etc also can generate information, why we use `wdm`, because `webpack-dev-middleware` have long name in console and it is looks very bad.

**Comment by gpoitch** [comment]
@evilebottnawi that is a fair point.  Adding it as an option would satisfy all parties then.

I personally don't want these logs at all and just the stats, hence my logLevel suggestion but that is somewhat separate from the original issue now.

**Comment by evilebottnawi** [comment]
@gpoitch yep, feel free to send a PR with improving `logLevel`, don't think we really need change name right now, also it is not high priority

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack-dev-middleware/issues/302
