### ISSUE TITLE
Unwanted charset=UTF-8 always added to custom mime types

### ISSUE THREAD

**Issue by gpoitch** [webpack/webpack-dev-middleware#350]
* Operating System: macOS 10.14
* Node Version: 10.4.1
* NPM Version: 6.4.1
* webpack version: 4.27.1
* webpack-dev-middleware Version: 3.4.0

- [x] This is a **feature** request
- [x] This is a **bug**

Since https://github.com/webpack/webpack-dev-middleware/pull/136, `charset=UTF-8` is always appended to the Content-Type header.  If I define custom mime types, I believe that this shouldn't be appended.  

For example, mobile safari can render 3d/AR models in a native viewer when a file is served with ` model/vnd.pixar.usd`. When setting the option `mimeTypes: { 'model/vnd.pixar.usd', ['usdz'] }`, the server will return: `Content-Type: model/vnd.pixar.usd; charset=UTF-8`.  The addition of the charset causes the browser to incorrectly interpret the mime type.

This is already special-cased for wasm.

### Expected Behavior
charset=UTF-8 is not appended to every Content-Type header when defining custom mimeTypes.

### Actual Behavior
charset=UTF-8 is always appended

I can make a PR if you agree on the proposed behavior.

**Comment by evilebottnawi** [comment]
@gpoitch hm, sound reasonable, any ideas how we can detect when we need add `charset` when not?

**Comment by gpoitch** [comment]
@evilebottnawi yes, after some digging looks like it should be added only if charset is defined for the type in mime-db (https://github.com/jshttp/mime-db/blob/master/db.json)

**Comment by gpoitch** [comment]
https://github.com/webpack/webpack-dev-middleware/pull/351

**Comment by hiroppy** [comment]
hmm, it seems we need to overwrite below lines.

```
  res.setHeader('Content-Type', type + '; charset=utf-8')
  res.setHeader('Content-Length', Buffer.byteLength(body, 'utf8'))

  // body
  res.end(body, 'utf8')
```

Yes, I agree with you. We need to provide a new option for overwriting this.

**Comment by hiroppy** [comment]
ok, I'll take over this.

**Comment by evilebottnawi** [comment]
Just for information, https://github.com/expressjs/serve-static/blob/master/index.js do not use `utf8`, maybe we should investigate deeply

**Comment by hiroppy** [comment]
This problem seems to be difficult because express is writing utf-8 directly.😥

**Comment by evilebottnawi** [comment]
Fixed in `next`
