### ISSUE TITLE
Old files are being served in dev mode, restarting server, clearing cache does not help

### ISSUE THREAD

**Issue by Foxhoundn** [webpack/webpack-dev-middleware#358]
I can literally delete all app files, wait for recompile, shut down the server, start the server, go to the url and the app loads like I didn't delete nothing - what's going on?

Some info:

- Version used was 1.12.*
- Starting the server with `babel-node server.js`

Webpack config -

```
// @flow
const path = require('path');
const webpack = require('webpack');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

// Root path
const root = path.resolve(__dirname, './');

module.exports = {
  mode: 'development',
  context: `${root}/src`,
  entry: {
    qorus: [`${root}/src/index.jsx`],
  },
  output: {
    path: `${root}/dist`,
    filename: '[name].bundle.js',
    chunkFilename: '[name].bundle.js',
    publicPath: '/',
  },
  resolve: {
    modules: [`${root}/src/js`, 'node_modules'],
    extensions: ['.js', '.jsx'],
  },
  cache: false,
  devtool: 'eval-source-map',
  module: {
    rules: [
      {
        test: /\.js(x)?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.(html|mp3|ttf|woff|woff2|eot|svg)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
            },
          },
        ],
      },
      {
        test: /\.(c|sc)ss$/,
        use: [
          'style-loader',
          MiniCssExtractPlugin.loader,
          'css-loader',
          'sass-loader',
        ],
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'css/base.css',
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    }),
    new webpack.ProvidePlugin({
      Promise:
        'imports-loader?this=>global!exports-loader?global.Promise!es6-promise',
      fetch:
        'imports-loader?this=>global!exports-loader?global.fetch!whatwg-fetch',
    }),
    new webpack.NoEmitOnErrorsPlugin(),
  ],
};
```

Server config 
```
// @flow
const express = require('express');
const history = require('connect-history-api-fallback');
const serveStatic = require('serve-static');

const config = require('./webpack.config');
const devConfig = require('./webpack.config/dev');
const serverConfig = require('./server_config');
const WebpackDevServer = require('webpack-dev-server');
const proxyMiddleware = require('http-proxy-middleware');

const app = express();
const env = app.get('env');

if (env === 'production') {
  app.use(history());
  app.get('*', serveStatic(config.output.path));
} else {
  // Get webpack
  const APIconfig = require('./server_config.js');
  const webpack = require('webpack');
  // Get the webpack compiler
  const compiler = webpack(config);

  app.use((req, res, next) => {
    const router = new express.Router();

    router.use(proxyMiddleware(APIconfig.restBaseUrl));
    router.use(proxyMiddleware(APIconfig.extensionProxy));
    router.use(proxyMiddleware(APIconfig.dbProxy));
    router.use(proxyMiddleware(`${APIconfig.wsBaseUrl}/log`));
    router.use(proxyMiddleware(`${APIconfig.wsBaseUrl}/apievents`));

    router(req, res, next);
  });

  /* app.use(proxyMiddleware(APIconfig.restBaseUrl));
  app.use(
    proxyMiddleware('/apievents', {
      target: `${APIconfig.wsBaseUrl}/apievents`,
      ws: true,
    })
  );*/

  // History
  app.use(history());

  // Dev server
  app.use(
    require('webpack-dev-middleware')(compiler, {
      contentBase: config.context,
      inline: true,
      host: process.env.HOST || 'localhost',
      port: parseInt(process.env.PORT, 10) || 3000,
      historyApiFallback: true,
      publicPath: config.output.publicPath,
      noInfo: false,
      stats: { colors: true },
    })
  );

  // Serving
  app.get('*', serveStatic(config.context));
}

// Dev config
const dConfig = devConfig();

app.listen(dConfig.port, dConfig.host, () => {
  process.stdout.write(
    `Qorus Webapp ${app.get('env')} server listening on ` +
      `http://${serverConfig.host}:${serverConfig.port}\n`
  );
});
```

Please help

- Webpack does complain about missing files but the app works in the browser which means the bundle is cached somewhere who knows where
<img width="719" alt="screenshot 2019-01-14 at 13 16 17" src="https://user-images.githubusercontent.com/8861481/51112125-ae9a7180-17fe-11e9-8f1e-795299c589cb.png">

**Comment by Foxhoundn** [comment]
I'm closing on 35 hours on SOLELY this issue, please any help is appreciated. I've tried everything i've found on the net, restarting computer, but NOTHING is making webpack-dev-middleware serve latest files.

Is there a .cache folder I can delete or something?

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by Foxhoundn** [comment]
This was caused by `http-proxy-middleware` package, for some reason it was causing wdm to serve some ancient files. All is safe and sound. Sorry for the confusion!

**Comment by ButchMonkey** [comment]
@Foxhoundn I'm having the same issue here. 

How did you solve this? Of course, removing `http-proxy-middleware` isn't an option as it is a dependency for `webpack-dev-server`

**Comment by Conversional** [comment]
> This was caused by `http-proxy-middleware` package, for some reason it was causing wdm to serve some ancient files. All is safe and sound. Sorry for the confusion!

So can you give a hint what you did? I am having the same problem.

**Comment by ButchMonkey** [comment]
I ran into this issue a while a go and it turned out to be that there was an error during the build. I missed the error message as it was at the top of the log. Dev server then serves the last successful build

**Comment by ascott18** [comment]
I ran into this and found that it was one of the various caches in `node_modules/.cache`. Deleting the `.cache` folder instantly fixed the problem for me.

![image](https://user-images.githubusercontent.com/5017521/86409263-5adb4c80-bc6d-11ea-9c3e-b1a53b5a9ab0.png)

**Comment by fanqidi-xbrother** [comment]
> This was caused by `http-proxy-middleware` package, for some reason it was causing wdm to serve some ancient files. All is safe and sound. Sorry for the confusion!

hello ? what did you do to solve this ? i think i have the same problem caused by `http-proxy-middleware`

**Comment by matthias-ccri** [comment]
@Foxhoundn what was the fix?

**Comment by redcartel** [comment]
I had been running dev in yarn and then for whatever absentminded reason was running it in npm one day and kept getting this problem. Switching back to yarn dev did the trick.

**Comment by neil-ji** [comment]
I have same problem and I suspect it's caused by browser because of I find it happens on my  Eadge rather than Chrome.
