### ISSUE TITLE
ConcurrentCompilationError with lazy: true when multiple entry points present

### ISSUE THREAD

**Issue by MonochromeChameleon** [webpack/webpack-dev-middleware#359]
* Operating System: macOS High Sierra 
* Node Version: 10.15.0
* NPM Version: 6.5.0
* webpack version: 4.28.4
* webpack-dev-middleware Version: 3.5

- [ ] This is a **feature** request
- [X] This is a **bug**

### Code

```js
// webpack.config
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  mode: 'development',
  plugins: [new MiniCssExtractPlugin()],
  module: {
    rules: [{
      test: /\.css$/,
      use: [MiniCssExtractPlugin.loader, 'css-loader'],
    }],
  },
};
```

```js
// ./src/main.js
import './style.css';

document.write('it works');
```

```css
/* ./src/style.css */
* {
    font-size: xx-large;
}
```

```html
<!-- ./src/index.html -->
<html lang="en">
<head>
  <link rel="stylesheet" href="./main.css"/>
  <script src="./main.js"></script>
</head>
</html>
```

```js
// ./server.js
const express = require('express');
const webpack = require('webpack');
const WebpackDevMiddleware = require('webpack-dev-middleware');
const webpackConfig = require('./webpack.config');

const lazy = process.argv.reverse()[0] === '--lazy';
const app = express();

app.use(WebpackDevMiddleware(webpack(webpackConfig), { lazy }));
app.use(express.static('./src'));

app.listen(3000, () => console.log('app started'));
```

### Expected Behavior

All assets should be compiled and served, allowing the page to load

### Actual Behavior

Behaviour is as expected when webpack-dev-middleware is configured with lazy: false.
When lazy: true is supplied as an option, the two requests for css & js both trigger recompilation, resulting in a concurrent compilation error.

### How can we reproduce the behavior?

Create any project with two compiled assets requested in parallel, served by webpack-dev-middleware with { lazy: true }

### Possible solution

Change lib/util.js around line 152 from:
```js
// in lazy mode, rebuild on bundle request
if (context.options.lazy && (!context.options.filename || context.options.filename.test(filename))) {
  context.rebuild();
}
```
to
```js
// in lazy mode, rebuild on bundle request
if (context.options.lazy && !context.compiler.running && (!context.options.filename || context.options.filename.test(filename))) {
  context.rebuild();
}
```

**Comment by evilebottnawi** [comment]
Why you use `lazy`?

**Comment by MonochromeChameleon** [comment]
@evilebottnawi Some platforms don't properly support filesystem watch e.g. when running an app inside docker on Windows 7. `lazy` bypasses that problem

**Comment by evilebottnawi** [comment]
@MonochromeChameleon why don't use `poll: true`? It is normal using this for filesystem what doesn't support watch.

Also can you create minimum reproducible test repo?

**Comment by MonochromeChameleon** [comment]
@evilebottnawi I don't see poll as a documented option? 

test repo is now here: https://github.com/MonochromeChameleon/wdm-lazy-bug

**Comment by MonochromeChameleon** [comment]
@evilebottnawi Thanks - I'll look into the watchoptions to see whether that works (or at least, I'll get one of my colleagues who has a win7 computer to do so!) in the meantime, I've PR'd up my proposed change just in case :)

**Comment by mathisonian** [comment]
I'm hitting this same error. FWIW my use-case for using `lazy` is that I'm working on a project with hundreds of different HTML pages, and I don't want these to be compiled unless the dev specifically navigates to them - otherwise if everything compiled at once things are just way too slow.

**Comment by evilebottnawi** [comment]
@mathisonian you can send a PR with fix, here description https://github.com/webpack/webpack-dev-middleware/pull/360

**Comment by evilebottnawi** [comment]
Let's close issue in favor https://github.com/webpack/webpack-dev-middleware/issues/409, feel free to feedback
