### ISSUE TITLE
Inconsistency with webpack: writeToDisk output of file with question mark in name

### ISSUE THREAD

**Issue by iliakan** [webpack/webpack-dev-middleware#367]
Node: 11, Webpack: 4.28.4 (all latest).

In webpack.config:
```js
output:    {
  ...
  filename: '[name].js?[hash]'
}
```

Regular webpack creates files on disk like `main.js`.

But webpack-dev-server with writeToDisk option writes files like `main.js?abcdef`.

I suggest to remove `?abcdef` from file names when they are written to disk, to be consistent with what webpack does.

Maybe patch `toDisk` in `fs.js` for that?

**Comment by evilebottnawi** [comment]
@iliakan already fixed in master, wait webpack-dev-server release

**Comment by evilebottnawi** [comment]
Here https://github.com/webpack/webpack-dev-middleware/blob/master/lib/fs.js#L29
