### ISSUE TITLE
Content-Type set by other middleware gets overwritten

### ISSUE THREAD

**Issue by dmohns** [webpack/webpack-dev-middleware#376]
* Operating System: macOS 10.14.3
* Node Version: `v11.10.0`
* NPM Version: `6.8.0`
* webpack version: `4.29.6`
* webpack-dev-middleware Version: `3.6.0`

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

I am working with a custom middleware to serve static assets from their gzipped versions, like so:

```javascript
app.use(function (req, res, next) {
  if (req.url.endsWith('css')) {
    req.url = req.url + '.gz';
    res.set('Content-Encoding', 'gzip');
    res.set('Content-Type', 'text/css');
  }
  next()
});
```

Unfortunately, `webpack-dev-middleware` overwrites `Content-Type` regardless of whether or not it's been set already by another middleware. See

https://github.com/webpack/webpack-dev-middleware/blob/e5bd8f8d1b12543938601f1daab40e6173db7489/lib/middleware.js#L82

### Expected Behavior

In the resulting request: `Content-Type: text/css`

### Actual Behavior

In the resulting request: `Content-Type: application/gzip; charset=UTF-8`

**Comment by dmohns** [comment]
@clshortfuse you had some trouble with incorrect mimeTypes set by `webpack-dev-middleware`. Is this problem similar?

**Comment by evilebottnawi** [comment]
We should add check if header already exists, feel free to send a PR with fix :+1:

**Comment by evilebottnawi** [comment]
Release https://github.com/webpack/webpack-dev-middleware/releases/tag/v3.6.1
