### ISSUE TITLE
Content-Length is overwritten by ExpressJS

### ISSUE THREAD

**Issue by dmohns** [webpack/webpack-dev-middleware#379]
* Operating System: macOS 
* Node Version: `v11.10.0`
* NPM Version: `6.8.0`
* webpack version: `4.29.6`
* webpack-dev-middleware Version: `3.6.1`

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

Follow up to discovery in https://github.com/webpack/webpack-dev-middleware/pull/377#discussion_r263004819

It looks like the computation of `Content-Length` is not functional.

https://github.com/webpack/webpack-dev-middleware/blob/dba5e02876bb76d2301c93d20ec90f558147d5b4/lib/middleware.js#L85

ExpressJS takes care of setting `Content-Length` appropriately. See also: https://github.com/expressjs/express/issues/2893#issuecomment-185839759

In fact, even when removing the line in doubt the following test will succeed

```js
describe('Check Content-Length', () => {
  before((done) => {
    app = express();
    const compiler = webpack(webpackConfig);
    instance = middleware(compiler, {
      stats: 'errors-only',
      logLevel
    });
    app.use(instance);
    listen = listenShorthand(done);
  });
  after(close);

  it('Check ExpressJS Content-Length computation', (done) => {
    request(app).get('/bundle.js')
      .expect('Content-Length', '4631')
      .expect(200, done);
  });
});
```

### Expected Behavior

The code suggests that `webpack-dev-middleware` is responsible for setting `Content-Length` header.

### Actual Behavior

ExpressJS is setting `Content-Length` header.

### Discussion

From my understanding it is perfectly fine to let ExpressJS deal with `Content-Length`  header and simply remove the code from `webpack-dev-middleware`.

**Comment by evilebottnawi** [comment]
@dmohns thanks for investigate, let's do it, just remove this and add comment like "Content-Length header is unnecessary due Express already set header [linkToSouceCodeOfExpress]"

**Comment by gpoitch** [comment]
Wanted to chime in to say that this middleware works without Express.  I currently use it with plain node http.

**Comment by evilebottnawi** [comment]
Fixed in https://github.com/webpack/webpack-dev-middleware/pull/497
