### ISSUE TITLE
Response.getHeader may be undefined, not a function

### ISSUE THREAD

**Issue by sjy** [webpack/webpack-dev-middleware#380]
* Operating System: OSX
* Node Version: 10.15.1
* NPM Version: 6.4.1
* webpack version: 4.1.6
* webpack-dev-middleware Version: 3.6.1

- [x] This is a **bug**

### Expected Behavior
No error

### Actual Behavior
A TypeError throwed
```bash
 if (!res.getHeader('Content-Type')) {
...
}
```
![image](https://user-images.githubusercontent.com/1523060/53937052-e7f8aa80-40e6-11e9-85ee-207536d4aec6.png)

### For Bugs; How can we reproduce the behavior?
Use vue-cli create a app and install the latest version of webpack-dev-middleware

**Comment by sjy** [comment]
https://github.com/webpack/webpack-dev-middleware/pull/377 introduce this issue

**Comment by sjy** [comment]
@evilebottnawi  should i need to make a pr which will  check `getHeader` before call it

**Comment by evilebottnawi** [comment]
@sjy yep, feel free to send a PR, anyway what is use case where `getHeader` is undefined?

**Comment by sjy** [comment]
My project depends on `koa-webpack`, https://github.com/shellscape/koa-webpack/issues/109

**Comment by evilebottnawi** [comment]
@sjy we don't support officially `koa`, we can add check, but in future it can get other broken part

**Comment by dmohns** [comment]
Looks like help is on the way: https://github.com/shellscape/koa-webpack/pull/110

**Comment by hovoodd** [comment]
It's a `koa-webpack` issue, not `webpack-dev-middleware`

**Comment by nuintun** [comment]
Same problem !!

**Comment by wssgcg1213** [comment]
same problem.

**Comment by weipxiu** [comment]
无法解决的疑难问题，似乎是绝症

**Comment by davinma** [comment]
在 `"vuepress": "^0.14.10"` 下面新增一行 `"webpack-dev-middleware": "^3.6.0"` 即可。刚开始用 npm / yarn 安装的时候都报这个错误，参考 [issues/1417](https://github.com/vuejs/vuepress/issues/1417) 解决了，估计是版本号不兼容。

**Comment by evilebottnawi** [comment]
All comments are not in English are marked as spam.

**Comment by evilebottnawi** [comment]
Update your deps

**Comment by white87332** [comment]
same problem!!

**Comment by evilebottnawi** [comment]
Update your deps

**Comment by emilsedgh** [comment]
Which dependency must be used to resolve this?

It seems that koa-webpack is the package which included the fix but I'm not even using that.

Do I have to?

**Comment by hovoodd** [comment]
@emilsedgh are you sure about that? Is the `grep koa-webpack package-lock.json` output empty?

**Comment by emilsedgh** [comment]
Yes I'm quite sure of that.

It seems that koa-webpack wrapped webpack-dev-middleware and webpack-hot-client, which were already set up.

I'm in the process of porting to koa-webpack anyways, but I think this bugs means people wont be able to opt-out of that anymore.
