### ISSUE TITLE
Documentation on using with Express/ Webpack generated Views

### ISSUE THREAD

**Issue by george-norris-salesforce** [webpack/webpack-dev-middleware#392]
Setting up Webpack with Express throws `Cannot read property 'invalid' of undefined`

* Operating System: OSX
* Node Version: 10
* NPM Version: 5.6.0
* webpack version: 4.29.6
* webpack-dev-middleware Version: 3.5.1
- This is a **bug**

Trying to use this library with `HtmlWebpackPlugin` to generate some `handlebars` templates. Is this possible to do with this library?

- publicPath in Webpack config is set to `/contents/dist/assets/` 
- a view file in Express uses `handlebars`
- in Webpack config, `handlebars` template is setup to output correct  script tags / link stylesheet..

        new HtmlWebpackPlugin({
          template: 'views/index.handlebars',
          filename: 'views/index.handlebars',
        }),

   So this also output to `/contents/dist/assets/` under `views` folder. Thus, `/contents/dist/assets/views` is where it will be output.

- and in Express, a route is setup to serve this file.         
        route.get('*', (req, res) => {    
           res.render('index' .....)   

And...    
- I've setup `webpack-dev-middleware` to serve assets

```
  const webpack = require('webpack');
  const webpackDevMiddleware = require('webpack-dev-middleware');
  const config = require('../../webpack.config');
  const compiler = webpack(config);

  const app = express();

  app.use(webpackDevMiddleware(compiler, config.devServer));

```

- I've set up a `new CleanWebpackPlugin()` plugin, to delete the contents of the `dist` folder before each build, so it start with a fresh empty folder.

**How is this suppose to actually work?** 

Express is looking for the view where I've told it to look. 
```
const viewsDir = resolve(__dirname, '../../client/views');
app.set('views', viewsDir);
```

When I run webpack, it delete the contents of the `dist` folder so the view is not there. BUT, isn't `webpack-dev-middleware` ***suppose*** to serve all these assets (HTML, Handlebars, etc) via memory? Not the file system? When Express hits the `/` route, there is no view to serve. 

**How is all this suppose to hook together and work?**  

https://stackoverflow.com/questions/55660079/webpack-dev-middleware-express-and-webpack-generated-views-how-is-this-suppose

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack-dev-middleware/issues?q=is%3Aissue+is%3Aclosed

**Comment by evilebottnawi** [comment]
You have invalid configuration. webpack-dev-middleware already store all in memory.

**Comment by evilebottnawi** [comment]
You don't need `CleanWebpackPlugin`, because no assets in file system

**Comment by evilebottnawi** [comment]
Also `devServer` !== `webpack-dev-middleware`

**Comment by george-norris-salesforce** [comment]
Sorry a little confused. What is invalid? 
CleanWebpackPlugin may be unnecessary. But since `webpack-dev-middleware` serves from memory, it wouldn’t interfere and mess it up right?

I’ve removed CleanWebpackPlugin. But the resulting template has no injected script / style tags.

**Comment by george-norris-salesforce** [comment]
Is it possible to use something like `HtmlWebpackPlugin` that generates a template / injects script and style tags — with `webpack-dev-middleware`?

**Comment by evilebottnawi** [comment]
How it is related to `webpack-dev-server`? We just middleware for express, we provide access to assets from webpack and all. If `HtmlWebpackPlugin` emit assets you can get their by url, if not you can't give their.
