### ISSUE TITLE
Higher CPU load than webpack-dev-server?

### ISSUE THREAD

**Issue by naganowl** [webpack/webpack-dev-middleware#40]
I was playing around with making my own asset server (to replace webpack-dev-server) and noticed that it causes a huge spike in CPU load (~100% with fans spinning) compared to the dev server (~3%) when both are just idling.

These are just measured using Activity Monitor on a 10.9.5 Macbook Pro (quad core i7, 16GB RAM). Don't think the specs of the machine are super relevant, but there's definitely a noticeable difference when switching between the two and wanted to see if anyone had input.

**Comment by avioli** [comment]
Same here, although CPU usage at about 40%, not as high as 100%, but still not < 5%.
```
"express": "^4.13.3",
"webpack": "^1.12.2",
"webpack-dev-middleware": "^1.2.0",
```
```
Mac OS X 10.11.1, 2.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3
```

[webpack.config.js](https://gist.github.com/avioli/a5ed73d82c7f5e5a27fb)

**Comment by avioli** [comment]
... It's all because of the webpack watcher.

**Comment by eriknyk** [comment]
same problem, with a similar configuration of @avioli 
any thoughts?

**Comment by mbektimirov** [comment]
I have about 100% on my CPU, memory is growing too. I tried to profile it with `node-inspector` but it was not that easy.

**Comment by sokra** [comment]
propably the native module for the watcher is not installed, so the watcher switch to polling mode, which is cpu intensive. Try to install the fsevents module for OS X, or increase the polling frequency.

**Comment by michaek** [comment]
This is a counterintuituve solution, as chokidar does list fsevents in `optionalDependencies`, and it was installed successfully in my project. Nonetheless, `npm i --save-dev fsevents` dropped my CPU use from 40% of a core to 0%.

**Comment by SpaceK33z** [comment]
Closing this issue because it's not related to this middleware. [watchpack](https://github.com/webpack/watchpack) is related.

**Comment by DominicTobias** [comment]
Thanks @michaek !!! Work proxy was freezing the install of fsevents and I was cancelling it, thinking nothing bad was happening

**Comment by arobbins** [comment]
@michaek Worked for me as-well, thanks.

**Comment by index-swf** [comment]
I've had the same problem since I updated node, `npm rebuild fsevents` is also worked. Some packages need to be rebuilt after system upgrade. I wonder if webpack-dev-server should output a warn when it detects that fsevents is unavailable on Mac.
I apologize for my bad English.

**Comment by nchase** [comment]
amazing. thank you, @michaek!
