### ISSUE TITLE
`fs` implementation also requires `mkdirp`

### ISSUE THREAD

**Issue by progman32** [webpack/webpack-dev-middleware#405]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The documentation for the `fs` option mentions that `join` must be supported by the `fs` implementation (which the Node filesystem API does not, directly). However, it also requires `mkdirp` today. Attempting to follow the documentation's advice results in:
```
[1] emitting(node:14029) UnhandledPromiseRejectionWarning: TypeError: this.outputFileSystem.mkdirp is not a function
    at hooks.emit.callAsync.err (/home/ferrari/code/platform-ui/frontend/node_modules/webpack/lib/Compiler.js:306:26)
```

### Your Proposal for Changes

Not sure. Possibly point users in the direction of the NodeOutputFilesystem in webpack, which supports the method:
```js
const NodeOutputFileSystem = require('webpack/lib/node/NodeOutputFileSystem');
module.exports = {
  devServer: {
    fs: new NodeOutputFileSystem(),
    // etc
  }
};
```
```

**Comment by evilebottnawi** [comment]
Thanks for issue, it is bug, we need add check as here https://github.com/webpack/webpack-dev-middleware/blob/master/lib/fs.js#L102

**Comment by wusiquan** [comment]
use the `fs` option, I found the same error

temporarily usage, edit from https://github.com/webpack/webpack-dev-middleware/issues/405#issue-446382355

```javascript
class MyNodeOutputFileSystem {
	constructor() {
		this.mkdirp = mkdirp;
		this.mkdir = fs.mkdir.bind(fs);
		this.rmdir = fs.rmdir.bind(fs);
		this.unlink = fs.unlink.bind(fs);
		this.writeFile = fs.writeFile.bind(fs);
    this.join = path.join.bind(path);
    // 
    this.statSync = fs.statSync.bind(fs);
    this.readFileSync = fs.readFileSync.bind(fs);
	}
}

{
  fs: new MyNodeOutputFileSystem()
}
```

**Comment by evilebottnawi** [comment]
Fixed
