### ISSUE TITLE
webpack/lib/node/NodeOutputFileSystem removed in Wepback 5

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpack/webpack-dev-middleware#435]
* Operating System: Mac 10.14.5
* Node Version: 8.9 _(but it's not relevant to this issue)_
* NPM Version: Yarn 1.15.2
* webpack Version: 5.0.0-alpha.17
* webpack-dev-middleware Version: 3.7.0

### Expected Behavior

Don't crash when starting a Webpack dev server.

### Actual Behavior

```
Error: Cannot find module 'webpack/lib/node/NodeOutputFileSystem'
Require stack:
- ../node_modules/webpack-dev-middleware/lib/fs.js
- ../node_modules/webpack-dev-middleware/index.js
- ../node_modules/webpack-dev-server/lib/Server.js
```

### Code

```js
const NodeOutputFileSystem = require('webpack/lib/node/NodeOutputFileSystem');

const { mkdirp } = new NodeOutputFileSystem();
```

`mkdirp` in `NodeOutputFileSystem` is directly `require("mkdirp")` per #405. I think this issue would be fixed if `fs.js` directly had `const mkdirp = require("mkdirp");` instead.

### How Do We Reproduce?

Try out the Webpack 5 alpha: https://github.com/webpack/webpack/issues/8537

Issue reported on that thread: https://github.com/webpack/webpack/issues/8537#issuecomment-504672759

**Comment by evilebottnawi** [comment]
Yes, you are right, PR welcome
