### ISSUE TITLE
Conflict with html-webpack-plugin on catch all route

### ISSUE THREAD

**Issue by patrickheeney** [webpack/webpack-dev-middleware#46]
I have a single page app and I am using the middleware during dev. I want to route all requests in express to the `index.html` file so that my spa router takes over. There seems to be a problem with `webpack-dev-middleware` trying to detect the file or path, which prevents me from rendering the `index.html` file with the `html-webpack-plugin`. 

Here is essentially what I have:

```
// webpack.config
    new HtmlWebpackPlugin({
      template : paths.src('index.html'),
      hash     : true,
      filename : 'index.html',
      inject   : 'body'
    })

// server.js
const devMiddleware = WebpackDevMiddleware(compiler, {
  publicPath: webpackConfig.output.publicPath,
  contentBase: paths.project(config.get('dir_src')),
  hot: true,
  quiet: true,
  noInfo: false,
  lazy: false,
  stats: {
    colors: true
  },
  historyApiFallback: true
});
app.use(devMiddleware);

app.use((req, res, next) => {
  console.log('Final Request', req.url, req.method, req.accepts('html'));
  if (req.method === 'GET' && req.accepts('html')) {
    //res.sendFile(paths.src('index.html'), err => err && next());
    res.write(devMiddleware.fileSystem.readFileSync(paths.src('index.html')));
    res.send();
    next();
  } else next();
});
```

This results in the following error:

```
Error: no such file or directory
   at MemoryFileSystem.readFileSync (node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
   at build/webpack-dev-server.js:74:40
   at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (node_modules/express/lib/router/index.js:312:13)
   at node_modules/express/lib/router/index.js:280:7
   at Function.process_params (node_modules/express/lib/router/index.js:330:12)
   at next (node_modules/express/lib/router/index.js:271:10)
   at middleware (node_modules/webpack-hot-middleware/middleware.js:32:48)
   at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (node_modules/express/lib/router/index.js:312:13)
   at node_modules/express/lib/router/index.js:280:7
   at Function.process_params (node_modules/express/lib/router/index.js:330:12)
   at next (node_modules/express/lib/router/index.js:271:10)
   at node_modules/webpack-dev-middleware/middleware.js:166:12
   at continueBecauseBundleAvailible (node_modules/webpack-dev-middleware/middleware.js:58:5)
   at Array.forEach (native)
```

I confirmed the path is correct and could be read with: `fs.readFileSync(paths.src('index.html'))`. However it appears the upstream library may have an issue.

**Comment by patrickheeney** [comment]
If I am reading this right, it looks like you need to essentially [index the filesystem](https://github.com/webpack/memory-fs/blob/master/lib/MemoryFileSystem.js#L25) to populate it with data before being able to read from it? [We don't appear able to do this](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L32). How was this aspect designed to work?

**Comment by timsuchanek** [comment]
@patrickheeney Maybe [this example](https://github.com/gaearon/react-transform-boilerplate/blob/master/devServer.js) can help

**Comment by jonathaningram** [comment]
@timsuchanek unfortunately that example doesn't use `html-webpack-plugin` so `index.html` is actually just a plainly served file. The desired behaviour is that if `index.html` has the `o.htmlWebpackPlugin...` variables that it gets passed through `html-webpack-plugin` before being served.

**Comment by GreenGremlin** [comment]
I got this to work by rewriting all html requests to '/index.html', before the webpack middleware runs.

I'm using koa, but the solution should be similar for express.

``` javascript
const CONTENT_TYPE_HTML = 'text/html';

app.use(function* rewriteIndex(next) {
  if (this.accepts().toString().substr(0, CONTENT_TYPE_HTML.length) === CONTENT_TYPE_HTML) {
    this.request.url = '/index.html';
  }
  yield *next;
});

app.use(webpackDevMiddleware(compiler, {
...
```

**Comment by patrickheeney** [comment]
I ended up figuring this out: https://github.com/davezuko/react-redux-starter-kit/pull/202/files

Webpack Dev Server uses `connect-history-api-fallback` as a dependency. So after installing that and running it before the middleware, it handled things as expected.

**Comment by GreenGremlin** [comment]
Nice! It looks like that mw does basically the same thing, but with a few safety checks. Thanks!

**Comment by vesan** [comment]
@patrickheeney Cheers! This was the exact cure for my problems.

**Comment by Elyx0** [comment]
@patrickheeney Thanks for the link to your pull, it saved the day !

**Comment by GreenGremlin** [comment]
I wrote a more flexible alternative for koa, check it out. https://github.com/greengremlin/koa-mount-html

**Comment by halversondm** [comment]
This was very helpful, thank you.

**Comment by fourcolors** [comment]
super helpful thank you

**Comment by gordonk** [comment]
Thanks

**Comment by jiuxiaosheng** [comment]
Thanks, this saved my day

**Comment by konekoya** [comment]
@patrickheeney Thank you! You just made my day.

**Comment by benz2012** [comment]
Almost 2 years since @patrickheeney posted his solution, so I wasn't sure that I was having the exact same issue, but after including the `connect-history-api-fallback` as described in his PR, before the middleware, I am incredibly grateful that I found this issue thread.
