### ISSUE TITLE
In 3.7.1, `writeToDisk` option requires webpack 4.39.0

### ISSUE THREAD

**Issue by redbugz** [webpack/webpack-dev-middleware#463]
* Operating System:
* Node Version: 10.16.2
* NPM Version: 6.11.2
* webpack Version: 4.29.6
* webpack-dev-middleware Version: 3.7.1

### Expected Behavior

`writeToDisk` option outputs files to disk

### Actual Behavior

silent failure, no files are written

### How Do We Reproduce?

We are on a slightly out of date fork of CRA, which is pinned to webpack 4.29.6.
CRA just updated to webpack 4.39.0 25 days ago

The new implementation of the `writeToDisk` option released in 3.7.1 uses a new webpack hook released in 4.39.0, `assetEmitted`
https://webpack.js.org/api/compiler-hooks/#assetemitted

This error was silent for us, because `quiet` was set to true. Setting `quiet` to false, resulted in this stack trace:
```
✖ ｢wdm｣: TypeError: Cannot read property 'tapAsync' of undefined
    at compiler.hooks.emit.tap (/Users/me/dev/sandbox/newapp/node_modules/webpack-dev-middleware/lib/fs.js:18:37)
    at _next1 (eval at create (/Users/me/dev/sandbox/newapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at _err1 (eval at create (/Users/me/dev/sandbox/newapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at emitHtmlPromise.then (/Users/me/dev/sandbox/newapp/node_modules/html-webpack-plugin/index.js:313:11)
```

We are in the process of updating our CRA fork to resolve this issue.

It would be nice to at least update the release notes to note the dependency requirement, or make the error appear even when quiet is true.

**Comment by evilebottnawi** [comment]
Oh, I would advise using the latest version of `webpack`, sometimes this happens, we try to avoid this, but some problems can be solved in other way. Also some plugins potentially can have some problems.

Reverting PR broken compatibility with webpack and we wan't this. Error logging impossible in this situation. Only solution - update webpack, sorry

**Comment by zetlen** [comment]
Since this package now requires Webpack 4.39, it would help for you to indicate that by updating the [peerDependency you have  in package.json](https://github.com/webpack/webpack-dev-middleware/blob/master/package.json#L31).

**Comment by redbugz** [comment]
After updating webpack, things are working again.
