### ISSUE TITLE
`writeToDisk` leads the compile time keep increasing.

### ISSUE THREAD

**Issue by unbug** [webpack/webpack-dev-middleware#469]
* Operating System: MacOS 10.15
* Node Version: v10.15.2
* NPM Version: 6.11.3
* webpack Version: 4.40.2
* webpack-dev-middleware Version: 3.8.1

### Expected Behavior
The compile-time should not keep increasing.

### Actual Behavior

The compile-time keep increasing, and log shows duplicate write to disk keep increasing.
e.g. First compile:
```
[16:31:46] ➤ ｢wdm｣: Asset written to disk: app/js/app.js
writeToDisk
[16:31:46] ➤ ｢wdm｣: Asset written to disk: app/js/app.js.map
writeToDisk
[16:31:46] ➤ ｢wdm｣: Asset written to disk: app/js/app.js
[16:31:46] ➤ ｢wdm｣: Asset written to disk: app/js/app.js.map
```
Third compile:
```
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js
writeToDisk
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js.map
writeToDisk
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js
writeToDisk
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js.map
writeToDisk
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js
writeToDisk
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js.map
writeToDisk
[16:33:01] ➤ ｢wdm｣: Asset written to disk: app/js/app.js.map
```

### Code

```js
          webpackDevMiddleware(compiler, {
            publicPath: webpackConfig.dev.output.publicPath,
            stats: { colors: true },
            writeToDisk: true,
            logTime: true,
            logLevel: 'debug'
          }),
```

### How Do We Reproduce?
I think to change the `logLevel` to `debug` will see the log for any project.

**Comment by evilebottnawi** [comment]
Thanks for issue :+1:

**Comment by unbug** [comment]
Looks like the `compiler.hooks.assetEmitted.tapAsync('WebpackDevMiddleware', ....` got duplicate called for each compile.
https://github.com/webpack/webpack-dev-middleware/blob/master/lib/fs.js#L18

**Comment by evilebottnawi** [comment]
@unbug yep, in my todo, will be fixed in near future

**Comment by evilebottnawi** [comment]
@unbug hm, can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
No need, find memory leak, WIP

**Comment by JulienPradet** [comment]
Hi @evilebottnawi 

Is the memory leak you are talking about is that the first hook creates a new one on each pass, leading to never GC the `compilation` object?

I was myself investigating issues with webpack-dev-middleware and was about to submit a PR about this. (found it thanks to this clue: https://github.com/webpack/webpack/issues/6929#issuecomment-388717678). But I'm wondering if that would be useful to you reading your last comment.

**Comment by evilebottnawi** [comment]
@JulienPradet yes, here same bug, on each compilation we create new callback on hook, so after 100 compilations we have 100 callbacks. Here memory leak. I added this to my todo list, try to throw warning on webpack side for webpack@5, it is allow catch all these cases.

**Comment by JulienPradet** [comment]
That would be awesome!
If you need help landing the fix in webpack-dev-middleware (for example if you don't have time), I would be happy to help :)

**Comment by evilebottnawi** [comment]
@JulienPradet thanks, i am working on this right now, so I think there’s no point in working together on this, anyway thanks for feedback
