### ISSUE TITLE
Support http combo

### ISSUE THREAD

**Issue by sfger** [webpack/webpack-dev-middleware#48]
Hi，
   Nice work！Can this middleware also support http combo Handler，e.g:

http://www.test.com/path/to/file??a.js,b.js
Send only one request same as:
http://www.test.com/path/to/file/a.js
+
http://www.test.com/path/to/file/b.js

http://www.test.com/path/to/file??a/a1.js,b/b1.js
as previous:
http://www.test.com/path/to/file/a/a1.js
+
http://www.test.com/path/to/file/b/b1.js

Thanks

**Comment by sokra** [comment]
no. why? there is propably also a middleware for this...
