### ISSUE TITLE
Documentation does not mention that emitted images (in particular .jpg and .png) will be served from memory file system with (no|incorrect) mime types

### ISSUE THREAD

**Issue by Media-Evil** [webpack/webpack-dev-middleware#491]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The middleware does not serve bundled images (tested .jpg, . png) from memory file system with correct mime-types.
### Your Proposal for Changes
My proposal is to **serve** bundled (processed) assets such as images with correct mime types

If this is unintended behaviour, please let me know and I will provide additional details. If it **is** an expected behaviour, please mention this in documentation.

If neither of these, fell free to close the issue.

**Comment by evilebottnawi** [comment]
> The middleware does not serve bundled images (tested .jpg, . png) from memory file system with correct mime-types.

Please provide example

**Comment by Media-Evil** [comment]
[Here](https://drive.google.com/open?id=1NyDfXg7zescYapU7eT2pSLqrwqpEL6vY) I removed (almost) all clutter. The problem persists. Network tab shows that file is actually sent though with incorrect mime-type.

**Comment by Media-Evil** [comment]
P.S. `cd` to the `dev` folder prior to running any scripts

**Comment by evilebottnawi** [comment]
We use `mimes` package and he provide mime types, looks something wrong in your code. I will look on this in near future.

**Comment by Media-Evil** [comment]
I re-organized my code and issue disappeared. I'm closing the issue as irrelevant.

Some conclusions:
- if you see something like `../../../../outerModule.js` way too often, something is definitely wrong with your project architecture
- the first argument in express's `app.use` specifies the endpoint the user requests
- the second argument defines what folder to serve when that endpoint is requested

I apologize for false report.
