### ISSUE TITLE
FOUC when using HMR with CSS source-map.

### ISSUE THREAD

**Issue by danauclair** [webpack/webpack-dev-middleware#51]
When I use hot-module-reloading with sourcemaps I see what used to be inline style tags in the head turn into link tags with blob: hrefs. For some reason this change is causing a flash of unstyled content before the link tags are injected into the head.

Are there any workarounds for this?

**Comment by tizmagik** [comment]
For development I think this is expected. As long as your production build doesn't suffer from FOUC, I think it's the trade-off for HMR.

**Comment by SpaceK33z** [comment]
As said above, when working with HMR this is a trade-off. A workaround for this would be to disable HMR, and use live-reloading.
