### ISSUE TITLE
writeToDisk:true exhausts heap quickly on large projects

### ISSUE THREAD

**Issue by SunriseFox** [webpack/webpack-dev-middleware#527]
- Operating System: any
- Node Version: any
- NPM Version: any
- webpack Version: < 5
- webpack-dev-middleware Version: latest

### Expected Behavior

When `writeToDisk` is set to true, no memory leaks between compilations.

### Actual Behavior

Memory leak exhausts heap quickly on large projects.

### Code

```js
// webpack.config.js
devServer: {
    writeToDisk: true
}
```

### How Do We Reproduce?

Here is the cause: 
https://github.com/webpack/webpack-dev-middleware/blob/961ba4c8657baed400431803ead10166d8f42fc6/lib/utils/setupWriteToDisk.js#L13-L43

This assetEmitted hook holds a reference of `compilation` object and never releases.
https://github.com/webpack/webpack-dev-middleware/blob/961ba4c8657baed400431803ead10166d8f42fc6/lib/utils/setupWriteToDisk.js#L43

Whenever a watch-reload happens, *emit* hook is triggered so a new *assetEmitted* hook is installed, and thus a new instance of `compilation` object is held and never releases.

`compilation` holds all output contents. On a large project where the generated codes are larger than 100MB, this could quickly exhaust heap memory and crash webpack.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, looks memory leak in some plugins

**Comment by SunriseFox** [comment]
Ah, sorry. `compiler.hasWebpackDevMiddlewareAssetEmittedCallback` introduced in 3.7.2 should have fixed this. (but it will still hold one oldest compilation object... I found this issue in 3.7.1, then I rechecked it in 3.7.2 and still found a previous compilation object when I did memory profiling... At least it won't crash the application again).

Sorry again.
