### ISSUE TITLE
How to use this module with HapiJS ecosystem?

### ISSUE THREAD

**Issue by bboysathish** [webpack/webpack-dev-middleware#57]
Can you provide an example of how to use this plugin with HapiJS ecosystem?

Below is the configuration i used with Hapi. Thats all i have configured. When i open my server @ `localhost:3000` i got an error as below screen shot

![webpack-dev-middleware](https://cloud.githubusercontent.com/assets/8023447/12371037/20d01384-bc4c-11e5-8d72-797fcc9e0931.PNG)

```js

'use strict';

/* global __dirname */

const Webpack = require('webpack');
const Path = require('path');

module.exports = {
  'devtool': 'eval',
  'entry': [
    'webpack-hot-middleware/client?path=/__webpack_hmr&reload=true',
    './app/main.js'
  ],
  'output':{
    'path': __dirname + '/public/',
    'filename' : 'bundle.js',
    'publicPath' : '/'
  },
  'plugins':[
    new Webpack.optimize.OccurenceOrderPlugin(),
    new Webpack.HotModuleReplacementPlugin(),
    new Webpack.NoErrorsPlugin()
  ],
  'module': {
    'loaders':[
      {
        'test': /\.js$/,
        'include': Path.join(__dirname, 'app'),
        'loader': 'babel-loader'
      }
    ]
  }
};
```

**Comment by j** [comment]
:+1:

**Comment by arb** [comment]
You can't. This module specifically hooks into the Express request lifecycle and middleware system. Check out https://www.npmjs.com/package/hapi-webpack-plugin for a possible hapi-compatible replacement.

**Comment by bboysathish** [comment]
@arb Thanks. Will look into it.
