### ISSUE TITLE
Server Side Rendering section seems innaccurate

### ISSUE THREAD

**Issue by marr** [webpack/webpack-dev-middleware#593]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
Looking through the Server Side Rendering example, there is a section that expects `res.locals.webpack` to exist. When I inspect that on my server, it is _undefined_. There is a `res.locals.webpackStats` set, but it doesn't seem to line up with the example. 

### Your Proposal for Changes
Is it possible to update this example with the latest (stable) from webpack?

**Comment by evilebottnawi** [comment]
It is documentation for next major release, please look here https://github.com/webpack/webpack-dev-middleware/blob/master/package.json#L3, you can find old documentation here https://github.com/webpack/webpack-dev-middleware/tree/v3.7.2#server-side-rendering (using tags).

The migration dragged on a bit, so a problem appeared, I hope we will fix it soon, and the master will be actual
