### ISSUE TITLE
log.debug is not a function...

### ISSUE THREAD

**Issue by abdullah-bl** [webpack/webpack-dev-middleware#598]
- Operating System: macos 10.15.3
- Node Version: v13.8.0
- NPM Version: 6.14.2
- webpack Version: 4.42.0
- webpack-dev-middleware Version: 3.7.2

### Error
```js
log.debug is not a function
TypeError: log.debug is not a function
    at ../node_modules/webpack-dev-middleware/lib/fs.js:75:21
    at ../node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:154:23)
error Command failed with exit code 1.
```

#### This is what i did to fix this problem..
I opened webpack-dev-middleware/lib/fs.js file and added this code
```js
// line 8
const getLogger = require('webpack-log');
const { colors } = getLogger
```

```js
// line 63 
//  const { log } = context;
const log = getLogger('webpack-logger');
```

**Comment by evilebottnawi** [comment]
Do not use `webpack-logger` or `webpack-log`, webpack has own built-on logger
