### ISSUE TITLE
4.0.0-rc.1 is incompatible with Fastify

### ISSUE THREAD

**Issue by artemirq** [webpack/webpack-dev-middleware#602]
- Node Version: v13.11.0
- NPM Version: 6.13.7
- webpack Version: 4.42.0
- webpack-dev-middleware Version: 4.0.0-rc.1

### Actual Behavior

When I trying to access application from browser, build is failing with error `TypeError: res.get is not a function`. In previous version, 3.7.2 it's not happened

I checked that error is happening in new version on [this code line](https://github.com/webpack/webpack-dev-middleware/blob/master/src/middleware.js#L59)

### Code

```js
const webpack = require('webpack');
const middleware = require('webpack-dev-middleware').default;
const path = require('path');
const compiler = webpack({
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
});
const fastify = require('fastify');
const app = fastify();

app.use(
  middleware(compiler)
);

app.listen(3000, () => console.log('Example app listening on port 3000!'));
```

### How Do We Reproduce?

1. Bootstrap project from scratch with `npm init`
2. Run `npm i webpack webpack-dev-middleware@next fastify`
3. Create file `src/index.js` and write something valid
4. Place the code above to `./run-webpack.js`
5. Run `node run-webpack.js`
6. Try to access http://localhost:3000/main.js in your browser

### Notes

- I also checked that my example works with Express normally, but with Fastify not

**Comment by evilebottnawi** [comment]
We never will be compatibility with `fastify`, we support only `express` officialy

**Comment by artemirq** [comment]
Supporting availability to use with two frameworks is bad idea, agreed

**Comment by evilebottnawi** [comment]
In theory we can implement it, but we need improve tests, let's mark it is feature

**Comment by pearofducks** [comment]
@artemirq (and any others who find this) - this is working fine with the lastest fastify and [fastify-express](https://github.com/fastify/fastify-express) as the middleware provider (instead of middie)

**Comment by evilebottnawi** [comment]
@pearofducks yep, can you send a PR to docs how to use it with fastify?

**Comment by WraithKenny** [comment]
This is also breaking with `browser-sync` where before it was working fine. (In my setup, I have a Gulp file which runs a BrowserSync server, which loads the middleware.) It's the same issue here; should I make a new issue, or just leave this note?

**Comment by evilebottnawi** [comment]
we never supports faslity, please look at README, we write how you should use it with fastify

**Comment by gpoitch** [comment]
4.0 breaks compatibility with vanilla node http too.

**Comment by evilebottnawi** [comment]
PR exists https://github.com/webpack/webpack-dev-middleware/pull/747, we never support is too, I think we fix it in near patch release

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-dev-middleware/issues/945, hope we will improve this in near future
