### ISSUE TITLE
Add webpack-bot to trigger automatic creation of issue in documentation repo

### ISSUE THREAD

**Issue by jeffin143** [webpack/webpack-dev-middleware#613]
### Feature Proposal

Add webpack-bot to trigger the issue creation if check box is checked by a maintainer 
* [ ]  This needs to be documented (issue in webpack/webpack.js.org will be filed when merged)

https://github.com/webpack-bot
https://github.com/open-bot/open-bot

### Feature Use Case

Will help to sync the documentation repo with the changes 

cc @sokra

**Comment by jeffin143** [comment]
If webpack-bot has permission to all repo then it would automatically read the .yaml files and if not then we just have to enable it for this particular repo

**Comment by alexander-akait** [comment]
Clsoe in favor https://github.com/webpack/webpack-dev-middleware/pull/612#issuecomment-1524100016
