### ISSUE TITLE
Warnings and Errors only

### ISSUE THREAD

**Issue by arb** [webpack/webpack-dev-middleware#64]
How can I use this middleware and only get logging information about errors and warnings only, not full stats?

**Comment by SpaceK33z** [comment]
Did you read the readme?

**Comment by bendytree** [comment]
These days `noInfo` `quiet` and `stats` have been replaced by [infrastructureLogging][1] in the root of your Webpack config:

    // webpack.config.js
    ...
    infrastructureLogging: {
      level: 'error',
    },


  [1]: https://webpack.js.org/configuration/other-options/#level
