### ISSUE TITLE
Errors after server starts when running from different repo than webpack.config

### ISSUE THREAD

**Issue by bdsanfelippo** [webpack/webpack-dev-middleware#645]
- Operating System: Windows 10
- Node Version: v12.16.1
- NPM Version: 6.13.4
- webpack Version: 4.43.0
- webpack-dev-middleware Version: 3.7.2

### Expected Behavior

The express server starts up with no errors and serves up the webpack bundle properly.

### Actual Behavior

The server starts up and listens on its port but then I have tons of errors related to not being able to resolve libraries.

The first of the many errors listed is as such:

```console
ERROR in ./node_modules/worker-farm/lib/fork.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\csanfeb\git\Cloud\problem\standalone\node_modules\worker-farm\lib'
 @ ./node_modules/worker-farm/lib/fork.js 3:21-45
 @ ./node_modules/worker-farm/lib/farm.js
 @ ./node_modules/worker-farm/lib/index.js
 @ ./node_modules/terser-webpack-plugin/dist/TaskRunner.js
 @ ./node_modules/terser-webpack-plugin/dist/index.js
 @ ./node_modules/terser-webpack-plugin/dist/cjs.js
 @ (webpack)/lib/WebpackOptionsDefaulter.js
 @ (webpack)/lib/webpack.js
 @ ./src/index.ts
```

### Code

I created a standalone repo here:
https://github.com/bdsanfelippo/problem

I should note that I am creating a library using webpack and within my library's repo, I'm creating a standalone test. The standalone test provides the server. 

### How Do We Reproduce?

clone the repo:
https://github.com/bdsanfelippo/problem

npm install

then cd into "standalone" and run npm install and then npm start

**Comment by evilebottnawi** [comment]
Can you update `terser-webpack-plugin` to latest version?

**Comment by bdsanfelippo** [comment]
How would I do that? I'm not using terser-webpack-plugin directly.

**Comment by bdsanfelippo** [comment]
I manually updated the terser-webpack-plugin that webpack was using and it did not solve the problem.

**Comment by evilebottnawi** [comment]
Interesting problem :smile: To be honestly no problems, just add:

**webpack.config.js**

```
  entry: "./src/index.ts",
  context: path.resolve(__dirname),
  mode: "development",
```

Default `context` is `process.cwd()` (https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L72), so webpack try to bundle `standalone/src/index.ts` instead `src/index.js` (in `standalone/dist/index.js`), alternative solution to use absolute path to `entry`.

Also you need configuration `publicPath` to `publicPath: "/library/"`, but you can do it in runtime, just modify `publicPath` in `standalone/src/index.ts`.

**Comment by bdsanfelippo** [comment]
Thanks! That worked for my example application. In my actual application I had to make one additional change for the babel-loader:

```javascript
    rules: [
      {
        test: /\.(ts|js)$/,
        exclude: /node_modules/,
        loader: "babel-loader",
        options: {
          cwd: path.resolve(__dirname),
        },
      },
```
