### ISSUE TITLE
Access 0.0.0.0 externally fails using latest webpack

### ISSUE THREAD

**Issue by hiradyazdan** [webpack/webpack-dev-middleware#651]
- Operating System: `macOS`
- Node Version: `13.14`
- NPM Version: `6.14.5`
- webpack Version: `4.43`
- webpack-dev-middleware Version: `3.7.2`

### Expected Behavior

static assets should be accessed/loaded externally as they're locally

### Actual Behavior

static assets aren't loaded as expected with this error:

`Failed to load resource: Could not connect to the server.`

### Code

webpack.config.js

```js
const host = '0.0.0.0'
const port = 3000
const config = {
	output: {
		publicPath: `http://${host}:${port}/`
		...
	},
	...
}
```

server.dev.js (using expressjs):
```js
const devMiddlewareOptions = {
	publicPath: config.output.publicPath
}

app.use(webpackDevMiddleware(compiler, devMiddlewareOptions))
	.use(webpackHotMiddleware(compiler))
...
```

### How Do We Reproduce?

If the dev server (custom using the dev middleware) is started listening to `0.0.0.0`, accessing the server externally (i.e. on a remote device) with the machine's ip address will provide this result. Note that the html file which is served via the express itself loads fine, but the part that dev middleware handles fails, This used to work on earlier webpack versions I believe.

**Comment by evilebottnawi** [comment]
@hiradyazdan Can't reproduce, can you create reproducible test repo?

**Comment by hiradyazdan** [comment]
@evilebottnawi it didn't even take a minute for you to reproduce it?! you just read my issue!

**Comment by evilebottnawi** [comment]
@hiradyazdan I read your issue, works fine with `0.0.0.0` locally

**Comment by hiradyazdan** [comment]
locally?! you clearly didn't read it :D

**Comment by evilebottnawi** [comment]
@hiradyazdan please change the tone of communication, otherwise I will close your problem without an answer, please create reproducible test repo

**Comment by hiradyazdan** [comment]
you have been offended for just reminding you that you even missed out even reading my issue, set aside reproducing it?!!! oh I'm sorry for that then! such a child! go on close the issue so people can know how mature you are!

**Comment by evilebottnawi** [comment]
@hiradyazdan if you change your mind and stop communicating with me in that tone, just do what I asked and I will help you

**Comment by evilebottnawi** [comment]
I don't know how you run your server, so the `publicPath` can have any value, if you run it locally, just set `publicPath: "/"` if you proxy (that I do not know because you refuse to provide an example) you need set on right way, without minimum example I can't say right value of `publicPath`

**Comment by hiradyazdan** [comment]
webpack hmr for webpack 1.x used to need the full path than relative for `publicPath` so it can work on remote devices as well, somehow it was resolving the host from `0.0.0.0`. The relative path `/` now works for both dev and hot middleware. This has changed I think. Thanks.
