### ISSUE TITLE
Server-Side Rendering Option

### ISSUE THREAD

**Issue by jayair** [webpack/webpack-dev-middleware#653]
Hi all,

Thanks for the great plugin. I'm using the server-side rendering option for an upcoming project. And I have a question about this:

> Note: this feature is experimental and may be removed or changed completely in the future.

I would like the middleware to be queued until the chunks are generated and then get access those chunks.

Is there a recommended way to do this moving forward? Maybe there's an alternative option that I'm not aware of.

Thank you!

**Comment by evilebottnawi** [comment]
No, you should use Server-Side Rendering Option, if we remove it we will provide alternative way to solve a problem, so feel free to use it without problems
