### ISSUE TITLE
Please reinstate lazy option in v4

### ISSUE THREAD

**Issue by karlhepler** [webpack/webpack-dev-middleware#662]
- Operating System: n/a
- Node Version: n/a
- NPM Version: n/a
- webpack Version: n/a
- webpack-dev-middleware Version: n/a

### Feature Proposal
Please reinstate lazy option in v4.

### Feature Use Case
I noticed that one of the breaking changes included in 4.0.0-rc.0 is "the lazy option was removed without replacement". This option is essential for my build system.

**Comment by evilebottnawi** [comment]
It is impossible due architecture, `lazy` never works fine, sorry

**Comment by evilebottnawi** [comment]
Here https://github.com/webpack/webpack-dev-middleware/issues/622 more infromation
