### ISSUE TITLE
Test issue: one test file affecting following test when webpack@next compilation not completed

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-middleware#682]
- Operating System: CI Environment (Windows, Linux, Mac)
- Node Version: Any
- webpack Version: v5 (webpack@next)
- webpack-dev-middleware Version: v4

### Expected Behavior

Different test files with different webpack compilations should not affect one another

### Actual Behavior

See: https://github.com/webpack/webpack-dev-middleware/pull/674#discussion_r451820369

The previous test file: `api.test.js` had a test with a webpack compilation that was not being completed before the test file finished. In `api.test.js`, `jest.spyOn` is applied to the `done` hook of compilations. The problem was that the very first test of the next test file being run (`getFilenameFromUrl.test.js`) was not getting its `done` hook called, making the test fail. This problem was solved in the test files by forcing `api.test.js` to wait for compilation completion.

This problem could be caused by jest itself, or possibly by how webpack@next hooks are handled.

I could not reproduce the problem locally. It consistently happened on CI.

### How Do We Reproduce?

See: https://github.com/webpack/webpack-dev-middleware/pull/674#discussion_r451820369

**Comment by alexander-akait** [comment]
I think we can close it, because we rewrite tests, anyway if it happens again I will reopen this
