### ISSUE TITLE
Ignore ? query parameter on url

### ISSUE THREAD

**Issue by gunta** [webpack/webpack-dev-middleware#7]
`?` query parameter is not ignored so it results in a **404 error**.

Example:
[Font Awesome Icons CSS](http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css)

``` css
src: url('../fonts/fontawesome-webfont.eot?v=4.0.3')
```

**Comment by tsofist** [comment]
`html-webpack-plugin` provide `hash` option for cache busting but dev-middleware not supported this case 😢 

```
Request URL: http://localhost:12160/bundle.js?0d937badc5d6699554df
Request Method: GET
Status Code: 404 Not Found
```
```
Request URL: http://localhost:12160/bundle.js
Request Method: GET
Status Code: 200 OK
```
