### ISSUE TITLE
Refactoring test code

### ISSUE THREAD

**Issue by hiroppy** [webpack/webpack-dev-middleware#713]
- Operating System: N/A
- Node Version: N/A
- NPM Version: N/A
- webpack Version: N/A
- webpack-dev-middleware Version: N/A

### Modification Proposal

Currently, tests/middleware.test.js has more than 3600 lines. It's hard to read because test code has many `{}`. I want to divide it.

**Comment by evilebottnawi** [comment]
Divide on that?

**Comment by hiroppy** [comment]
yes

**Comment by evilebottnawi** [comment]
We have multiple `describe` sections, and we can move each section to own file

**Comment by hiroppy** [comment]
Thanks, I want to divide like that.

**Comment by Cronus1007** [comment]
@evilebottnawi  Sir whether someone is working on this issue or shall I take this issue for now.

**Comment by evilebottnawi** [comment]
You can pick it after stable release (today)

**Comment by Cronus1007** [comment]
@evilebottnawi  Sir is the stable release ready?

**Comment by evilebottnawi** [comment]
Yes

**Comment by Cronus1007** [comment]
@evilebottnawi  I think that the linked PR will close this issue. Have a look 
#753

**Comment by alexander-akait** [comment]
I want to close this issue after latest refactor, output tests was moved to separate file, anyway we can improve this better in future, but I think we don't need issue for this, just send a PR
