### ISSUE TITLE
webpack 5 is not included in peerDependencies of v3

### ISSUE THREAD

**Issue by ylemkimon** [webpack/webpack-dev-middleware#725]
- webpack Version: 5
- webpack-dev-middleware Version: 3.7.2

### Expected Behavior
webpack v5 and webpack-cli v4 are compatible with webpack-dev-middleware v3 and webpack-dev-server v3, so peerDependencies of webpack-dev-middleware v3 should include webpack v5.

### Actual Behavior
webpack v5 is not included in peerDependencies of webpack-dev-middleware v3:

https://github.com/webpack/webpack-dev-middleware/blob/68ae47b1838dbd08f83b7e10099a0eaebdc311e1/package.json#L30-L32

**Comment by evilebottnawi** [comment]
Fixed in master

**Comment by evilebottnawi** [comment]
We will do release when the work will be completed, hope this week

**Comment by ylemkimon** [comment]
@evilebottnawi Would it be possible to backport changes into v3? From what I've tried, v3 seems to be compatible with webpack v5.

**Comment by evilebottnawi** [comment]
No, because a lot of incompatibilities, why you need it? Just wait the release, right now it is just the waring
