### ISSUE TITLE
ETag support

### ISSUE THREAD

**Issue by privatenumber** [webpack/webpack-dev-middleware#738]
- Operating System: Mac
- Node Version: v12.16.2
- NPM Version: v6.14.4
- webpack Version: v4.44.2
- webpack-dev-middleware Version: v3.7.2

### Feature Proposal
Add Etags to assets to prevent re-loading unchanged assets.

### Feature Use Case
Faster page loads by eliminating loads for large files that are unchanged.

This optimization is used in other dev bundlers like [Vite](https://github.com/vitejs/vite) and [Snowpack](https://www.snowpack.dev).

### Other
I implemented this via wrapper [in a separate package](https://github.com/privatenumber/vue-just-ssr/pull/7/files#diff-3979a5e82c57a8459c6e8316962f32833b811d7ca03362e3e3c4319211454a56R105).

Happy to open a PR if the issue is accepted.

**Comment by evilebottnawi** [comment]
@privatenumber Yes, PR welcome

**Comment by privatenumber** [comment]
Is v3 still actively maintained? I didn't see a separate dev branch for it but I'm personally using v3 so I would like to add it there so that I can use it.

If not, I can add it to v4.

**Comment by evilebottnawi** [comment]
Yes, let's add to v4, I will do release in near future (today/tomorrow), also v4 supports webpack@4 and webpack@5
