### ISSUE TITLE
NPM Warnings with Webpack 5

### ISSUE THREAD

**Issue by hayesmaker** [webpack/webpack-dev-middleware#741]
$ node --version
v12.18.2

$ npm --version
6.14.5

    "webpack": "^5.1.3",
    "webpack-bundle-analyzer": "^3.9.0",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"

### Expected Behavior

should run without warnings when using webpack 5

### Actual Behavior

npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none
 is installed. You must install peer dependencies yourself.

### Code

```js
mode: 'development',
  entry: './src/pixi-main.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  devServer: {
    overlay: true,
    hot: false,
    hotOnly: false,
    open: true,
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000
  },
  devtool: 'eval-cheap-source-map',
  plugins: [
    //new BundleAnalyzerPlugin()
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/env']
          }
        }
      }
    ]
  }
```

```js
// additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?

configure and run a project with webpack-dev-server

**Comment by evilebottnawi** [comment]
Fixed in master

**Comment by hayesmaker** [comment]
ok thanks - time to pester webpack-dev-server to update
