### ISSUE TITLE
Enhancement of package.json 

### ISSUE THREAD

**Issue by Cronus1007** [webpack/webpack-dev-middleware#752]
As per the convenience of a developer  we should also add "lint:fix" script in our package.json which will ease the work of a developer for removing the linitng errors.

### Expected Behavior / Situation
By adding this script fixing of the linting errors would be an easy task.
### Actual Behavior / Situation
If the global configuration files and local configuration files of the prettier collide so there is a need to add the script in order to fix the linting errors.
### Modification Proposal
Ease the development proess of the dev-middleware

**Comment by Cronus1007** [comment]
cc @evilebottnawi

**Comment by evilebottnawi** [comment]
No need to open new issues for this, feel free to send a PR
