### ISSUE TITLE
On Windows when filename contains '..' the file resolution fails

### ISSUE THREAD

**Issue by reda-alaoui** [webpack/webpack-dev-middleware#755]
- Operating System: Windows 10
- Node Version: 12.19.0
- NPM Version: 6.14.8
- webpack Version: 4.44.1
- webpack-dev-middleware Version: 3.7.2

### Expected Behavior

When filename contains '..' the file resolution should work.

### Actual Behavior

On Windows only (works on Linux), when filename contains '..' the file resolution does not find the file which leads to an http 404.

### Code

Angular CLI 10.2.0 code

### How Do We Reproduce?

Generate an Angular app, then in `angular.json` set `option` index to:
```json
"index": {
              "input": "index.html",
              "output": "../index.html"
            }
```

### Fix proposal

The fix is really easy => https://github.com/Cosium/webpack-dev-middleware/commit/c4ac7965a69f42100ec01cc21e820841409527a2

**Comment by evilebottnawi** [comment]
> webpack-dev-middleware Version: 3.7.2

update webpack-dev-middleware to latest version, fixed in master

**Comment by reda-alaoui** [comment]
I guess there are breaking changes between version 3 and 4?
If so, would it be possible to fix version 3?

**Comment by evilebottnawi** [comment]
v3 is deprecated and contains a lot of other bugs, my recommendation is migrate on v4, I am really afraid what fixing one bug we create regressions for other
