### ISSUE TITLE
no `stats` option property anymore?

### ISSUE THREAD

**Issue by HomyeeKing** [webpack/webpack-dev-middleware#757]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [StackOverflow](https://stackoverflow.com/questions/tagged/webpack)
or [the Webpack Gitter](https://gitter.im/webpack/webpack) instead.

I want to clean the console info , the [webpack official](https://webpack.js.org/configuration/stats/#root) says: 

> For webpack-dev-middleware, this property needs to be in the webpack-dev-middleware's options object.

I wonder  if this middleware  has `stats` property?

**Comment by evilebottnawi** [comment]
No `stats`, it was removed in favor `stats` inside configuration, you can use `module.exports = (env) => { stats: env.myCustomStatsValue : 'minimum' }`
