### ISSUE TITLE
add BrowserSync support

### ISSUE THREAD

**Issue by dthpth** [webpack/webpack-dev-middleware#758]
do you have plans to add a support of BrowserSync server?

right now it thows `TypeError: res.get is not a function` (as mentioned in #652)
I've made a minimal example to reproduce that issue: https://github.com/dthpth/webpack-dev-middleware-bs-issue

**Comment by evilebottnawi** [comment]
No, we don't have plans, we never supports `browser-sync`, but if you want you can do it, we already have PR for this https://github.com/webpack/webpack-dev-middleware/pull/747

**Comment by evilebottnawi** [comment]
Fixed in master, release will be tomorrow, I think we need add tests to avoid regressions in future

**Comment by evilebottnawi** [comment]
Can you try https://github.com/webpack/webpack-dev-middleware/releases/tag/v4.0.1?

**Comment by evilebottnawi** [comment]
We have compatibility with connect

**Comment by dthpth** [comment]
works perfectly, thank you!
