### ISSUE TITLE
Outdated version on NPM ?

### ISSUE THREAD

**Issue by websilone** [webpack/webpack-dev-middleware#76]
Hi,

it looks like the version installed via NPM is not the same as the one visible here in the repo.
Especially, the waitUntilValid function is not referenced anywhere.

Any clue about that ?
Thank you.

**Comment by dcousineau** [comment]
:+1: Currently checking out the specific commit hash as waitUntilValid is needed for me, would appreciate a version tick and publish for this :)

**Comment by bluedaniel** [comment]
@sokra can we publish to npm again? Thanks

**Comment by ctrlplusb** [comment]
I had this same problem.  Confused the hell out of me for a while!

As a temporary workaround I have install the packaged directly from github. 

i.e.

```
npm i git+https://git@github.com/webpack/webpack-dev-middleware --save-dev
```

**Comment by sokra** [comment]
Sorry, missed that... Too many repos....

**Comment by SpaceK33z** [comment]
Looks like that's fixed now.
