### ISSUE TITLE
the webpack-dev-middleware looks like is not supportting the property of stats

### ISSUE THREAD

**Issue by lanmch** [webpack/webpack-dev-middleware#765]
- Operating System: MacOS 10.15.5
- Node Version: 12.18.1
- NPM Version: 6.14.5
- webpack Version: 5.3.2
- webpack-dev-middleware Version: 4.0.2

### Expected Behavior

i hope to use the property of stats to reduce the unnecessary log info in my terminal. When i use the webpack4 and the webpack-dev-middleware 3.7.2, the ‘stats' can be used rightly.

### Actual Behavior
There is still all of the log info appear.
And i found the code of node_modules about the 'webpack-dev-middleware', i cant find this property. But i find some usage in the webpack site about it.
The website is 'https://webpack.js.org/configuration/dev-server/#devserverstats-'

### Code

```js
app.use(webpackDevMiddleware(compiler));
      webpackDevMiddleware(compiler).waitUntilValid(() => {
        const listenPort = port || 8001;
        app.listen(listenPort, () => { console.log(`[wdm] Webpack server listening on port ${listenPort}!\n`) })
      });
```

```js
[webpack-dev-middleware] assets by chunk 2.58 MiB (name: index)
<i>   asset index.js 2.57 MiB [emitted] (name: index)
<i>   asset index.css 12.8 KiB [emitted] (name: index)
<i> assets by path img/*.png 13.7 KiB
<i>   asset img/logo.png 11.3 KiB [emitted] (auxiliary name: index)
<i>   asset img/test.png 2.38 KiB [emitted] (auxiliary name: index)
<i> asset index.html 247 KiB [emitted]
<i> Entrypoint index 2.58 MiB (13.7 KiB) = index.css 12.8 KiB index.js 2.57 MiB 2 auxiliary assets
<i> runtime modules 1.61 KiB 8 modules
<i> modules by path ./node_modules/ 613 KiB 140 modules
<i> modules by path ./src/ 57 KiB (javascript) 4.17 KiB (css/mini-extract)
<i>   modules by path ./src/pages/index/ 34.6 KiB (javascript) 4.17 KiB (css/mini-extract)
<i>     cacheable modules 34.6 KiB 23 modules
<i>     css modules 4.17 KiB 5 modules
<i>   modules by path ./src/business/ 13.9 KiB 7 modules
<i>   ./src/containers/page-container.tsx 5.37 KiB [built] [code generated]
<i>   ./src/assets/global/global.ts 1.96 KiB [built] [code generated]
<i>   ./src/middlewares/index.ts 1.21 KiB [built] [code generated]
<i> external "React" 42 bytes [built] [code generated]
<i> external "ReactDOM" 42 bytes [built] [code generated]
<i> webpack 5.3.2 compiled successfully in 5554 ms
<i> [webpack-dev-middleware] Compiled successfully.
```

### How Do We Reproduce?
if hope to add this property like the previous versions, in my team, we really need it! thx!
Expecting a reply

**Comment by ylemkimon** [comment]
From CHANGELOG: the `stats` option was removed in v4, the default value of the `stats` option is taken from the value of the `stats` option from the configuration (`webpack.config.js`).

**Comment by lanmch** [comment]
> From CHANGELOG: the `stats` option was removed in v4, the default value of the `stats` option is taken from the value of the `stats` option from the configuration (`webpack.config.js`).

thanku i will try it

**Comment by evilebottnawi** [comment]
@ylemkimon thanks for help, yep `stats` was removed
