### ISSUE TITLE
 options has an unknown property 'logLevel'. These properties are valid:

### ISSUE THREAD

**Issue by chenjiajing23** [webpack/webpack-dev-middleware#766]
- Operating System:mac os 11.0.1
- Node Version:v15.2.1
- NPM Version:7.0.8
- webpack Version:5.4.0
- webpack-dev-middleware Version:4.0.2

### Expected Behavior
![image](https://user-images.githubusercontent.com/41351722/99390304-5c9f6700-2913-11eb-9127-630e50804423.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/41351722/99390225-3d083e80-2913-11eb-83d9-c7bfef54a3b7.png)
![image](https://user-images.githubusercontent.com/41351722/99390734-1d254a80-2914-11eb-94f1-3d9362f3f378.png)

### Code

```js
// webpack.config.js
const path = require('path');
const chalk = require('chalk');
const express = require('express');
const webpack = require('webpack');
const getPort = require('get-port');
const devMiddleware = require('webpack-dev-middleware');
const hotMiddleware = require('webpack-hot-middleware');
const { createProxyMiddleware } = require('http-proxy-middleware');

const config = require('../config');
const port = config.dev.port;
const webpackConfig = require('./webpack.dev');

const main = () => {
  getPort({
    port: getPort.makeRange(port, port + 100)
  }).then(newPort => {
    const app = express();
    const compiler = webpack(webpackConfig);

    const webpackDevMiddleware = devMiddleware(compiler, {
      // logLevel: 'silent',
      publicPath: webpackConfig.output.publicPath
    });

    const webpackHotMiddleware = hotMiddleware(compiler, {
      log: false,
      heartbeat: 2000,
      path: '/__hmr'
    });

    app.use(webpackDevMiddleware);
    app.use(webpackHotMiddleware);

    // proxy
    Object.keys(config.dev.proxyTable).forEach(context => {
      let options = config.dev.proxyTable[context];
      if (typeof options === 'string') {
        options = {
          target: options,
          proxyTimeout: 30 * 1000
        };
      }
      app.use(context, createProxyMiddleware(options.filter || context, options));
    });

    app.use('/ping', function (_req, res) {
      res.sendStatus(200);
    });

    const staticPath = path.posix.join(
      config.dev.assetsPublicPath,
      config.base.assetsSubDirectory
    );
    app.use(staticPath, express.static('./static'));

    console.log('> Starting dev server...');
    webpackDevMiddleware.waitUntilValid(() => {
      console.log(
        chalk.default.green(`> Listening at： ${config.dev.host}:${newPort} \n`)
      );
    });
    app.listen(newPort);
  });
};

main();

```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Respect time of other developers, please read changelog before update, this option was removed in v4

**Comment by chenjiajing23** [comment]
v3.7.2 is okay ，Did version 4.0.0 remove the logLevel attribute？
![image](https://user-images.githubusercontent.com/41351722/99391384-1814cb00-2915-11eb-97d2-52437fb3b294.png)

**Comment by evilebottnawi** [comment]
You, it was removed

**Comment by chenjiajing23** [comment]
> You, it was removed
thanks

**Comment by joebnb** [comment]
how to reduce this log,it interrupt progress bar,

![image](https://user-images.githubusercontent.com/1646883/99472474-a6c03100-2983-11eb-813e-fb472f01f4d2.png)

and remove <i> 

![image](https://user-images.githubusercontent.com/1646883/99472591-e8e97280-2983-11eb-9632-0c228193c496.png)

**Comment by evilebottnawi** [comment]
https://webpack.js.org/configuration/other-options/#infrastructurelogging
