### ISSUE TITLE
Unable to use loglevel in version 4.0.2

### ISSUE THREAD

**Issue by goelshobhit** [webpack/webpack-dev-middleware#774]
- Operating System: window 10
- Node Version: 14.15.0
- NPM Version: 6.14.8
- webpack Version: 5.6.0
- webpack-dev-middleware Version:4.0.2

### Expected Behavior

Should be able to use other options inside webpackDevMiddleware apart from below options.

schema: {
    type: 'object',
    properties: {
      mimeTypes: { type: 'object' },
      writeToDisk: { anyOf: [ { type: 'boolean' }, { instanceof: 'Function' } ] },
      methods: { type: 'array', items: { type: 'string' } },
      headers: { type: 'object' },
      publicPath: { type: 'string' },
      serverSideRender: { type: 'boolean' },
      outputFileSystem: { type: 'object' },
      index: { anyOf: [ { type: 'boolean' }, { type: 'string' } ] }
    },
    additionalProperties: false
  },
![Screenshot (30)](https://user-images.githubusercontent.com/26035935/100313679-1e710a00-2fdb-11eb-9e04-e2b8a3afba82.png)
![Screenshot (31)](https://user-images.githubusercontent.com/26035935/100313713-3052ad00-2fdb-11eb-932f-62bc881cb3f4.png)
### Actual Behavior

If i am using loglevel as a option. it throws error

```
      schemaPath: '#/additionalProperties',
      params: { additionalProperty: 'logLevel' },
      message: 'should NOT have additional properties',
```

### Code
```
function createWebpackMiddleware(compiler, publicPath) {
  const options = {
    logLevel: 'warn',
    publicPath,
  };
  return webpackDevMiddleware(compiler, options);
}
```

### How to reproduce.

- upgrade the webpack and webpack-dev-middleware version to the latest.
- if you pass loglevel as a options inside webpack-dev-middleware, you get the above issue on the terminal

**Comment by evilebottnawi** [comment]
Please read changelog, `logLevel` was removed
