### ISSUE TITLE
No colors appearing in terminal

### ISSUE THREAD

**Issue by CaiqueR** [webpack/webpack-dev-middleware#782]
In webpack-dev-middleware 3.7.2 it worked fine, but in version 4.0.2 it's showing <i> tag, <e> tag.

- Operating System: Ubuntu 20.04
- Node Version: 14.15.1
- NPM Version: 6.14.8
- webpack Version: 5.6.0
- webpack-dev-middleware Version: 4.0.2

### Expected Behavior
Show correct colors in terminal
![image](https://user-images.githubusercontent.com/42003129/101041387-28ef4e80-355b-11eb-846c-ba42fbfcf11f.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/42003129/101038356-525baa80-355a-11eb-8869-cfd0e2626735.png)

**Comment by alexander-akait** [comment]
It is breaking change, now it uses logger

**Comment by alexander-akait** [comment]
and respect `stats.colors`

**Comment by CaiqueR** [comment]
> It is breaking change, now it uses logger

Hmmm, and how to solve that?

**Comment by alexander-akait** [comment]
we should don't use `logger` for stats, I will fix it tomorrow

**Comment by CaiqueR** [comment]
> we should don't use `logger` for stats, I will fix it tomorrow

Ok, I'm waiting for the fix. Thank you

**Comment by alexander-akait** [comment]
Anyway, it remove `<i>` and will be output in `stdout`, about colors, you should check the `stats.colors` option

**Comment by CaiqueR** [comment]
> Anyway, it remove `<i>` and will be output in `stdout`, about colors, you should check the `stats.colors` option

I put it that way:
```javascript
webpackDevMiddleware(compiler, {
        publicPath: webpackConfig.output.publicPath,
        serverSideRender: true,
        stats: {
          colors: true,
        },
      })
```
But I get that error:
![image](https://user-images.githubusercontent.com/42003129/101166531-2fdb9700-3617-11eb-961b-5ff7a0e549dd.png)

**Comment by alexander-akait** [comment]
You need set `stats.colors: true` for `compiler`, i.e. `const compiler = webpack({ statis: { colors: true } })`

**Comment by aaarichter** [comment]
hi @alexander-akait 

I ran into the same issue, where setting `stats: { colors: true, }` to the webpack config solved the color problem. 

Can you elaborate how to get rid of the `<i>` ?

I also looked up the changelog and yes it is mentioned there, but in the RC changes. Shouldn't a major release include & highlight breaking changes? Skimming through various RCs is a bit cumbersome.

**Comment by alexander-akait** [comment]
> Can you elaborate how to get rid of the <i> ?

It is built-in, you can create custom logger, but it should output with stats, we are working on this, release will be today/tomorrow
