### ISSUE TITLE
Update peerDependencies to support webpack@^5.0.0 for webpack-dev-middleware@^3.7.2

### ISSUE THREAD

**Issue by 5paceman** [webpack/webpack-dev-middleware#797]
### Feature Proposal
Add `webpack@^5.0.0` as a valid peer dependency for `webpack-dev-middleware@^3.7.2`

### Feature Use Case
`webpack-dev-middleware` started to support `webpack@5` from [v3.7.2](https://github.com/webpack/webpack-dev-middleware/releases/tag/v3.7.2). Actually, the `peerDependencies` in [package.json](https://github.com/webpack/webpack-dev-middleware/blob/v3.7.2/package.json#L31) of `v3.7.2` only contains `webpack@^4.0.0`.
`webpack-dev-middleware@^3.7.2` is the dependency of `webpack-dev-server@3.11.0`. If `webpack@5` and `webpack-dev-server@3.11.0` are used at the same time, a warning message will be thrown when installing the dependencies:
```sh
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has incorrect peer dependency "webpack@^4.0.0".
```

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack/webpack-dev-middleware/releases/tag/v3.7.3
