### ISSUE TITLE
Doesn't reload the browser after re-compiling

### ISSUE THREAD

**Issue by okonet** [webpack/webpack-dev-middleware#8]
I'm not sure it's a bug but I'm trying to switch from watch-build cycle to using of connect + middleware. The only problem is that after recompiling the bundle browser doesn't reload it. If I do manual refresh I can see an updated bundle. Please advise where I can look for it.

**Comment by vincentpalita** [comment]
I found a way to do that very convenient by simulating how the webpack-hot-middleware works.
Inside your rewriteRules you can add: 

const config = webpack(webpackConfig);
`config.plugin('done', () => {
    try {
        browser.reload();
    } catch (e) {
    }
}),`
