### ISSUE TITLE
setupHook statsOptions.colors undefined

### ISSUE THREAD

**Issue by Ekhrapykin** [webpack/webpack-dev-middleware#814]
Hello,

After #583  for the exception:
`TypeError: Cannot read property 'colors' of undefined`

- Operating System:
- Node Version: v12.18.4
- NPM Version: 6.14.11
- webpack Version: 4.44.1
- webpack-dev-middleware Version: 4.0.3

### Expected Behavior

No error

### Actual Behavior

.../node_modules/webpack-dev-middleware/dist/utils/setupHooks.js:68
} else if (typeof statsOptions.colors === 'undefined' || typeof statsOptions === 'string') {
^

TypeError: Cannot read property 'colors' of undefined
at .../node_modules/webpack-dev-middleware/dist/utils/setupHooks.js:68:38
at processTicksAndRejections (internal/process/task_queues.js:79:11)

### Code

```js
  const devMiddleware = require("webpack-dev-middleware")(compiler, {
    publicPath: webpackConfig.output.publicPath
  });
<!--...-->
  app.use(devMiddleware);
```

**Comment by uinika** [comment]
webpack built 4333dbf8aa8a0bbf4aab in 13716ms
C:\Workspace\gd-diy-apply\node_modules\webpack-dev-middleware\dist\utils\setupHooks.js:68
      } else if (typeof statsOptions.colors === 'undefined' || typeof statsOptions === 'string') {
                                     ^

TypeError: Cannot read property 'colors' of undefined
    at C:\Workspace\gd-diy-apply\node_modules\webpack-dev-middleware\dist\utils\setupHooks.js:68:38
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aves@6.3.3 start: `node ./config/command/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aves@6.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhenghang\AppData\Roaming\npm-cache\_logs\2021-01-13T06_27_35_802Z-debug.log

**Comment by uinika** [comment]
I also got this problem...

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-dev-middleware/issues/815
