### ISSUE TITLE
Support  stats option for webpack-dev-middleware

### ISSUE THREAD

**Issue by clarkdo** [webpack/webpack-dev-middleware#818]
- Operating System: macOS Catalina
- Node Version: 14.8.0
- NPM Version: 6.14.0
- webpack Version: 4.46.0
- webpack-dev-middleware Version: 4.0.4

### Feature Proposal

Add `stats` option for `webpack-dev-middleware` to control stats printed by `webpack-dev-middleware`

### Feature Use Case

When we use custom plugins for stats output like [webpackbar](https://github.com/nuxt-contrib/webpackbar), we hope `webpack-dev-middleware` can have an option to control stats output from the middleware like: disabling stats log without overriding `stats` in webpack config.

More details can be found in https://github.com/webpack/webpack-dev-middleware/pull/817

**Comment by alexander-akait** [comment]
Thanks, I will implement this tomorrow

**Comment by clarkdo** [comment]
Thank you so much for the new option!

**Comment by alexander-akait** [comment]
Sorry for small delay

**Comment by clarkdo** [comment]
I just opened a pr for updating types definition. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50645

**Comment by alexander-akait** [comment]
I think we can implement built-in types here using typescript jsdocs (as we use in webpack and some other repos)

**Comment by alexander-akait** [comment]
If you want to help, feel free to send a PR :star:

**Comment by clarkdo** [comment]
I may have a look when I get a chance, feel free to go ahead if it's urgent.
