### ISSUE TITLE
Exclude some routes while bundling

### ISSUE THREAD

**Issue by shhlkien** [webpack/webpack-dev-middleware#819]
- Operating System: Ubuntu 20.04
- Node Version: v12.18.4
- NPM Version: 6.14.6
- webpack Version: 4.x
- webpack-dev-middleware Version: ^4.0.2

### Feature Proposal
Add a convenient API or option to exclude some routes from waiting while bundling

### Feature Use Case
When I'm developing API, I don't need to serve assets from webpack. Since `webpack-dev-middleware` delays all requests until bundle is valid, I have to wait seconds to minutes to access some routes with no assets. For example:

```js
app.use(webpackDevMiddleware(compiler, {
   excludeRoutes: ['/api-that-returns-json-only']
}))
...
app.use('/route-1', routeOne)
app.use('/route-2', routeTwo)
app.use('/api-that-returns-json-only', routeApi)
```
so it doesn't slow down development

**Comment by alexander-akait** [comment]
What is real use case? Can you provide example?

**Comment by shhlkien** [comment]
> What is real use case? Can you provide example?

The above example is real use case! What point don't you understand?

**Comment by shhlkien** [comment]
@alexander-akait 
 You can see more details [here](https://youtu.be/jnMl2g12i5w)

**Comment by alexander-akait** [comment]
The main problem - we don't know filename until we do build (also the `filename` option can be `Function`), such use case may not be safe in many cases, but if you have a clear structure, then such use is safe, but `excludeRoutes` is misleading, the best solution is provide `route` for `webpack-dev-middleware`, like `app.use('route', webpackDevMiddleware)`

**Comment by shhlkien** [comment]
I have thought about this and temporarily use it.  I want a more convenient way as described for those cases that have to be rewritten too much, but if not, then I have to deal with it. Anyway, thank you

**Comment by alexander-akait** [comment]
can you clarify? you can use `publicPath` as the `route` value (if `publicPath` is the string)

**Comment by shhlkien** [comment]
> can you clarify? you can use `publicPath` as the `route` value (if `publicPath` is the string)

Ok, I end up with this solution. Thank for your help!
