### ISSUE TITLE
asset/resource is not supported

### ISSUE THREAD

**Issue by mikalai-ramashka** [webpack/webpack-dev-middleware#827]
- Operating System: win 10
- Node Version: v14.15.4
- NPM Version: 6.14.10
- webpack Version: 5.18.0
- webpack-dev-middleware Version: 4.1.0

### Expected Behavior

`webpack-dev-middleware` will correctly work with `asset/resource` module type.

### Actual Behavior

Images are not served.

### Code

webpack.config.js:
```
output: {
   ..
  assetModuleFilename: '[name].[ext]'
},
...
{
  test: /(favicon\.ico|application-logo\.svg)$/,
  type: 'asset/resource'
},
```

main.tsx:
```
import '../../images/application-logo.svg';
```

node_modules\webpack-dev-middleware\dist\middleware.js:
```js
//request GET application-logo.svg

try {
  content = context.outputFileSystem.readFileSync(filename);
} catch (_ignoreError) { //no such file error
   await goNext();
   return;
}
```

### How Do We Reproduce?

I guess just use `type`: 'asset/resource' module type. BTW, with `file-loader` everything is working fine.

**Comment by alexander-akait** [comment]
Works fine, `How Do We Reproduce?` your information is not help to help you

**Comment by alexander-akait** [comment]
Double check you public path
