### ISSUE TITLE
webpack-dev-middleware needs a plugin to serve index.html whith webpack-dev-server does not

### ISSUE THREAD

**Issue by happybeing** [webpack/webpack-dev-middleware#829]
- Operating System: Ubuntu 20
- Node Version: v15.2.1
- NPM Version: n/a
- yarn version: 1.22.5
- webpack Version: 4.44.2
- webpack-dev-middleware Version: 4.1.0

### Expected Behavior

Should work if webpack-dev-server CLI works.

### Actual Behavior

Using the same `webpack.config.js` that works with `yarn webpack-dev-server`, the `webpack-dev-middleware` server gives 404 for the path '/'.

This was fixed by adding the `webpack-html-plugin` to serve 'index.html' as:
```javascript
new HtmlWebpackPlugin({
	filename: 'index.html',
	template: './public/index.html',
	title: 'Test server'
	})
```
### Code

```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');

const mode = process.env.NODE_ENV || 'development';
const prod = mode === 'production';
module.exports = {
	entry: {
		bundle: [__dirname + '/src/main.js']
	},
	resolve: {
		alias: {
			svelte: path.resolve('node_modules', 'svelte')
		},
		extensions: ['.mjs', '.js', '.svelte'],
		mainFields: ['svelte', 'browser', 'module', 'main']
	},
	output: {
		path: __dirname + '/public',
		filename: '[name].js',
		chunkFilename: '[name].[id].js'
	},
	module: {
		rules: [
			{
				test: /\.svelte$/,
				use: {
					loader: 'svelte-loader',
					options: {
						emitCss: true,
						hotReload: true
					}
				}
			},
			{
				test: /\.css$/,
				use: [
					/**
					 * MiniCssExtractPlugin doesn't support HMR.
					 * For developing, use 'style-loader' instead.
					 * */
					prod ? MiniCssExtractPlugin.loader : 'style-loader',
					'css-loader'
				]
			}
		]
	},
	mode,
	plugins: [
		new MiniCssExtractPlugin({
			filename: '[name].css'
		})
	],
	devtool: prod ? false: 'source-map'
};
```

### How Do We Reproduce?

Clone https://github.com/happybeing/p2p-git-portal-wasi

Save the following to 'devserver.js' in the root and run `node ./devserver.js`, then visit localhost:5333.
```js
const webpackConfig = require('./webpack.config.js');
const webpack = require('webpack');
const middleware = require('webpack-dev-middleware');
const compiler = webpack(webpackConfig);
const express = require('express');
const app = express();

app.use(
middleware(compiler, {
    // webpack-dev-middleware options
})
);

let port = 5333;
app.listen(port, () => console.log('devserver on port: ' + port));
```
```

**Comment by alexander-akait** [comment]
Can't understand problem, `webpack-dev-middleware` has `index` option for this case https://github.com/webpack/webpack-dev-middleware#index, just create `index.html` or setup `HtmlWebpackPlugin` to generate `index.html` for you, so this is expected

**Comment by alexander-akait** [comment]
If you have 404, it means you don't setup right `publicPath`, you output assets to `public`, setup `publicPath: '/public/'`

**Comment by happybeing** [comment]
Wow, thanks for the speedy response - not even time to make my coffee!

Are you saying it's expected that the CLI works but the middleware does not with the same config?

If so, maybe the documentation could include information about what the middleware requires in addition to the CLI.

**Comment by happybeing** [comment]
I forgot to mention that even after I got this working (by adding the HTML plugin, the bundle sizes and other console output are considerably different between running CLI and middleware, though both seem to serve the app. So I'm expecting there's more that I'll need to worry about later.

**Comment by alexander-akait** [comment]
As I see you use Node.js API, so you need specify `publicPath`, otherwise we just don't have `index.html` so nothing to handle

**Comment by happybeing** [comment]
There something I'm not understanding here. Can you explain the difference in behaviour with the CLI and the middleware? Just saying 'you need to do x' etc isn't helping me understand. 

I have already fixed the problem and have both working, so I created this issue because I think the same config should work with both CLI and middleware. If not, I'd like to understand why not, and maybe save others time by adding to the middleware README to make the difference clear.

If you clone the repo you'll see that `yarn webpack-dev-server` works without your suggestions or the HTML plugin. If I add the plugin, both the CLI and the middleware work (without your additional suggestions).

**Comment by alexander-akait** [comment]
I can't understand, what you expected? Auto creating `index.html`?

**Comment by happybeing** [comment]
Try cloning the repo. The config you seem to think won't work works with `yarn webpack-devserver`. Try it.

And if I add the HTML plugin, it works with the middleware too (using the script I included in the OP).

I'm not sure you have taken on board the reason I opened this issue. I'm NOT asking for help to fix a problem. At this point, I don't think I have a problem! I'm suggesting there's a bug that either needs fixing or a difference that could do with being documented.

**Comment by alexander-akait** [comment]
> Try cloning the repo. The config you seem to think won't work works with yarn webpack-devserver. Try it.

You need setup `contentBase` (or `static` for webpack-dev-server v4) to serve `public` directory (it is by default for v4). 

Yes behavior is different, because `webpack-dev-server` has more middlewares, `webpack-dev-middleware` it is only one part of complex server configurations (it handles only webpack generated files, that is why `HtmlWebpackPlugin` help you). I don't know what we should document here, because it decried in README, but if you have ideas feel free to send a PR and clarify something.

**Comment by happybeing** [comment]
The `HtmlWebpackPlugin` is irrelevant to my use case as I'm using static `index.html` amongst other things. My configuration was already working so the reason I opened this issue was not to get help with that, but thank you for your time. I will review the documentation and send a PR as you suggest, because I think it would help to clarify this.

If you this open I'll explain more here and will reference it in a PR which might help others confused by this (even if the PR is rejected).

**Comment by alexander-akait** [comment]
What I should explain here?

**Comment by happybeing** [comment]
Nothing, I'm not asking a question. I believe you've helped clarify the situation and I plan to create a PR to add this to the documentation. I will add that explanation to this issue to help any others who get stuck on this point.

**Comment by happybeing** [comment]
I've been looking at the webpack.js.org repo and after cloning it and building etc its quite an onerous process to contribute. As I've no idea if a PR would be accepted, and it's likely a one-off from me, I'm going to provide the information here instead. 

The following is written as if it appears under the heading [Using webpack-dev-middleware](https://webpack.js.org/guides/development/#using-webpack-dev-middleware), and before the heading ("Adjusting Your Text Editor"):

### Serving Static Content
The above example assumes you use the `HtmlWebpackPlugin` to provide an `index.html` for `webpack-dev-middleware`. If you wish to provide a static `index.html` file or other static content you need to provide middleware to serve this or it will not be found and cause a 404 error. The following example shows how to do this based on the example above but with the `HtmlWebpackPlugin` removed from the `webpack.config.js`. It assumes your `index.html` file is stored in `./dist` and loads the bundle files generated for you according to you your `webpack.config.js`. 
```js
const webpackConfig = require('../webpack.config.js');
const express = require('express');
let app = express();
let server;

async function startServer(port) {
	const webpack = require('webpack');
	const middleware = require('webpack-dev-middleware');
	const compiler = webpack(webpackConfig);

	app.use(express.static(webpackConfig.devServer.contentBase));
	app.use(
		middleware(compiler, {
			// webpack-dev-middleware options
		})
	);
	return new Promise(resolve => {
		server = app.listen(port, () => {
			console.log('devserver on port ' + port);
			resolve();
		});
		server = require('http-shutdown')(server);
	});
}
```
This is done for you if you are using `webpack-dev-server`, so you so it can be confusing if you find that `webpack-dev-server` works, but `webpack-dev-middleware` does not, for the same `webpack` configuration.
