### ISSUE TITLE
Unable to write to disk, Error: EROFS: read-only file system

### ISSUE THREAD

**Issue by mboisvertdupras** [webpack/webpack-dev-middleware#845]
- Operating System: Mac OS 11.2.1
- Node Version: 15.4.0
- NPM Version: 7.0.15
- webpack Version: 5.15.0
- webpack-dev-middleware Version: 3.7.3

### Expected Behavior

When using the `writeToDisk : true` option, files should be written to the output directory

### Actual Behavior

When trying to write the files, wdm outputs an error `｢wdm｣: Error: EROFS: read-only file system, open '/app.css'`

### Code

https://gist.github.com/mboisvertdupras/292f93e38a6cc7c1f547486e30e504de

### How Do We Reproduce?

The project is located here https://github.com/mboisvertdupras/kinetic

To test it, clone the repo and do a `npm i && npm run watch`

**Comment by ylemkimon** [comment]
The `outputPath` of file-loader is regarded as an absolute path: https://github.com/mboisvertdupras/kinetic/blob/167806ce11ef46409e968e85e97211fcd85f4e61/webpack.config.js#L36.

**Comment by alexander-akait** [comment]
Answer above, also do not use `file-loader`/`url-loader`/`raw-loader` with webpack v5 https://webpack.js.org/guides/asset-modules/
