### ISSUE TITLE
Types are broken with webpack 5. 

### ISSUE THREAD

**Issue by dopry** [webpack/webpack-dev-middleware#859]
For those of us using typescript we are running into issued with @types/webpack, @types/webpack-dev-middleware published by DefinitelyTyped.  It would be nice if this packaged included it's own types so we didn't need to depend on definitely typed..

see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49755 for context

**Comment by alexander-akait** [comment]
We don't have built-in types, please open an issue in `DefinitelyTyped`
