### ISSUE TITLE
Access memoryfs files

### ISSUE THREAD

**Issue by sunyang713** [webpack/webpack-dev-middleware#88]
Hi, so I know that this middleware automatically handles the serving of all assets from memory. However, is there a way to let express use this memoryFs for other middleware as well? So that I can, for example, use `res.render('myfile.ext')` where `myfile.ext` is also in the webpack-dev memoryFs?

**Comment by grrowl** [comment]
You can access the filesystem directly through the `fileSystem` property:

```
const devMiddleware = webpackDevMiddleware(compiler)
app.use(devMiddleware)

app.use((req, res) => {
  // rewrite the request to serve the index page
  console.log('serving index.html for', req.url)

  res.set('Content-Type', 'text/html')
  res.send(
    devMiddleware.fileSystem.readFileSync(config.output.path + 'index.html')
  )
})
```

**Comment by SpaceK33z** [comment]
@sunyang713, does the link @grrowl posted above answer your question? So you'd need to rewrite the request.

**Comment by sunyang713** [comment]
Not quite, rewriting requests doesn't achieve what I need, because I would still need to access the memoryFs. I also posted in the issue that grrowl linked. I've pasted below

>hi, so just to be clear, is it still okay to manually serve a file from devMiddleware.fileSystem? For my project, this is pretty important - i.e. I need to modify the index.html request handler that devMiddleware automatically implements. How exactly can I "rewrite requests" for devMiddleware.fileSystem files?

**Comment by SpaceK33z** [comment]
@sunyang713, could you tell me why you need to rewrite the request to `index.html`? Just understanding your usecase would help me. If you need to set a variable in your `index.html`, I would suggest to use [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin) instead. It allows you to pass custom variables and all other crazy stuff, without hacking the filesystem.

**Comment by sunyang713** [comment]
Thanks for the response. I want to be very clear about my use case, so this response is pretty long. I would be very happy to see if there's a nicer, /cleaner/ way to do this that the community has established, but at the time I hadn't found one, and I haven't found one since.

I do use html-webpack-plugin. I use it to add a hash after my javascript builds. At the same time, I use server-side rendering with react. I need to render some initial content, AFTER the server is running and `index.html` is generated with the correctly linked files. The solution I am trying to do is using html-webpack-plugin to generate `index.ejs`; I start with a base `template.ejs` and a generate a *new* template. Before I run the server, I start with some base template:

```ejs
   . . .
    <%= "\<% if (content) { %\>" %>
    <div id="root"><%= "\<%- content %\>" %></div>
    <%= "\<% } else { %\>" %>
   . . .
```

At the bottom of the file, the correct `index.js?1231243hash` file is linked. Then, when I run the server with webpack (in devo; prod vs devo explained later), html-webpack-plugin converts this to:

```ejs
   . . .
    <% if (content) { %>
    <div id="root"><%- content %></div>
    <% } else { %>
    . . .
```

So I've generated a template from a template, and I will then use this to server-render like so:
```javascript
app.set('view engine', 'ejs')
. . .
// on 200
res.render('index', renderApp())
```

where `renderApp` is a function that renders my react app server-side as a string, and returns an object such as:
```
{
    "content": "<react id stuff stuff stuff> ... ... . > .> "
}
```

And `res.render` will pass this in nicely.


... except here is the problem. In prod, I would build all of my javascript files before running my server. In this case, I guess I could manually change the linked javascript bundle with the correct hash each time, but that's not fun to do. In any case, the document lives in the filesystem and is easily accessed using the static-middleware provided by express.

In devo, I use webpack-dev-middleware which means all files are served from memory. This also means that the generated `index.ejs` is in memory. webpack-dev-middleware default looks for `index.html` as a response to `GET /`. So for the time being, I've been accessing the `memoryfs` as a hack. I rewrite the request to `/` to return

```javascript
ejs.render(getDocument(), { content })
```

where `getDocument()` is a function that looks like this in devo:

```
import path from 'path'
import compiler from 'compiler' // this is the webpack compiler

export default function getDocument() {
  const memoryFs = compiler.outputFileSystem
  const indexPath = path.resolve(process.cwd(), 'dist/index.ejs')
  return memoryFs.readFileSync(indexPath, 'utf8')
}
```

**Comment by SpaceK33z** [comment]
Wow. Okay. Did you take a look at #118? I'm not sure if it completely fits your usecase, but it has some similarities.

**Comment by axelpale** [comment]
Thanks @sunyang713 for sharing your solution. I stumbled upon this inconvenient issue myself too with a pretty similar tech stack. In my case, I have a single-page app (SPA) with client-side routing and URLs like /login, /invite, /item/123, and the root / of course. To provide a boring use case, if a user bookmarks the /item/123 and browses to it later on, the URL needs to work. The express server should response the request /item/123 with index.html in a manner identical to the requests /, /login, and /invite. Their routing is then made on the client.

However, in prod env this is easy as you showed but not so in dev env where I use the webpack-dev-middleware. The server-side code should have a file access to the webpacked index.html, then to be able to serve it for any valid URL the user throws at the server.

Fortunately in my case the solution was simple. Because my index.html is completely static in the first place, I am able to serve it without messing with webpack's temporary files. I lose the benefits of html uglification and other webpack feats but in dev environment that is ok. For a reference, the server-side catch-all route for the SPA then becomes:

    app.get('/*', function (req, res) {
      res.sendFile(path.resolve(__dirname, 'public', 'index.html');
    });

I hope this comment to expand and describe the perspective of the issue.

**Comment by SpaceK33z** [comment]
@axelpale, can't you do something like this:

```js
var webpackMiddleware = require("webpack-dev-middleware");
var historyApiFallback = require("connect-history-api-fallback");
var instance = webpackMiddleware(...);
app.use(instance);
app.use(historyApiFallback());
app.use(instance);
```

Note that using `app.use(instance)` twice is on purpose, without this rewriting the request doesn't work.

**Comment by axelpale** [comment]
@SpaceK33z Interesting! The first `app.use(instance)` catches `/index.html`. If not caught, then `app.use(historyApiFallback())` will catch `/any/thing` and rewrite it to `/index.html`, which is finally caught and served by the second `app.use(instance)`. I get it, cool, thanks!

**Comment by eduardoleal** [comment]
I tried to do something like @SpaceK33z 's but the express server does not respond.

```javascript
const express = require('express');
const path = require('path');
const app = express();
const historyApiFallback = require('connect-history-api-fallback');

if (process.env.NODE_ENV !== 'production') {
    const webpackMiddleware = require('webpack-dev-middleware');
    const webpack = require('webpack');
    const webpackConfig = require('./webpack.config.js');
    const webpackInstance = webpackMiddleware(webpack(webpackConfig));
    app.use(webpackInstance);
    app.use(historyApiFallback);
    app.use(webpackInstance);
} else {
    app.use(express.static('dist'));
    app.get('*', (req, res) => {
        res.sendFile(path.join(__dirname, 'dist/index.html'));
    })
}

app.listen(process.env.PORT || 3050, () => console.log('Listening...'));
```

I can't access react routes using browserHistory. It only works if i use hashHistory.

**Comment by anthonator** [comment]
@eduardoleal were you able to resolve this?

**Comment by anthonator** [comment]
Oops, you need to pass `historyApiFallback` in as a function.

@SpaceK33z's example is correct.

**Comment by eduardoleal** [comment]
Yes, @anthonator!
I'm using the following code:
```(javascript)
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
import 'babel-polyfill';
import express from 'express';
import path from 'path';
import webpackMiddleware from 'webpack-dev-middleware';
import webpack from 'webpack';
import prerender from 'prerender-node';
import webpackConfig from './webpack.config';

const app = express();

if (process.env.NODE_ENV !== 'production') {
  app.use(webpackMiddleware(webpack(webpackConfig)));
} else {
  app.use(prerender);
  app.use(express.static('build'));
  app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'build/index.html'));
  });
}

app.listen(process.env.PORT || 10090, () => {
  console.log('Listening...')
});

```

**Comment by shellscape** [comment]
Closing as there seems to be a good resolution here. If anyone would like to add this to the documentation, please open a PR 😄

**Comment by robbyemmert** [comment]
There really needs to be a more intuitive solution. Adding the instance twice seems really hacky. Is there a good reason that there isn't an equivalent historyApiFallback option in webpack-dev-middleware? This seems like a really common use case that deserves a setting.

**Comment by robbyemmert** [comment]
Also, could there be performance concerns with adding webpack twice?

**Comment by shellscape** [comment]
@robbyemmert it looks like you may be new to Github, so please do note that it's a best practice to _edit a previous comment_ to add more info, rather than posting a comment shortly after a previously posted comment.

I'm not sure you're fully understanding the solutions provided in this thread, as neither of the latest examples "add webpack" . Regardless, there's a new feature in `writeToDisk` you may want to take a look at. You can find more information [in the README](https://github.com/webpack/webpack-dev-middleware#writetodisk).
