### ISSUE TITLE
enable use other than express

### ISSUE THREAD

**Issue by noahehall** [webpack/webpack-dev-middleware#945]
- Operating System: ubuntu
- Node Version: latest
- NPM Version: latest
- webpack Version: latest
- webpack-dev-middleware Version: latest

### Feature Proposal
enable use of other backends. [similar to my hacky approach here](https://github.com/noahehall/webpack-dev-middleware/blob/972e5fdcd227abd87badb7e75cbeba61ae095192/src/middleware.js#L12)

if I could just say 'hey use this middleware instead of the default one' that would make my life really easier

thx!

### Feature Use Case
i want to use koa, and koa-webpack doesnt work with webpack5

**Comment by anshumanv** [comment]
Seems fair, if there are no means already to support this, @alexander-akait what do you think?

**Comment by noahehall** [comment]
[here is a working example](https://github.com/noahehall/nodeproto/blob/dev/apps/client/bff/server.mjs)

**Comment by alexander-akait** [comment]
Yes, why not, PR welcome

**Comment by alexander-akait** [comment]
We already support connect, express and fastify https://github.com/webpack/webpack-dev-middleware#fastify

**Comment by anshumanv** [comment]
> Yes, why not, PR welcome

will PR 👍

**Comment by alexander-akait** [comment]
Don't forget to add tests :smile:

**Comment by anshumanv** [comment]
yep, any better name for option?

**Comment by alexander-akait** [comment]
No need option, it is internal changes, maybe it will work already, maybe we need to use other API to get headers or something else

**Comment by alexander-akait** [comment]
Example of pure API and express https://github.com/webpack/webpack-dev-middleware/blob/master/src/middleware.js#L105

**Comment by noahehall** [comment]
you guys are awesome. @alexander-akait 

im planning on testing this tonight. sorry for the delay

**Comment by IanVS** [comment]
Hi, in my understanding, using fastify-express essentially means that you run an express server inside of fastify.  I'd really like to use actual fastify.  Does anyone know of any options to do this?

**Comment by alexander-akait** [comment]
I can accept PR for adding fastify here and for dev server too

**Comment by alexander-akait** [comment]
We want to move `webpack-dev-middleware` to `webpack-dev-server` (and make it monorepo, so all packages related to dev server will be in one place), so I want to close this in favor https://github.com/webpack/webpack-dev-server/issues/4741, we still consider it (and I think we will implement this after the next major release)
