### ISSUE TITLE
Ability to disable "middleware delays requests until compiling has completed." for custom proxy middleware

### ISSUE THREAD

**Issue by Rush** [webpack/webpack-dev-middleware#966]
- Operating System: openSUSE Tumbleweed
- Node Version: 14
- NPM Version: newest
- webpack Version: newest
- webpack-dev-middleware Version: newest

### Feature Proposal
Ability to disable "middleware delays requests until compiling has completed." for custom proxy middleware

### Feature Use Case
Forwarding API and Websocket requests to a separate Node.JS process. Today, all API / requests need to wait for the entire frontend rebult to complete which does not seem necessary.

**Comment by alexander-akait** [comment]
You can do it on own side, just create custom proxy server

**Comment by Rush** [comment]
It needs to run on the same port so it needs to reuse the http server. A viable solution would be to allow hooking before the "wait for changes" middleware is set up.

**Comment by alexander-akait** [comment]
We can implement `filter` option to filter request
