### ISSUE TITLE
How can I show the error infomation to the browser

### ISSUE THREAD

**Issue by ioriandy4** [webpack/webpack-dev-middleware#984]
How can I show the error infomation to the browser ？ In the webpack-dev-server，i can use the options 
`
devServer: {
    overlay: {
      warnings: true,
      errors: true
    }
  }
`
But how can I show the error infomation in webpack-dev-middleware ?

**Comment by alexander-akait** [comment]
`webpack-dev-middleware` for handling assets, we need `webpack-client-hot-middleware` for this, it will be in future (in our roadmap), after stable release, overlay is out of scope webpack-dev-middleware
