### ISSUE TITLE
Configuration with SSL

### ISSUE THREAD

**Issue by buzinas** [webpack/webpack-dev-middleware#99]
I'm not being able to make webpack-dev-middleware work with SSL enabled.

Do you have any examples, or can you help me with how should I proceed?

**Comment by mattijsbliek** [comment]
SSL doesn't seem to be supported. I checked the source and it [explicitly ignores urls with https](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L131).

**Comment by SpaceK33z** [comment]
Have you looked at the implementation in [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js)? It has an option for HTTPS.

**Comment by buzinas** [comment]
In fact, when I opened the issue the problem was occurring, but a few days ago the problem was gone, I'm not sure why (I updated some dependencies, but I didn't notice if webpack-dev-middleware was one of them.

**Comment by evilebottnawi** [comment]
@aemonge Not related to `webpack-dev-middleware`

**Comment by aemonge** [comment]
So webpack-dev-middleware isn't the reverse proxy for webpack ?

I know I posted a framework specific configuration file, but I'm only asking for documentation for creating a secure reverse proxy with webpack-dev-middleware.

I hope I can clarify my doubt.
